#!/usr/bin/env python3
"""Ch 69 Hepatitis B Virus : Part 1 — Book p1036-1038, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 69

# ---------------------------------------------------------------- p1036
p1036 = [
    ("fillup",
     "Fill up (Structure): HBV is a DNA ______ virus; its genome is partially double stranded, ______ circular dsDNA.",
     ["Hepadna; relaxed", "Hepe; supercoiled", "Picorna; linear", "Flavi; covalently closed"],
     "'DNA : Hepadnavirus. Partially double stranded : Relaxed circular dsDNA.' Figure caption: 'Relaxed circular dsDNA'."),
    ("match",
     "Match — 1) Incomplete (+) strand 2) Complete (−) strand … A) Reverse transcriptase / polymerase B) Primer",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Incomplete (+) strand : primer; Complete (−) strand : Reverse transcriptase / polymerase.'"),
    ("numeric",
     "Infective virion size and name, number of genotypes, and number of ORFs — as printed?",
     ["42 nm Dane particle; 10 genotypes; 4 ORFs", "27 nm Dane particle; 6 genotypes; 3 ORFs", "42 nm Australia particle; 8 genotypes; 5 ORFs", "22 nm Dane particle; 10 genotypes; 4 ORFs"],
     "'Infective particle (virion) : 42 nm Dane particle; 10 genotypes in HBV; 4 open reading frames (ORFs)'."),
    ("oddoneout",
     "Which ORF label does NOT appear in the circular genome figure?",
     ["ORF E", "ORF Pre S1", "ORF X", "ORF Core"],
     "Figure labels: ORF Pre S1, ORF Pre S2, HBsAg gene, ORF S, ORF P, Polymerase gene, ORF X, ORF Core, Pre C. There is no separate 'ORF E'."),
    ("match",
     "Gene table — match — 1) S-gene 2) C-gene 3) Pre C-gene … A) HBeAg, qualitative marker of infectivity & replication B) HBsAg, surface protein C) HBcAg, core protein (intracellular; anti-HBcAg in blood)",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A"],
     "S-gene → HBsAg surface protein; C-gene → HBcAg core protein (intracellular; anti-HBcAg in blood); Pre C-gene (part of C-gene) → HBeAg qualitative marker of infectivity & replication."),
    ("match",
     "Gene table continued — match — 1) P-gene 2) X-gene … A) HBx Ag, associated with hepatocellular carcinoma B) Polymerase, reverse transcriptase enzyme",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "P-gene → polymerase / reverse transcriptase enzyme; X-gene → HBx Ag associated with HCC."),
    ("truefalse",
     "Judge from the table: I HBcAg is intracellular and only its antibody is detected in blood. II HBeAg is a quantitative marker of replication.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "'Core protein (Intracellular anti-HBcAg : in blood)'; HBeAg is the 'Qualitative marker of infectivity & replication' (HBV DNA is the quantitative marker, p1037)."),
    ("numeric",
     "Progression diagram: incubation period, and the outcome percentages after acute hepatitis?",
     ["60 days; recovery 95–99%, chronic hepatitis 1–5%", "30 days; recovery 80%, chronic 20%", "40 days; recovery 95%, chronic 5%", "60 days; recovery 50%, chronic 50%"],
     "'Virus entry —60 days Incubation Period (IP)→ Acute hepatitis → 95–99% Recovery / 1–5% Chronic hepatitis'."),
    ("fillup",
     "Fill up: In the progression diagram, chronic hepatitis follows ______ transmission in ______%.",
     ["vertical; 95", "sexual; 30", "percutaneous; 6–30", "transfusion; 5–20"],
     "'95% Vertical transmission' arrow into Chronic hepatitis."),
    ("oddoneout",
     "Which is NOT one of the three end-points drawn from cirrhosis in the progression diagram?",
     ["Cholangiocarcinoma", "Portal hypertension", "Hepatocellular carcinoma", "Liver failure"],
     "Cirrhosis → Portal hypertension; Hepatocellular carcinoma; Liver failure. Notes: 'Also seen: NASH' (direct HCC arrow) and 'No treatment available.'"),
    ("numeric",
     "Infectivity of HBV relative to HIV and HCV, as printed?",
     ["100× as HIV, 10× as HCV", "10× as HIV, 100× as HCV", "50× as HIV, 5× as HCV", "Equal to HIV, 10× HCV"],
     "'100x as HIV, 10x as HCV'."),
    ("match",
     "Genotype notes — match — 1) HAV 2) HEV 3) HBV commonest genotype 4) HBV HCC-risk genotype … A) 4 genotypes B) Genotype C C) 1 genotype D) Genotype A",
     ["1-C, 2-A, 3-D, 4-B", "1-A, 2-C, 3-B, 4-D", "1-C, 2-A, 3-B, 4-D", "1-D, 2-A, 3-C, 4-B"],
     "'1 genotype in HAV, 4 in HEV → Commonest : Genotype A; HCC risk : Genotype C'."),
    ("recall",
     "HBV is 'found in all body fluids except ______'.",
     ["stools", "saliva", "breast milk", "semen"],
     "'Found in all body fluids except stools.'"),
    ("scenario",
     "A pregnant woman is HBsAg-positive. Applying the printed 90/10 rule, what determines whether transmission risk is 90% or 10%?",
     ["HBeAg status: HBeAg +ve → 90%, HBeAg −ve → 10%", "Anti-HBs titre: <10 mIU/mL → 90%", "Mode of delivery: vaginal 90%, caesarean 10%", "Trimester of infection: third 90%, first 10%"],
     "'Pregnancy : 90/10 rule — HBsAg +ve + HBeAg +ve : 90% chance of transmission; HBeAg −ve : 10% chance.'"),
]

# ---------------------------------------------------------------- p1037
p1037 = [
    ("oddoneout",
     "Mode of transmission tree for acute hepatitis B — which is NOT one of the four printed arms?",
     ["Feco-oral", "Vertical", "Percutaneous", "Blood transfusion"],
     "Arms: Vertical, Percutaneous, Sexual, Blood transfusion. 'No feco-oral / breast milk transmission.'"),
    ("numeric",
     "Percutaneous risk figures printed for HBV and HCV?",
     ["HBV 6–30%; HCV 0.6–6.1%", "HBV 0.3%; HCV 3%", "HBV 30–60%; HCV 6–10%", "HBV 90%; HCV 10%"],
     "'Percutaneous — Risk : 6 – 30%; HCV Risk : 0.6 – 6.1%'."),
    ("truefalse",
     "Judge: I Sexual transmission risk is printed as 'not established'. II Blood-transfusion risk is 1 : 200,000 units and 1 : 1,800,000 with HBV > HBC (HCV).",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Sexual : Not established'; 'Blood Transfusion : 1 : 200000 units; 1 : 1800000 [HBV > HBC]'."),
    ("recall",
     "Post-transfusion hepatitis — which hierarchy of agents is printed?",
     ["CMV > EBV > HCV", "HBV > HCV > CMV", "HCV > HBV > EBV", "EBV > CMV > HBV"],
     "'Post Transfusion Hepatitis : Hepatitis following transfusion • CMV > EBV > HCV.'"),
    ("numeric",
     "Symptoms of acute hepatitis B: duration of prodrome and when it appears?",
     ["2–3 days of prodromal phase after 60 days of IP", "2–3 weeks of prodrome after 30 days IP", "7 days of prodrome after 40 days IP", "No prodrome; abrupt jaundice at 60 days"],
     "'2–3 days of prodromal phase after 60 days of IP. Jaundice + ↑↑ enzymes (ALT/AST).'"),
    ("match",
     "Investigations — match — 1) Anti-HAV IgM 2) Anti-HEV IgM … A) m/c cause in adults B) m/c cause in children",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Anti-HAV IgM (m/c cause : children). Anti-HEV IgM (m/c cause : adults). if both −ve → HBsAg, HBeAg, anti-HBc IgM.'"),
    ("match",
     "HBV marker curve — match — 1) dark blue 2) red 3) green 4) purple … A) Anti-HBs B) HBsAg C) Total anti-HBc D) IgM anti-HBc",
     ["1-B, 2-D, 3-C, 4-A", "1-A, 2-B, 3-D, 4-C", "1-B, 2-C, 3-D, 4-A", "1-D, 2-B, 3-C, 4-A"],
     "Legend: HBsAg (blue), IgM Anti-HBc (red), Total Anti-HBc (green), Anti-HBs (purple)."),
    ("numeric",
     "On the 'HBV infection markers' graph, the boxed window period sits between which weeks after exposure?",
     ["Approximately 24–32 weeks", "Approximately 4–8 weeks", "Approximately 12–16 weeks", "Approximately 52–100 weeks"],
     "The 'Window period' box lies over the 24–32-week span, after HBsAg falls and before anti-HBs rises; upper bands show HBeAg then Anti-HBe."),
    ("match",
     "Interpretation table — match — 1) HBsAg +, HBeAg +, anti-HBc IgM + 2) HBsAg +, HBeAg −, anti-HBc IgM + … A) Low infectivity & replication / pre-core gene mutant (unable to express HBeAg) B) Acute hepatitis with ↑ infectivity & replication",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Column 1 (all +): acute hepatitis with ↑ infectivity & replication. Column 2 (HBeAg −): low infectivity & replication / Pre core gene mutant unable to express HBeAg."),
    ("fillup",
     "Fill up (right-hand bullets): S gene / A gene / Escape / Occult gene mutation → ↓ viral load, won't express ______; best test: ______.",
     ["HBsAg; anti-HBc IgM", "HBeAg; HBV DNA", "HBcAg; anti-HBs", "HBxAg; HBeAg"],
     "'Sgene/A gene/Escape/Occult gene mutation : ↓ viral load – Won't express HBsAg. Best test : Anti HBc IgM.'"),
    ("numeric",
     "Basal core mutant expresses what percentage of HBeAg, per the bullet?",
     ["30%", "0%", "90%", "10%"],
     "'Basal core mutant : Express 30% of HBeAg.'"),
    ("recall",
     "What is printed as the best marker for acute hepatitis at the bottom of the page?",
     ["HBV DNA load (quantitative marker)", "HBeAg (qualitative marker)", "Anti-HBc IgM", "HBsAg titre"],
     "'Best marker for acute hepatitis : HBV DNA load (Quantitative marker).' (Anti-HBc IgM is the best test for escape/occult mutants.)"),
]

# ---------------------------------------------------------------- p1038
p1038 = [
    ("match",
     "Progression table — match — 1) Recovery 2) Chronic hepatitis 3) AFH with simple HBV infection 4) AFH with HBV + HDV co-infection … A) 5–20% B) 0.1–1% C) 95–99% D) 1–5%",
     ["1-C, 2-D, 3-B, 4-A", "1-C, 2-D, 3-A, 4-B", "1-D, 2-C, 3-B, 4-A", "1-C, 2-B, 3-D, 4-A"],
     "Recovery 95–99%; Chronic hepatitis 1–5%; Acute fulminant hepatitis: simple HBV 0.1–1%, HBV + HDV coinfection 5–20%."),
    ("numeric",
     "Follow-up is done after how long, per the printed bullet?",
     ["24 weeks since IP / 12–16 weeks of symptom onset", "6 weeks since IP / 2 weeks of symptoms", "52 weeks since IP", "24 weeks of symptom onset / 12–16 weeks since IP"],
     "'After 24 weeks since IP/12–16 wks of symptom onset'."),
    ("match",
     "Follow-up conversions — match — 1) HBsAg 2) Anti-HBc IgG 3) HBeAg … A) converts to anti-HBeAg B) converts to anti-HBsAg C) converts to anti-HBc IgM (as printed)",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A"],
     "Printed: 'HBsAg converts→ anti HBsAg; Anti HBc IgG converts→ Anti HBc IgM; HBeAg → anti HBeAg' — all three bracketed as Recovery. (Note: the printed IgG→IgM direction is the reverse of the usual IgM→IgG class switch; taught here as written.)"),
    ("recall",
     "Per the follow-up bullet, which serological pair defines chronic hepatitis?",
     ["HBsAg +ve, anti-HBc IgG +ve", "HBsAg −ve, anti-HBs +ve", "HBeAg −ve, anti-HBe +ve", "Anti-HBc IgM +ve alone"],
     "'HBsAg +ve, anti HBc IgG +ve : Chronic hepatitis'."),
    ("scenario",
     "Chronic hepatitis profile: HBsAg + and anti-HBc IgG +; HBeAg is POSITIVE. What HBV DNA threshold and interpretation does the flowchart give?",
     ["HBV DNA load > 20,000 IU/mL — high infectivity, high replication", "HBV DNA load > 2,000 IU/mL — high infectivity, high replication", "HBV DNA load < 2,000 IU/mL — low infectivity, carrier state", "HBV DNA at any level — carrier, no need of Rx but HCC risk"],
     "'+ve → HBV DNA load > 20000 IU/mL → High infectivity, high replication'."),
    ("match",
     "HBeAg NEGATIVE branch — match — 1) HBV DNA > 2,000 IU/mL 2) HBV DNA < 2,000 IU/mL … A) Low infectivity, low replication → carriers B) High infectivity, high replication",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "HBeAg −ve: HBV DNA > 2000 → high infectivity/replication; < 2000 → low infectivity/replication → Carriers."),
    ("truefalse",
     "Carriers (HBeAg −, DNA < 2000) — judge: I No need of Rx. II No risk for HCC.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "'Carriers → No need of Rx; Risk for HCC.'"),
    ("oddoneout",
     "Pre-core / basal core mutant carries a very poor prognosis with ↑ risk for three outcomes. Which is NOT listed?",
     ["Hepatorenal syndrome", "HCC", "Cirrhosis", "Decompensation"],
     "'Pre-Core / Basal Core mutant : very poor prognosis; ↑ risk for HCC, Cirrhosis, Decompensation.'"),
    ("match",
     "Serological patterns table — match — 1) HBsAg + / anti-HBs − / anti-HBc IgM / HBeAg + / anti-HBe − 2) HBsAg + / anti-HBs − / anti-HBc IgG / HBeAg + / anti-HBe − … A) Chronic hepatitis B, high infectivity B) Acute hepatitis B, high infectivity",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Row 1: acute hepatitis B, high infectivity (IgM). Row 2: chronic hepatitis B, high infectivity (IgG)."),
    ("scenario",
     "Serology: HBsAg +, anti-HBs −, anti-HBc IgG, HBeAg −, anti-HBe −. Give the two printed interpretations and the confirmatory step.",
     ["Late acute or chronic hepatitis B with low infectivity, OR HBeAg-negative (precore-mutant) hepatitis B — do HBV DNA to confirm", "Window period of seroconversion from HBsAg to anti-HBs, OR heterotypic anti-HBs — repeat anti-HBs in 4 weeks", "Recovery from hepatitis B, OR hepatitis B in the remote past — no further test is needed", "Acute reactivation of chronic hepatitis B, OR escape mutant — do anti-HBc IgM to confirm"],
     "Row 3: '1. Late acute or chronic hepatitis B, low infectivity 2. HBeAg negative (Precore-mutant) hepatitis B (Chronic or, rarely, acute). Do HBV DNA to confirm'."),
    ("scenario",
     "Serology: HBsAg +, anti-HBs +, anti-HBc +, HBeAg ±, anti-HBe ±. Which pair of interpretations is printed, and which is labelled common vs rare?",
     ["HBsAg of one subtype with heterotypic anti-HBs (common); seroconversion from HBsAg to anti-HBs in progress (rare, window period)", "Acute reactivation of chronic hepatitis B (common); S-gene escape mutant that fails to express HBsAg (rare)", "Recovery from hepatitis B with persisting antigenaemia (common); hepatitis B in the remote past (rare)", "Immunisation with HBsAg vaccine plus passive HBIG (common); occult HBV with low viral load (rare)"],
     "Row 4: '1. HBsAg of one subtype and heterotypic anti-HBs (common) 2. Process of seroconversion from HBsAg to anti HBs (rare) (window period)'."),
    ("recall",
     "Serology: HBsAg −, anti-HBs −, anti-HBc IgM, HBeAg ±, anti-HBe ±. Interpretation?",
     ["Acute reactivation of chronic hepatitis B", "Acute hepatitis B, high infectivity", "Hepatitis B in remote past", "Immunisation"],
     "Row 5: 'Acute reactivation of chronic hepatitis B'."),
    ("match",
     "Last three rows — match — 1) HBsAg −, anti-HBs −, anti-HBc IgG, HBeAg −, anti-HBe ± 2) HBsAg −, anti-HBs +, anti-HBc IgG, HBeAg −, anti-HBe ± 3) HBsAg −, anti-HBs +, anti-HBc −, HBeAg −, anti-HBe − … A) Recovery from hepatitis B B) Immunisation with HBsAg (after vaccination) C) Hepatitis B in remote past, or escape mutant",
     ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "Row 6: remote past / escape mutant (anti-HBc alone). Row 7: recovery (anti-HBs + anti-HBc). Row 8: immunisation (anti-HBs alone)."),
    ("oddoneout",
     "Which single-marker pattern distinguishes vaccination from natural recovery in the serological table?",
     ["Anti-HBc is absent after vaccination but present after recovery", "Anti-HBe is present after vaccination but absent after recovery", "HBeAg is positive after vaccination", "Anti-HBs is absent after vaccination"],
     "Immunisation row: anti-HBs + with anti-HBc −; recovery row: anti-HBs + with anti-HBc IgG."),
]

write_part(CH, "p1036a", 1036, "HBV structure, genome figure, gene table, progression, infectivity, genotypes, pregnancy 90/10", p1036)
write_part(CH, "p1037a", 1037, "Acute hepatitis B: transmission, post-transfusion hepatitis, symptoms, investigations, marker curve, interpretation", p1037)
write_part(CH, "p1038a", 1038, "Progression table, follow-up conversions, chronic hepatitis profile, mutants, serological patterns table", p1038)

write_units(CH, [
    {"title": "HBV structure, genes and natural history",
     "sec": "Virology · p1036",
     "guide": "Hepadnavirus, relaxed circular partially dsDNA, (+) incomplete primer / (−) complete RT; 42 nm Dane, 10 genotypes, 4 ORFs; S→HBsAg, C→HBcAg (intracellular), pre-C→HBeAg qualitative, P→polymerase/RT, X→HBxAg HCC; 60-day IP, 95–99% recovery, 1–5% chronic (95% vertical), cirrhosis → PHTN/HCC/liver failure, NASH also, no treatment; 100× HIV, 10× HCV; HAV 1, HEV 4 genotypes, A commonest, C HCC; all fluids except stool; 90/10 rule by HBeAg.",
     "parts": ["p1036a"]},
    {"title": "Acute hepatitis B: transmission, symptoms, markers and interpretation",
     "sec": "Acute HBV · p1037",
     "guide": "Vertical, percutaneous 6–30% (HCV 0.6–6.1%), sexual not established, transfusion 1:200,000 & 1:1,800,000 HBV>HCV; no feco-oral/breast milk; post-transfusion CMV>EBV>HCV; 2–3 day prodrome after 60 days; anti-HAV IgM children, anti-HEV IgM adults → HBsAg/HBeAg/anti-HBc IgM; marker curve colours and 24–32 wk window; HBeAg + vs − interpretation, pre-core mutant; S/escape/occult mutants lose HBsAg, best test anti-HBc IgM; basal core mutant 30% HBeAg; HBV DNA best acute marker.",
     "parts": ["p1037a"]},
    {"title": "Progression, follow-up, chronic profile and serological patterns",
     "sec": "Chronic HBV & serology · p1038",
     "guide": "Recovery 95–99%, chronic 1–5%, AFH 0.1–1% vs 5–20% with HDV; follow-up 24 wk/12–16 wk; conversions to anti-HBs, anti-HBc IgM (as printed), anti-HBe = recovery; HBsAg + anti-HBc IgG = chronic; HBeAg + → DNA >20,000; HBeAg − → >2,000 high vs <2,000 carriers (no Rx, HCC risk); pre-core/basal core mutant poor prognosis; 8-row serological pattern table including window, reactivation, remote/escape, recovery, immunisation.",
     "parts": ["p1038a"]},
])
