#!/usr/bin/env python3
"""Ch 64 Biliary Cirrhosis — Book p1020-1022, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 64

# ---------------------------------------------------------------- p1020
p1020 = [
    ("fillup",
     "Fill up (opening line of the chapter): Primary Biliary Cirrhosis / Primary Biliary Cholangitis is the cardinal example of ______ cholestasis.",
     ["intrahepatic", "extrahepatic obstructive", "post-hepatic", "pre-hepatic haemolytic"],
     "The chapter opens: 'Cardinal example of intrahepatic cholestasis.'"),
    ("truefalse",
     "Judge the two statements from the printed definition of PBC: I It is an autoimmune disease with chronic progressive non-suppurative inflammatory destruction. II The target is the large extrahepatic bile ducts.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "Definition: autoimmune, chronic progressive non-suppurative inflammatory destruction of SMALL intrahepatic / intralobular bile ducts — not the large extrahepatic ducts."),
    ("recall",
     "According to the printed definition, the destruction of small intrahepatic / intralobular bile ducts in PBC is mediated by which immune arm?",
     ["Both T-cell and B-cell, with T-cell predominating over B-cell", "B-cell only, via complement-fixing antibody", "T-cell only, with no antibody contribution", "Neutrophil-mediated suppurative injury"],
     "The arrow below the definition reads 'mediated by both T-cell > B-cell'."),
    ("numeric",
     "Antimitochondrial antibody (AMA) is printed as positive in what proportion of PBC patients?",
     ["95%", "50%", "100%", "60–65%"],
     "'Antimitochondrial Ab (AMA) 95%.' (ANA is the 50% antibody listed later on p1021.)"),
    ("fillup",
     "Fill up: In PBC the antimitochondrial antibody is directed against ______.",
     ["PDHE2 (pyruvate dehydrogenase enzyme type-2)", "SLA (soluble liver antigen)", "LKM-1 (liver-kidney microsome type 1)", "ATP7B (Wilson ATPase)"],
     "'Against : PDHE2.' The footnote to the Note table expands it: 'PDHE2 : Pyruvate dehydrogenase enzyme type-2'."),
    ("match",
     "Match each column of the Note table (Hepatic vs Cholestatic pattern) with its printed content — 1) Hepatic 2) Cholestatic … A) Fatigue and pruritus, progressing through complete destruction of bile duct to jaundice (poor prognosis) B) Jaundice as the predominant feature",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Note table: Hepatic column = 'Jaundice (predominant feature)'; Cholestatic column = 'Fatigue & pruritus → complete destruction of bile duct → Jaundice (Poor prognosis)'."),
    ("scenario",
     "A patient with PBC who for years had only fatigue and pruritus now develops jaundice. Per the Note table's cholestatic column, what does this jaundice signify?",
     ["Complete destruction of the bile ducts and a poor prognosis", "Onset of the hepatic pattern, which carries the better prognosis", "Transient viral superinfection unrelated to duct loss", "Successful response to UDCA with ductular regeneration"],
     "In the cholestatic column the arrow runs fatigue & pruritus → 'Complete destruction of bile duct' → 'Jaundice (Poor prognosis)'."),
    ("numeric",
     "What female-to-male ratio and age band are printed under 'Prevalence' of PBC?",
     ["F > M = 9 : 1; 4th–5th decade", "F > M = 3 : 1; 2nd–3rd decade", "M > F = 2 : 1; 2nd–3rd decade", "F = M; 6th–7th decade"],
     "Prevalence: 'F > M = 9 : 1. 4th – 5th decade.'"),
    ("oddoneout",
     "Which of the following is NOT one of the three disease associations listed for PBC on this page?",
     ["Ulcerative colitis", "Sjogren syndrome with arthritis", "Distal RTA (Type 1)", "Gallstones"],
     "Disease association list: Sjogren syndrome with arthritis, Distal RTA (Type 1), Gallstones. Ulcerative colitis is the PSC association (p1021)."),
    ("management",
     "Diagnostic algorithm: a patient with cholestasis undergoes ultrasound. Duct dilatation is ABSENT. What is the next printed step?",
     ["Check AMA antibody; if positive, diagnose PBC", "Refer to surgery", "Proceed directly to liver transplant listing", "Start empirical UDCA and reassess in 6 months"],
     "Algorithm: Patient with cholestasis → Ultrasound: look for duct dilatation → −ve → AMA Ab → +ve → PBC."),
    ("management",
     "In the same algorithm, ultrasound shows duct dilatation (+ve). What does the book direct?",
     ["Refer to surgery", "Test AMA antibody", "Perform liver biopsy for florid duct lesion", "Start obeticholic acid"],
     "Ultrasound +ve for duct dilatation → 'Refer to surgery' (obstructive / extrahepatic cause)."),
    ("truefalse",
     "Presentation of PBC — judge: I Asymptomatic is the most common presentation. II Pruritus is the most common symptom.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "'Asymptomatic (m/c presentation)', 'Fatigue (m/c symptom)', then Pruritus as a separate bullet."),
    ("numeric",
     "Jaundice occurs in what percentage of PBC patients, and how is it characterised in the presentation list?",
     ["10%; late presentation with poor prognosis", "30–40%; early presentation with good prognosis", "<15%; incidental finding", "95%; presenting feature"],
     "'Jaundice (10%) : Late presentation (Poor prognosis).'"),
    ("fillup",
     "Fill up the bracket exactly as printed beside hypercholesterolemia in the PBC presentation list: 'Hypercholesterolemia (Against : ______)'.",
     ["Dihydrolipoyl transacetylase", "Pyruvate carboxylase", "Farnesoid X receptor", "Lipoprotein lipase"],
     "The bullet reads 'Hypercholesterolemia (Against : Dihydrolipoyl transacetylase)' — the printed bracket names the E2 (dihydrolipoyl transacetylase) component that AMA targets; it is the antibody target, not a mechanism of hypercholesterolaemia."),
    ("match",
     "Match the printed frequencies in the PBC presentation list — 1) Hepatomegaly 2) Splenomegaly 3) Jaundice … A) <15% B) 10% C) 30–40%",
     ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A"],
     "Hepatomegaly (30–40%), Splenomegaly (<15%), Jaundice (10%)."),
    ("oddoneout",
     "Which of the following is NOT listed among the PBC presentation bullets on this page?",
     ["Kayser–Fleischer rings", "Xanthelasmas", "Hyperpigmentation", "Steatorrhea"],
     "The list: asymptomatic, fatigue, pruritus, jaundice, hypercholesterolemia, xanthelasmas, hyperpigmentation, hepatomegaly, splenomegaly, steatorrhea. K-F rings belong to Wilson's disease."),
    ("recall",
     "Steatorrhea in PBC is attributed on this page to which mechanism?",
     ["Decreased bile acid", "Pancreatic exocrine insufficiency", "Bacterial overgrowth from leaky gut", "Loss of intestinal lipase"],
     "'Steatorrhea (↓ Bile acid)'."),
    ("match",
     "The flowchart under steatorrhea lists three consequences of fat malabsorption and one downstream effect. Match — 1) Diarrhea 2) ↓ Fat soluble vitamin 3) ↓ Vitamin D absorption … A) leads to metabolic bone disease B) direct consequence of fat malabsorption (first arrow) C) direct consequence of fat malabsorption (second arrow)",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     "Fat malabsorption → Diarrhea; → ↓ Fat soluble vitamin; → ↓ Vitamin D absorption → metabolic bone disease."),
]

# ---------------------------------------------------------------- p1021
p1021 = [
    ("match",
     "Laboratory features of PBC — match the marker with its printed positivity — 1) AMA (Type IgM) 2) ANA … A) +ve in 50% B) +ve in 95%",
     ["1-B, 2-A", "1-A, 2-B", "1-B, 2-B", "1-A, 2-A"],
     "Laboratory features: Raised ALP; AMA (Type IgM) +ve in 95%; ANA +ve in 50%."),
    ("fillup",
     "Fill up: The first laboratory feature listed for PBC is raised ______, and the AMA is printed as being of the ______ isotype.",
     ["ALP; IgM", "ALT; IgG", "GGT; IgA", "bilirubin; IgG4"],
     "'Raised ALP.' and 'AMA (Type IgM) : +ve in 95%.'"),
    ("recall",
     "Which histopathological feature is labelled the EARLIEST change in PBC?",
     ["Loss of the canal of Hering", "Ductopenia", "Florid duct lesion with non-caseating granulomas", "Concentric periductal onion-skin fibrosis"],
     "Histopathology tree: 'Loss of the canal of Hering : Earliest'."),
    ("recall",
     "Which histopathological feature of PBC is labelled most common (m/c)?",
     ["Ductopenia", "Loss of the canal of Hering", "Florid duct lesion", "Bridging fibrosis"],
     "'Ductopenia (m/c)'."),
    ("truefalse",
     "Judge: I The most characteristic histological lesion of PBC is the florid duct lesion with granulomas. II These granulomas are caseating.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "'Florid duct lesion with granulomas (Non-caseating) (most characteristic)'."),
    ("match",
     "Match the PBC treatments with the printed descriptor — 1) Ursodeoxycholic acid (UDCA) 2) Obeticholic acid … A) Farnesoid receptor agonist B) ↓ progression of biliary cirrhosis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Treatment: UDCA : ↓ progression of biliary cirrhosis; Obeticholic acid : Farnesoid receptor agonist."),
    ("fillup",
     "Fill up (PSC definition): Primary Sclerosing Cholangitis is progressive ______ destruction of intra and extra hepatic bile duct, and is an ______ disease due to leaky gut.",
     ["fibrosing; IgG4", "granulomatous; IgM", "suppurative; IgA", "autoimmune T-cell; IgE"],
     "'Progressive fibrosing destruction of intra and extra hepatic bile duct. IgG4 disease d/t leaky gut.'"),
    ("numeric",
     "Prevalence of PSC: sex predilection and decade printed?",
     ["M > F; 2nd–3rd decade", "F > M 9:1; 4th–5th decade", "M > F; 4th–5th decade", "F > M; 2nd–3rd decade"],
     "'M > F (2nd – 3rd decade).'"),
    ("recall",
     "Which HLA associations are printed for PSC?",
     ["HLA B-8, DR-3", "HLA DR-4, DR-7", "HLA DR-3 only", "HLA B-27, DR-2"],
     "'HLA Association : HLA B-8, DR-3.'"),
    ("oddoneout",
     "Which item is NOT among the four PSC presentation bullets on this page?",
     ["Xanthelasma", "Fatigue", "Leaky gut", "Cholestasis"],
     "Presentation: Fatigue, Pruritis, Leaky gut, Cholestasis."),
    ("recall",
     "Which cancer is printed under 'Association with cancer' for PSC?",
     ["Cholangiocarcinoma", "Hepatocellular carcinoma", "Gallbladder carcinoma", "Pancreatic adenocarcinoma"],
     "'Association with cancer : Cholangiocarcinoma.' (Colorectal carcinoma appears separately under the UC association.)"),
    ("numeric",
     "Interpret the printed figures for the PSC–ulcerative colitis association: '(2/3rd / 5%)'.",
     ["2/3rd of PSC cases have UC; 5% of UC cases have PSC", "2/3rd of UC cases have PSC; 5% of PSC cases have UC", "2/3rd of PSC cases develop colorectal carcinoma; 5% die", "Both figures refer to the lifetime cholangiocarcinoma risk"],
     "'Ulcerative colitis (2/3rd / 5%) (2/3rd cases of PSC have UC & 5% cases of UC have PSC).'"),
    ("truefalse",
     "Regarding the UC that accompanies PSC, judge: I It is associated with atypical p-ANCA. II Its type is pancolitis with rectal sparing. III The only treatment is transplant.",
     ["I, II and III all true", "I and II true, III false", "I true, II and III false", "II true, I and III false"],
     "Sub-bullets under UC: Atypical P. ANCA association; Type: pancolitis with rectal sparing; A/w colorectal carcinoma; Only treatment: transplant."),
    ("fillup",
     "Fill up: The UC associated with PSC is 'A/w ______ carcinoma'.",
     ["colorectal", "cholangio", "hepatocellular", "gastric"],
     "'A/w colorectal carcinoma.'"),
    ("oddoneout",
     "Laboratory features of PSC — which of the following is printed as NEGATIVE?",
     ["AMA antibody", "IgG4 antibody", "Atypical p-ANCA antibody", "Both IgG4 and p-ANCA are printed negative"],
     "Laboratory features: IgG4 antibody; Atypical P. ANCA Ab; 'AMA Ab : −ve'."),
]

# ---------------------------------------------------------------- p1022
p1022 = [
    ("recall",
     "Which radiological investigation is marked the investigation of choice (IOC) for PSC?",
     ["MRCP", "ERCP", "Ultrasound", "CECT abdomen"],
     "'MRCP (IOC)' with ERCP listed beneath; both point to 'Strictures/Ectasia'."),
    ("fillup",
     "Fill up: Both MRCP and ERCP in PSC demonstrate ______ / ______ of the bile ducts (image caption).",
     ["Strictures / Ectasia", "Stones / Sludge", "Cavernoma / Collaterals", "Ductopenia / Granulomas"],
     "'→ Strictures/Ectasia' and the cholangiogram caption 'Strictures/Ectasia'."),
    ("recall",
     "What histological feature is printed for PSC (and labelled in the micrograph)?",
     ["Concentric periductal onion-skin fibrosis", "Florid duct lesion with non-caseating granuloma", "Interface hepatitis with rosettes", "Chicken-wire pericellular fibrosis"],
     "'Histological Features : Concentric periductal onion skin fibrosis.' Micrograph caption: 'Concentric periductal fibrosis'."),
    ("numeric",
     "Treatment of PSC on this page is surgery — what recurrence figure is printed?",
     ["25% recurrence", "5% recurrence", "50% recurrence", "10% recurrence"],
     "'Treatment : Surgery (25% recurrence).'"),
    ("match",
     "PBC vs PSC table, row 'Population incidence' — match — 1) PBC 2) PSC … A) Young male B) Perimenopausal females",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Population incidence: PBC = Perimenopausal females; PSC = Young male."),
    ("match",
     "Rows 'Disease type' and 'HLA association' — match — 1) PBC 2) PSC … A) Autoimmune disease; HLA association absent B) Fibrosing disease; HLA association present",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "Disease type: PBC autoimmune, PSC fibrosing. HLA association: PBC absent, PSC present (B-8, DR-3)."),
    ("truefalse",
     "Row 'Smoking' — judge: I Smoking increases the risk of PBC. II Smoking is protective in PSC.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Smoking: PBC = Increase risk; PSC = Protective."),
    ("match",
     "Rows 'Disease association' and 'Diagnostic feature' — match — 1) PBC 2) PSC … A) Sjogren's syndrome; AMA Ab B) Ulcerative colitis; MRCP",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "Disease association: PBC Sjogren's, PSC UC. Diagnostic feature: PBC AMA Ab, PSC MRCP (printed 'IOP' in the table, 'IOC' on the same page above)."),
    ("scenario",
     "A young man with ulcerative colitis has raised ALP; MRCP shows multifocal strictures and ectasia. Per the comparison table, what is the treatment listed for his condition?",
     ["Transplant", "UDCA", "Obeticholic acid", "Steroid 1 mg/kg with azathioprine"],
     "The picture is PSC. Table row 'Treatment': PBC = UDCA; PSC = Transplant."),
    ("truefalse",
     "Row 'Carcinoma association' — judge: I PBC is not premalignant. II PSC is associated with cholangiocarcinoma.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Carcinoma association: PBC = Not premalignant; PSC = A/w cholangiocarcinoma."),
    ("oddoneout",
     "Which of the following row pairings from the PBC vs PSC table is WRONGLY stated?",
     ["Smoking: PBC protective, PSC increases risk", "Population: PBC perimenopausal females, PSC young male", "Diagnostic feature: PBC AMA Ab, PSC MRCP", "Treatment: PBC UDCA, PSC transplant"],
     "The smoking row is reversed in this option: the book prints PBC = increase risk, PSC = protective. The other three pairings are correct."),
]

write_part(CH, "p1020a", 1020, "PBC: definition, AMA/PDHE2, hepatic vs cholestatic note, prevalence, associations, algorithm and presentation", p1020)
write_part(CH, "p1021a", 1021, "PBC laboratory, histopathology, treatment; PSC definition, prevalence, HLA, presentation, UC association, labs", p1021)
write_part(CH, "p1022a", 1022, "PSC radiology, histology, treatment; PBC vs PSC comparison table", p1022)

write_units(CH, [
    {"title": "PBC — definition, AMA/PDHE2, patterns, prevalence, associations, diagnostic algorithm and presentation",
     "sec": "PBC basics · p1020",
     "guide": "Cardinal intrahepatic cholestasis; autoimmune non-suppurative destruction of small intrahepatic/intralobular ducts, T-cell > B-cell; AMA 95% against PDHE2; hepatic (jaundice) vs cholestatic (fatigue & pruritus → duct destruction → jaundice, poor prognosis); F>M 9:1, 4th–5th decade; Sjogren with arthritis, distal RTA type 1, gallstones; ultrasound → AMA → PBC vs surgery; asymptomatic m/c presentation, fatigue m/c symptom, jaundice 10% late, hypercholesterolemia/xanthelasma, hyperpigmentation, hepatomegaly 30–40%, splenomegaly <15%, steatorrhea → fat malabsorption tree.",
     "parts": ["p1020a"]},
    {"title": "PBC labs, histology and treatment; PSC definition through laboratory features",
     "sec": "PBC labs/Rx · PSC part 1 · p1021",
     "guide": "Raised ALP, AMA IgM 95%, ANA 50%; canal of Hering loss earliest, ductopenia m/c, florid duct lesion with non-caseating granulomas most characteristic; UDCA slows progression, obeticholic acid = farnesoid receptor agonist. PSC: fibrosing destruction of intra+extra hepatic ducts, IgG4 disease d/t leaky gut; M>F 2nd–3rd decade; HLA B-8, DR-3; fatigue, pruritus, leaky gut, cholestasis; cholangiocarcinoma; UC 2/3rd vs 5%, atypical p-ANCA, pancolitis with rectal sparing, colorectal carcinoma, transplant only; IgG4, atypical p-ANCA, AMA negative.",
     "parts": ["p1021a"]},
    {"title": "PSC imaging, histology, treatment and the PBC vs PSC table",
     "sec": "PSC part 2 · comparison · p1022",
     "guide": "MRCP (IOC) / ERCP → strictures/ectasia; concentric periductal onion-skin fibrosis; surgery with 25% recurrence; table: perimenopausal female vs young male, autoimmune vs fibrosing, HLA absent vs present, smoking increases risk vs protective, Sjogren vs UC, AMA vs MRCP, UDCA vs transplant, not premalignant vs cholangiocarcinoma.",
     "parts": ["p1022a"]},
])
