#!/usr/bin/env python3
"""Ch 70 Hepatitis B Virus : Part 2 — Book p1039-1044, strict source order."""
from itemwriter_70_74 import write_part, write_units

CH = 70

# ---------------------------------------------------------------- p1039
p1039 = [
    ("fillup",
     "Fill up (Progression, Part 2): the printed chain runs Acute hepatitis → ______ → Cirrhosis, and cirrhosis ends in the two drawn end-points ______.",
     ["Chronic hepatitis; hepatocellular carcinoma and liver failure",
      "Chronic hepatitis; portal hypertension and variceal bleed",
      "Fulminant hepatitis; hepatocellular carcinoma and liver failure",
      "Chronic hepatitis; cholangiocarcinoma and portal vein thrombosis"],
     "'Acute Hepatitis → Chronic Hepatitis → Cirrhosis', with the cirrhosis box arrowed to 'HCC' and 'Liver failure'."),
    ("oddoneout",
     "In the p1039 progression diagram, cirrhosis arrows into two end-points. Which of these is NOT one of them?",
     ["Cholangiocarcinoma", "Hepatocellular carcinoma", "Liver failure", "HCC"],
     "Only 'HCC' and 'Liver failure' are drawn from the cirrhosis box."),
    ("truefalse",
     "Judge the Part-2 progression diagram: I Cirrhosis is drawn downstream of chronic hepatitis. II Recovery is drawn as an end-point of cirrhosis.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "Acute → chronic hepatitis → cirrhosis → HCC / liver failure; no recovery branch is drawn from cirrhosis."),
    ("oddoneout",
     "Under 'Transmission (Acute)' the page lists three routes. Which one is NOT among them?",
     ["Vertical (mother to child)", "Per-cutaneous", "Blood transfusion", "Sexual"],
     "The printed arms are Sexual, Per-cutaneous and Blood transfusion; vertical transmission is handled in its own block below."),
    ("recall",
     "How is vertical transmission described in this block?",
     ["Transmission : vertical (mother to child)", "Transmission : feco-oral (household contact)",
      "Transmission : breast milk to infant", "Transmission : airborne within the household"],
     "'Transmission : vertical (mother to child).'"),
    ("match",
     "Vertical transmission block — match — 1) HBeAg positive mother 2) HBeAg negative mother … A) 10% chances B) 90% chances",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Below HBeAg the block prints '90% chances' and '10% chances' for transmission to the child."),
    ("fillup",
     "Fill up: 'Time of development : ______ trimester (______)'.",
     ["3rd; maximum", "1st; maximum", "2nd; minimum", "3rd; minimum"],
     "'Time of development : 3rd trimester (maximum)'."),
    ("numeric",
     "At what gestation does the pregnancy block advise the check-up?",
     ["28 – 30 weeks", "24 – 28 weeks", "32 – 34 weeks", "12 – 16 weeks"],
     "'Treatment in Pregnancy : At 28 - 30 week → check-up'."),
    ("scenario",
     "Antenatal HBV DNA comes back above the printed cut-off. What is the next printed step and the threshold used?",
     ["Start treatment once HBV DNA exceeds 20,000",
      "Start treatment only after delivery, whatever the HBV DNA",
      "Start treatment once HBV DNA exceeds 2,000",
      "Give HBIG to the mother immediately, whatever the HBV DNA"],
     "'check-up → HBV DNA → > 20,000 → Start treatment'."),
    ("truefalse",
     "Judge the pregnancy block: I The antenatal check-up with HBV DNA is timed at 28–30 weeks. II Treatment is started when HBV DNA crosses 20,000.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both statements reproduce the printed block: check-up at 28–30 weeks, and 'Start treatment' after HBV DNA > 20,000."),
    ("fillup",
     "Fill up (Child after birth): immunoglobulin — HBIg (______ ml); vaccine — ______, with the first dose within ______ hours.",
     ["0.5; 0, 1, 6; 12", "0.06; 0, 1, 2; 24", "1.0; 0, 1, 6; 24", "0.5; 0, 1, 2, 6; 24"],
     "'Child After birth : Immunoglobulin : HBIg (0.5 ml). Vaccine : 0,1,6 / 0,1,6 (1st dose within 12 hours)'."),
    ("numeric",
     "Post-exposure prophylaxis after a needlestick from an HBV-positive patient — what risk figure is printed?",
     ["6 – 30% chances", "0.6 – 6.1% chances", "90% chances", "1 : 200,000 units"],
     "'Needle prick : HBV +ve patient (6-30% chances) → Check for Anti HBs levels'."),
    ("match",
     "Needlestick algorithm — match the anti-HBs level to the printed action — 1) > 100 2) 10 – 100 … A) 1 booster to be given B) No need for Ig / vaccine",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'> 100 : No need for Ig/vaccine'; '10-100 : 1 booster to be given'."),
    ("recall",
     "After a needlestick from an HBV-positive source, what is the investigation the page asks for before deciding on prophylaxis?",
     ["Check for anti-HBs levels", "Check HBeAg in the source",
      "Check anti-HBc IgM in the recipient", "Check HBV genotype"],
     "'Check for Anti HBs levels' is the branch point of the algorithm."),
    ("fillup",
     "Fill up (Sexual-contact exposure): HBIG ______ mL/kg given within ______ days.",
     ["0.06; 14", "0.06; 24 hours", "0.5; 14", "0.5; 7"],
     "'Sexual contact : HBIg : 0.06 mL/kg within 14 days'."),
    ("fillup",
     "Fill up (Percutaneous / transmucosal exposure): HBIG ______ mL/kg given within ______ hours.",
     ["0.06; 24", "0.06; 14 days", "0.5; 24", "0.6; 72"],
     "'Percutaneous/transmucosal : HBIg : 0.06 ml/kg within 24 hours'."),
    ("truefalse",
     "Compare the two post-exposure columns: I Sexual contact allows HBIG up to 14 days. II Percutaneous/transmucosal exposure allows HBIG only up to 24 hours.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Sexual contact: 'within 14 days'; percutaneous/transmucosal: 'within 24 hours'."),
    ("match",
     "Post-exposure vaccination — match — 1) Sexual contact 2) Percutaneous/transmucosal … A) Vaccine 0,1,6 months, 1st dose within 1 week B) Vaccine 0,1,6 months, 1st dose within 1 week — identical in both",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "Both columns print 'Vaccine : 0,1,6 / 0,1,6 months' and '1st dose within 1 week'."),
    ("match",
     "Vaccine prophylaxis — match — 1) General population 2) In CKD patient … A) Schedule 0,1,2,6 months; 40 μg / 1 ml; both deltoid (double dose) B) Schedule 0,1,6 months; 20 μg / 0.5 ml; deltoid",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "General population: 0,1,6 months, 20 μg / 0.5 ml, deltoid. CKD: 0,1,2,6 months, 40 μg / 1 ml, both deltoid (double dose)."),
    ("recall",
     "What route is printed for hepatitis B vaccine prophylaxis in both the general population and the CKD patient?",
     ["Intramuscular", "Intradermal", "Subcutaneous", "Oral"],
     "'Route : im' in both columns."),
    ("oddoneout",
     "Which of these is NOT printed for the CKD vaccination schedule?",
     ["Single deltoid, standard dose", "Schedule 0,1,2,6 months",
      "40 μg / 1 ml", "Both deltoid (double dose)"],
     "The CKD column prints 0,1,2,6 months, 40 μg / 1 ml and 'Both Deltoid (double dose)'."),
]

# ---------------------------------------------------------------- p1040
p1040 = [
    ("oddoneout",
     "The p1040 phase table is built on marker rows. Which is NOT one of the printed row labels?",
     ["Anti-HBs", "HBeAg", "Anti-HBe", "HBV DNA"],
     "Printed row labels are HBeAg, Anti-HBe, HBV DNA (and ALT); anti-HBs is not a row label here."),
    ("match",
     "Match the phase to the immune state printed under it — 1) Phase I 2) Phase II … A) Immune clearance B) Immune tolerant",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Phase I is labelled 'Immune tolerant', Phase II 'Immune clearance'."),
    ("fillup",
     "Fill up: Phase I is 'HBeAg positive ______ infection', lasting ______ years.",
     ["chronic; 10 – 30", "chronic hepatitis; 10 – 30", "acute; 1 – 5", "chronic; 30 – 40"],
     "'Phase I / HBeAg Positive chronic infection : · 10 - 30 years'."),
    ("truefalse",
     "Judge Phase I: I HBsAg and HBeAg are both positive with HBV DNA markedly raised. II ALT is normal, so the page concludes no treatment.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Phase I prints 'HBsAg +ve', 'HBeAg +ve', 'HBV DNA ↑↑' and 'ALT : Normal → No [treatment]'."),
    ("recall",
     "Which phase is captioned the 'optimal treatment time'?",
     ["Phase II (HBeAg positive chronic hepatitis)", "Phase I (HBeAg positive chronic infection)",
      "Phase III (HBeAg negative chronic infection)", "Phase V (HBsAg negative)"],
     "Phase II carries 'Optimal treatment time'."),
    ("match",
     "Match the phase to its descriptor — 1) Phase II 2) Phase III … A) Inactive carrier state B) Mildly symptomatic chronic hepatitis with ALT ↑↑",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Phase II: 'chronic hepatitis : · mildly Symptomatic … ALT ↑ ↑'. Phase III: 'Inactive carrier state'."),
    ("recall",
     "Phase III (HBeAg-negative chronic infection) is qualified by which population note?",
     ["Majority population", "Minority population", "Only children", "Only dialysis patients"],
     "'Phase III / HBeAg Negative chronic infection : · majority population'."),
    ("fillup",
     "Fill up: in Phase III, HBeAg is ______ and HBV DNA is at its ______.",
     ["negative; lowest", "positive; highest", "negative; highest", "positive; lowest"],
     "'HBeAg - Normal' with 'HBV DNA : lowest'."),
    ("scenario",
     "An HBeAg-negative patient presents like acute hepatitis — fever, malaise, vomiting, raised serum bilirubin and raised liver enzymes. Which phase does the page label this as?",
     ["Phase IV — HBeAg negative chronic hepatitis", "Phase I — HBeAg positive chronic infection",
      "Phase III — inactive carrier state", "Acute hepatitis A"],
     "Phase IV is 'HBeAg Negative chronic hepatitis' with 'Presentation — Acute symptoms : Fever, malaise, Vomiting' and 'Laboratory features : ↑ s. bilirubin, ↑ liver enzyme'."),
    ("match",
     "Phase IV presentation — match — 1) Symptoms 2) Laboratory … A) ↑ s. bilirubin, ↑ liver enzyme B) Fever, malaise, vomiting",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Presentation — Acute symptoms : Fever, malaise, Vomiting'; 'Laboratory features : ↑ s. bilirubin, ↑ liver enzyme'."),
    ("recall",
     "What is printed for Phase V (HBsAg negative)?",
     ["Chronic infection with no inflammation and minimal fibrosis",
      "Chronic hepatitis with severe inflammation and cirrhosis",
      "Acute infection with anti-HBc IgM",
      "Inactive carrier state with high HBV DNA"],
     "'Phase V / HBsAg negative : chronic infection : · No inflammation · minimal fibrosis'."),
    ("oddoneout",
     "Which finding is NOT printed under Phase V (HBsAg negative)?",
     ["Bridging fibrosis", "No inflammation", "Minimal fibrosis", "Chronic infection"],
     "Phase V prints 'chronic infection', 'No inflammation' and 'minimal fibrosis' only."),
    ("scenario",
     "A patient looks like acute hepatitis B, but you suspect it is really chronic hepatitis phase IV. Which test does the page print to settle it?",
     ["Anti-HBc IgM", "Quantitative HBsAg", "Anti-HBs titre", "HBV genotype"],
     "The left block prints 'Acute hepatitis B — Anti HBc IgM +ve'."),
    ("numeric",
     "In the 'Chronic hepatitis phase IV' block, what quantitative HBsAg cut-off is printed for confirmation?",
     ["> 1000 IU/mL", "> 100 IU/mL", "> 10,000 IU/mL", "> 20,000 IU/mL"],
     "'For confirmation : · quantitative HBs Ag ( > 1000 IU/mL)'."),
    ("oddoneout",
     "Which is NOT one of the three items printed under 'For confirmation' in the chronic hepatitis phase IV block?",
     ["Anti-HBc IgM positive", "Quantitative HBsAg > 1000 IU/mL",
      "Severely symptomatic", "Very high HBV DNA load"],
     "The block lists quantitative HBsAg > 1000 IU/mL, 'Severely Symptomatic' and 'Very high HBV DNA load'; anti-HBc IgM belongs to the acute hepatitis B block."),
    ("truefalse",
     "Judge the two bottom blocks: I Acute hepatitis B is confirmed by anti-HBc IgM positivity. II Chronic hepatitis phase IV is confirmed by quantitative HBsAg above 1000 IU/mL.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Left block: 'Acute hepatitis B — Anti HBc IgM +ve'. Right block: 'Chronic hepatitis phase IV : For confirmation : · quantitative HBs Ag ( > 1000 IU/mL)'."),
]

write_part(CH, "p1039a", 1039,
           "Progression, vertical transmission, treatment in pregnancy, newborn care, post-exposure prophylaxis, vaccine prophylaxis", p1039)
write_part(CH, "p1040a", 1040,
           "Phases of chronic HBV: table rows, phase I-V, acute HBV vs chronic hepatitis phase IV", p1040)


# ---------------------------------------------------------------- p1041
p1041 = [
    ("fillup",
     "Fill up (Seroconversion): 'Both markers should be checked before ______ therapy.'",
     ["immunosuppressive", "antiretroviral", "antifungal", "antihypertensive"],
     "'Seroconversion : Both markers should be checked before immunosuppressive therapy.'"),
    ("match",
     "Match the two markers the page asks for — 1) First marker 2) Second marker … A) Anti-HBc IgG B) HBsAg",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "The pair printed before immunosuppressive therapy is HBsAg and anti-HBc IgG."),
    ("scenario",
     "Before immunosuppression, screening shows HBsAg negative but anti-HBc IgG positive. What does this page warn about?",
     ["Reactivation during immunosuppressive therapy",
      "No risk at all, because HBsAg is negative",
      "Acute hepatitis B that needs vaccination",
      "Immediate need for liver transplantation"],
     "HBsAg -ve with anti-HBc IgG +ve is the pattern arrowed to 'Immunosuppressive therapy → Reactivation'."),
    ("truefalse",
     "Judge the seroconversion block: I HBsAg negative with anti-HBc IgG negative is the pattern with no reactivation risk. II HBsAg negative with anti-HBc IgG positive is the carrier pattern that reactivates on immunosuppression.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Two patterns are contrasted: both markers negative, versus HBsAg -ve with anti-HBc IgG +ve, the latter running into reactivation."),
    ("match",
     "Clinical features — match — 1) Acute hepatitis column 2) Chronic hepatitis column … A) Asymptomatic presentation, fatigue (most common symptom), fever, extrahepatic manifestations B) Acute hepatitis B, reactivation",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Clinical Features' splits into Acute hepatitis (Acute hepatitis B, Reactivation) and Chronic hepatitis (Asymptomatic presentation, Fatigue — most common symptom, Fever, Extrahepatic manifestation)."),
    ("recall",
     "Which symptom does the page print as the most common symptom of chronic hepatitis B?",
     ["Fatigue", "Fever", "Arthralgia", "Jaundice"],
     "'Fatigue (most common symptom)'."),
    ("oddoneout",
     "Which is NOT one of the rare extrahepatic manifestations listed for chronic hepatitis B?",
     ["Kayser-Fleischer rings", "Membranous nephropathy", "Polyarteritis nodosa (30%)", "Arthralgia"],
     "'Extrahepatic manifestation (Rare) : membranous nephropathy, Polyarteritis Nodosa (30%), Arthralgia'."),
    ("numeric",
     "What figure is printed alongside polyarteritis nodosa in the extrahepatic list?",
     ["30%", "3%", "13%", "60%"],
     "'Polyarteritis Nodosa (30%)'."),
    ("recall",
     "Which investigation is printed next to 'Cirrhosis' in the work-up line?",
     ["Fibroscan", "Liver biopsy", "MRCP", "CT abdomen"],
     "'· Cirrhosis : Fibroscan'."),
    ("recall",
     "The 'Replicative load' section is divided into which two branches?",
     ["Low replicative and high replicative", "Replicative and non-replicative",
      "Infective and non-infective", "Compensated and decompensated"],
     "Two branches are drawn under 'Replicative load': 'Low Replicative' and 'High Replicative'."),
    ("match",
     "Replicative profiles — match — 1) HBV DNA > 20,000 IU/mL 2) HBV DNA > 2,000 IU/mL … A) HBeAg -ve (precore mutation) B) HBeAg +ve",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'HBeAg +ve : · HBV DNA > 20,000 IU/mL'; 'HBeAg -ve (Precore mutation) : · HBV DNA > 2,000 IU/mL'."),
    ("match",
     "Match the profile to its printed consequences — 1) HBeAg +ve profile 2) HBeAg -ve precore-mutant profile … A) Anti-HBc reactive, progressive liver injury, bad prognosis B) High infectivity, risk of liver injury",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "HBeAg +ve profile: 'High infectivity · Risk of liver injury'. Precore-mutant profile: '· Anti-HBc reactive · Progressive liver injury · Bad prognosis'."),
    ("scenario",
     "A patient with chronic HBV is HBeAg negative with HBV DNA 3,000 IU/mL. Which printed profile and consequence set applies?",
     ["HBeAg -ve precore mutation — anti-HBc reactive, progressive liver injury, bad prognosis",
      "HBeAg +ve — high infectivity, risk of liver injury",
      "Inactive carrier — no treatment and no follow-up",
      "Acute hepatitis B — anti-HBc IgM positive"],
     "HBeAg -ve with DNA above 2,000 fits the 'HBeAg -ve (Precore mutation)' profile with progressive liver injury and bad prognosis."),
    ("oddoneout",
     "Which statement is NOT printed for the HBeAg-negative precore-mutant profile?",
     ["High infectivity", "Anti-HBc reactive", "Progressive liver injury", "Bad prognosis"],
     "'High infectivity' belongs to the HBeAg-positive profile; the precore-mutant profile lists anti-HBc reactive, progressive liver injury and bad prognosis."),
]

# ---------------------------------------------------------------- p1042
p1042 = [
    ("fillup",
     "Fill up (Life cycle): the sub genomic mRNA is translated to give the ______ protein / ______ antigen, which is labelled carcinogenic.",
     ["x; HBxAg", "s; HBsAg", "c; HBcAg", "e; HBeAg"],
     "'① Sub genomic mRNA → Translation → x-Protein → HbxAg (Carcinogenic)'."),
    ("match",
     "Life cycle — match — 1) Pre genomic mRNA 2) DNA … A) DNA dependent DNA polymerase B) RNA dependent DNA polymerase (reverse transcriptase)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'(a) Pre genomic mRNA' leads to 'RNA dependent DNA polymerase (Reverse transcriptase)' → DNA, then 'DNA dependent DNA polymerase'."),
    ("truefalse",
     "Judge the life-cycle diagram: I The pre-genomic RNA step needs the viral RNA-dependent DNA polymerase (reverse transcriptase). II The host enzyme is shown acting on the sub-genomic mRNA branch.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'+ Host enzyme' is drawn on the sub-genomic (x-protein) branch; the pre-genomic branch runs through reverse transcriptase."),
    ("recall",
     "Which receptor is printed for entry of the Dane particle into the hepatocyte?",
     ["Na-taurocholate co-transporting polypeptide (NTCP)", "NTCP-independent bile acid transporter",
      "ASGPR (asialoglycoprotein receptor)", "Transferrin receptor"],
     "'Virion / Dane particle : Na-taurocholate receptor' (NTCP)."),
    ("fillup",
     "Fill up: the nuclear form printed in the life cycle is ______ (cccDNA), and its strands are labelled ______.",
     ["covalently closed circular DNA; +/-", "relaxed circular DNA; -/-",
      "single stranded DNA; + only", "linear double stranded DNA; +/+"],
     "'Covalent closed circular DNA (cccDNA)' and 'Strands +/-'."),
    ("truefalse",
     "Judge the printed note: I Integration of HBV cccDNA with the host genome makes eradication impossible. II It confers a risk of malignancy.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Note : HBV cccDNA integration with host genome makes it impossible to eradicate. Confers risk of malignancy.'"),
    ("recall",
     "Which viral product is specifically flagged as carcinogenic in the life-cycle diagram?",
     ["HBxAg", "HBsAg", "HBcAg", "HBeAg"],
     "'x-Protein → HbxAg (Carcinogenic)'."),
    ("numeric",
     "Indication of treatment in acute hepatitis B — the bilirubin criterion as printed?",
     ["S. bilirubin > 3 mg/dl for 4 weeks", "S. bilirubin > 1.5 mg/dl for 2 weeks",
      "S. bilirubin > 5 mg/dl for 1 week", "S. bilirubin > 10 mg/dl at any time"],
     "'Acute hepatitis : Indication of treatment : · S. Bilirubin > 3 mg/dl for 4 weeks'."),
    ("numeric",
     "The second treatment indication printed for acute hepatitis B?",
     ["INR ≥ 1.5", "INR ≥ 1.2", "INR ≤ 1.5", "PT prolongation > 3 seconds"],
     "'INR ≥ 1.5' is the second indication listed."),
    ("truefalse",
     "Judge the treatment indications for acute hepatitis B: I Serum bilirubin above 3 mg/dl persisting for 4 weeks. II INR of 1.5 or more.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both are printed under 'Acute hepatitis : Indication of treatment'."),
    ("match",
     "Histology captions — match — 1) H&E 2) Immunohistochemistry … A) Immunohistochemical stain for HBsAg showing brownish inclusion B) Hepatocytes with ground glass inclusions",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Hepatocytes with ground glass inclusions' and 'Immunohistochemical stain for HBsAg showing brownish inclusion'."),
    ("recall",
     "Which stain is used to demonstrate the ground-glass hepatocytes of HBV on this page?",
     ["Immunohistochemical stain for HBsAg", "Periodic acid-Schiff",
      "Prussian blue", "Reticulin"],
     "The paired caption reads 'Immunohistochemical stain for HBsAg showing brownish inclusion'."),
]

# ---------------------------------------------------------------- p1043
p1043 = [
    ("match",
     "Treatment tree — match the cirrhosis status to the printed step — 1) Cirrhosis -ve, low infectivity 2) Cirrhosis +ve, compensated 3) Cirrhosis +ve, decompensated … A) Treatment B) Treatment / transplant C) Follow up",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "'Low infectivity → Follow up'; 'Cirrhosis → Treatment'; 'Decompensated Cirrhosis → Treatment / transplant'."),
    ("numeric",
     "Treatment threshold printed for the HBeAg-positive chronic hepatitis branch?",
     ["HBV DNA > 20,000 IU/mL and ALT > 2 times the upper limit of normal",
      "HBV DNA > 2,000 IU/mL and ALT > 2 times the upper limit of normal",
      "HBV DNA > 20,000 IU/mL with normal ALT",
      "Any detectable HBV DNA with ALT > 5 times the upper limit"],
     "'HBeAg +ve : HBV DNA > 20,000 IU/mL; ALT > 2 times of upper limit'."),
    ("numeric",
     "Treatment threshold printed for the HBeAg-negative branch?",
     ["HBV DNA > 2,000 IU/mL and ALT > 2 times the upper limit of normal",
      "HBV DNA > 20,000 IU/mL and ALT > 2 times the upper limit of normal",
      "HBV DNA > 200 IU/mL and ALT > 5 times the upper limit",
      "HBV DNA undetectable with ALT > 2 times the upper limit"],
     "'HBeAg -ve : HBV DNA > 2,000 IU/mL; ALT > 2 times of upper limit'."),
    ("truefalse",
     "Judge the treatment branches: I The HBV DNA threshold for treatment is ten times higher in the HBeAg-positive than in the HBeAg-negative branch. II The ALT criterion is the same in both.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "20,000 vs 2,000 IU/mL, with 'ALT > 2 times of upper limit' in both branches."),
    ("match",
     "Targets of treatment — match — 1) HBeAg positive 2) HBeAg negative … A) Seroconversion B) ALT normal and suppression of HBV DNA",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "'Target of treatment : HBeAg -ve : Seroconversion · ALT normal · Suppress HBV DNA' as printed."),
    ("fillup",
     "Fill up: the two printed aims listed under 'Target of treatment' are ______ and ______.",
     ["ALT normal; suppress HBV DNA", "HBsAg loss; anti-HBs seroconversion",
      "ALT twice normal; detectable HBV DNA", "HBeAg loss; stop all drugs"],
     "'· ALT normal · Suppress HBV DNA'."),
    ("match",
     "Available therapies — match — 1) IFN-α 2) Lamivudine 3) Tenofovir disoproxil 4) Tenofovir alafenamide … A) 300 mg OD, A/e proximal RTA and bone mineral disease B) S/c, about 30% seroconversion, psychosis / autoimmune thyroiditis / marrow suppression C) DOC, latest, 25 mg OD, fewer side effects D) good initial response but YMDD mutation and resistance",
     ["1-B, 2-D, 3-A, 4-C", "1-D, 2-A, 3-C, 4-B", "1-B, 2-A, 3-D, 4-C", "1-C, 2-D, 3-A, 4-B"],
     "IFN-α: S/c, '30% Seroconversion', psychosis, autoimmune thyroiditis, bone marrow suppression. Lamivudine: 'Initially good response', 'YMDD mutation → Resistance, Nephrotoxic'. Tenofovir disoproxil: '300 mg OD Daily', 'A/e : RTA Type 2 (Proximal PCT toxicity), Bone mineral disease'. Tenofovir alafenamide: 'DOC', 'Latest', '25 mg OD Daily', 'Less side effect compared to Tenofovir disoproxil'."),
    ("fillup",
     "Fill up (Interferon): given ______, it achieves about ______ seroconversion.",
     ["S/c; 30%", "i/m; 3%", " orally; 60%", "S/c; 80%"],
     "'IFN-α : S/c · 30% Seroconversion'."),
    ("oddoneout",
     "Which is NOT a printed limitation of interferon therapy in chronic hepatitis B?",
     ["Nephrotoxicity", "No role in HBeAg-negative patients",
      "No role in cirrhosis", "No role in young Asians"],
     "'Limitation : No role in HBeAg -ve patient · No role in cirrhosis · No role in young asian'; nephrotoxicity is listed under lamivudine."),
    ("oddoneout",
     "Which is NOT a printed adverse effect of interferon in this list?",
     ["Proximal renal tubular acidosis", "Psychosis", "Autoimmune thyroiditis", "Bone marrow suppression"],
     "'A/e : Psychosis · Autoimmune thyroiditis · Bone marrow suppression'. Proximal RTA is a tenofovir disoproxil adverse effect."),
    ("recall",
     "What is the resistance mechanism printed against lamivudine?",
     ["YMDD mutation → resistance", "rtA181T mutation → resistance",
      "Precore mutation → resistance", "S-gene escape mutant → resistance"],
     "'YMDD mutation → Resistance'."),
    ("recall",
     "What verdict does the page give for lamivudine plus adefovir combination?",
     ["No significant benefit", "DOC for cirrhosis", "Preferred first line", "Only useful in HBeAg-negative disease"],
     "Against 'Lamivudine + Adefovir' the page prints '· No significant benefit'."),
    ("numeric",
     "Dose printed for tenofovir disoproxil fumarate?",
     ["300 mg once daily", "25 mg once daily", "0.5 mg once daily", "100 mg twice daily"],
     "'Tenofovir Disoproxil : 300 mg OD Daily'."),
    ("numeric",
     "Dose printed for entecavir?",
     ["0.5 mg once daily", "1 mg once daily", "0.5 mg twice daily", "5 mg once daily"],
     "'Entecavir : 0.5 mg OD Daily'."),
    ("numeric",
     "Dose printed for tenofovir alafenamide?",
     ["25 mg once daily", "300 mg once daily", "0.5 mg once daily", "245 mg once daily"],
     "'Tenofovir Alafenamide : · DOC · Latest · 25 mg OD Daily'."),
    ("match",
     "Adverse effects — match — 1) Tenofovir disoproxil 2) Tenofovir alafenamide … A) Fewer side effects than tenofovir disoproxil B) RTA type 2 (proximal PCT toxicity) and bone mineral disease",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Disoproxil: 'A/e : RTA Type 2 (Proximal PCT toxicity) · Bone mineral disease'. Alafenamide: 'Less side effect compared to Tenofovir disoproxil'."),
    ("recall",
     "Which drug does the page call the drug of choice and the latest agent?",
     ["Tenofovir alafenamide", "Tenofovir disoproxil", "Entecavir", "Lamivudine"],
     "'Tenofovir Alafenamide : · DOC · Latest'."),
    ("scenario",
     "A cirrhotic patient with chronic hepatitis B needs treatment. Which drug is specifically recorded as having no role in cirrhosis?",
     ["Interferon-α", "Entecavir",
      "Tenofovir alafenamide", "Tenofovir disoproxil"],
     "'Limitation : … · No role in cirrhosis' is printed under IFN-α."),
]

# ---------------------------------------------------------------- p1044
p1044 = [
    ("fillup",
     "Fill up: 'Hepatitis D Virus — Delta virus, ______'.",
     ["RNA", "DNA", "a defective DNA virus", "a prion"],
     "'Hepatitis D Virus : Delta virus, RNA'."),
    ("match",
     "HDV — match — 1) Coinfection 2) Superinfection … A) Chronic HBV + acute hepatitis D (acute on chronic) B) Acute HBV infection + acute HDV infection",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Coinfection : Acute HBV infection + Acute HDV infection'; 'Superinfection (Acute on chronic) : Chronic HBV + Acute Hepatitis D'."),
    ("match",
     "Antibody patterns — match — 1) Coinfection 2) Superinfection … A) HBsAg +ve with anti-HDV IgM B) Anti-HBc IgM +ve with anti-HDV IgM +ve",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Coinfection prints 'Anti HBc IgM +ve' and 'Anti HDV IgM +ve'; superinfection prints 'HBsAg +ve' and 'Anti HDV IgM'."),
    ("numeric",
     "Risk of fulminant hepatitis printed in the coinfection column?",
     ["5 – 20%", "1 – 2%", "30 – 40%", "60 – 70%"],
     "'Other features : Chances of fulminant hepatitis 5-20%'."),
    ("recall",
     "What long-term outcome is printed down the superinfection column?",
     ["Chronic HDV-related cirrhosis", "Complete recovery in most cases",
      "Hepatocellular carcinoma within a year", "Inactive carrier state"],
     "'Chronic HDV related cirrhosis' is the end-point of the superinfection column."),
    ("recall",
     "Which autoantibody is printed in the hepatitis D page?",
     ["Anti-LKM-3 antibody", "Anti-LKM-1 antibody",
      "Anti-smooth muscle antibody", "Anti-mitochondrial antibody"],
     "'Anti LKM-3 Antibody' appears against the delta agent and again in the superinfection column."),
    ("truefalse",
     "Judge the hepatitis D table: I Coinfection is acute HBV plus acute HDV with anti-HBc IgM positive. II Superinfection is acute HDV on chronic HBV and carries a bad prognosis with chronic HDV cirrhosis.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Coinfection = both infections acute with anti-HBc IgM +ve; superinfection = acute on chronic, '(Bad prognosis)' → 'Chronic HDV related cirrhosis'."),
    ("recall",
     "The closing note on this page flags a high risk of fulminant hepatic failure for which virus in pregnancy?",
     ["HEV", "HBV", "HDV", "HAV"],
     "'Note : HEV in pregnancy also has a high risk of fulminant hepatic failure.'"),
    ("scenario",
     "A patient with known chronic hepatitis B suddenly deteriorates with jaundice and tests anti-HDV IgM positive. Which pattern and prognosis does the page print?",
     ["Superinfection — bad prognosis with chronic HDV-related cirrhosis",
      "Coinfection — anti-HBc IgM positive with 5-20% fulminant risk",
      "Resolved HDV with anti-HDV IgG only",
      "HAV superinfection with no chronic sequelae"],
     "Chronic HBV + acute hepatitis D is superinfection (acute on chronic), which the page labels '(Bad prognosis)' → 'Chronic HDV related cirrhosis'."),
    ("oddoneout",
     "Which is NOT printed in the superinfection column?",
     ["Anti-HBc IgM positive", "HBsAg positive",
      "Anti-HDV IgM", "Chronic HDV-related cirrhosis"],
     "Anti-HBc IgM positivity is printed in the coinfection column, not the superinfection column."),
]

write_part(CH, "p1041a", 1041,
           "Seroconversion before immunosuppression, clinical features, extrahepatic disease, replicative load", p1041)
write_part(CH, "p1042a", 1042,
           "Life cycle of HBV, cccDNA note, acute hepatitis treatment indications, histology", p1042)
write_part(CH, "p1043a", 1043,
           "Chronic hepatitis treatment tree, thresholds, targets, available therapies and doses", p1043)
write_part(CH, "p1044a", 1044,
           "Hepatitis D virus: coinfection vs superinfection, antibodies, prognosis, HEV-in-pregnancy note", p1044)

write_units(CH, [
    {"title": "Vertical transmission, pregnancy, newborn and prophylaxis",
     "sec": "Prevention & prophylaxis · p1039",
     "guide": "Acute→chronic hepatitis→cirrhosis→HCC/liver failure; acute transmission = sexual, per-cutaneous, blood transfusion; vertical (mother to child) with 90% vs 10% chances by HBeAg, developing maximally in the 3rd trimester; antenatal check-up at 28–30 weeks, HBV DNA > 20,000 → start treatment; child after birth: HBIg 0.5 ml + vaccine 0,1,6 with 1st dose within 12 hours; needlestick 6–30% → check anti-HBs (>100 none, 10–100 one booster); sexual contact HBIG 0.06 mL/kg within 14 days; percutaneous/transmucosal HBIG 0.06 mL/kg within 24 hours; vaccine 0,1,6, 1st dose within 1 week; general population 0,1,6 months, 20 μg/0.5 ml, deltoid; CKD 0,1,2,6 months, 40 μg/1 ml, both deltoid double dose.",
     "parts": ["p1039a"]},
    {"title": "Phases of chronic hepatitis B",
     "sec": "Phases I–V · p1040",
     "guide": "Table rows HBeAg, anti-HBe, HBV DNA, ALT; Phase I HBeAg+ chronic infection, immune tolerant, 10–30 years, HBsAg+, HBeAg+, HBV DNA ↑↑, ALT normal → no treatment; Phase II HBeAg+ chronic hepatitis, immune clearance, mildly symptomatic, ALT ↑↑, optimal treatment time; Phase III HBeAg− chronic infection, inactive carrier state, majority population, HBeAg−, HBV DNA lowest; Phase IV HBeAg− chronic hepatitis, inflammation, acute symptoms (fever, malaise, vomiting), ↑ s. bilirubin and liver enzymes; Phase V HBsAg negative chronic infection, no inflammation, minimal fibrosis; acute HBV = anti-HBc IgM +ve vs chronic phase IV confirmed by quantitative HBsAg > 1000 IU/mL, severely symptomatic, very high HBV DNA load.",
     "parts": ["p1040a"]},
    {"title": "Reactivation risk, clinical features and replicative load",
     "sec": "Clinical · p1041",
     "guide": "Both markers (HBsAg and anti-HBc IgG) checked before immunosuppressive therapy; HBsAg -ve with anti-HBc IgG +ve reactivates; clinical features split into acute (acute hepatitis B, reactivation) and chronic (asymptomatic presentation, fatigue = most common symptom, fever, rare extrahepatic disease: membranous nephropathy, PAN 30%, arthralgia); cirrhosis assessed with fibroscan; replicative load split into low and high replicative branches, HBeAg +ve with HBV DNA > 20,000 IU/mL (high infectivity, risk of liver injury) and HBeAg -ve precore mutant with HBV DNA > 2,000 IU/mL (anti-HBc reactive, progressive liver injury, bad prognosis).",
     "parts": ["p1041a"]},
    {"title": "Life cycle, acute hepatitis treatment indications and histology",
     "sec": "Virology & acute treatment · p1042",
     "guide": "Sub-genomic mRNA → translation → x-protein → HBxAg (carcinogenic) with host enzyme; pre-genomic mRNA → RNA-dependent DNA polymerase (reverse transcriptase) → DNA → DNA-dependent DNA polymerase → +/- strands → virion/Dane particle; entry via Na-taurocholate (NTCP) receptor; cccDNA forms in the nucleus; note that cccDNA integration with the host genome makes eradication impossible and confers malignancy risk; acute hepatitis treatment indications: S. bilirubin > 3 mg/dl for 4 weeks and INR ≥ 1.5; histology: ground-glass hepatocytes and HBsAg immunohistochemistry with brownish inclusions.",
     "parts": ["p1042a"]},
    {"title": "Treatment of chronic hepatitis B: thresholds, targets and drugs",
     "sec": "Therapy · p1043",
     "guide": "Cirrhosis -ve: low infectivity → follow up, otherwise consider treatment; cirrhosis +ve: treatment, decompensated → treatment/transplant; thresholds: HBeAg +ve HBV DNA > 20,000 IU/mL with ALT > 2× ULN, HBeAg -ve HBV DNA > 2,000 IU/mL with ALT > 2× ULN; targets: (HBeAg -ve) seroconversion, ALT normal, suppress HBV DNA; drugs: IFN-α S/c ~30% seroconversion with psychosis, autoimmune thyroiditis, marrow suppression and no role in HBeAg -ve disease, cirrhosis or young Asians; lamivudine good initial response but YMDD mutation resistance and nephrotoxicity; lamivudine + adefovir no significant benefit; tenofovir disoproxil 300 mg OD with proximal RTA and bone mineral disease; entecavir 0.5 mg OD; tenofovir alafenamide DOC and latest, 25 mg OD, fewer side effects.",
     "parts": ["p1043a"]},
    {"title": "Hepatitis D virus",
     "sec": "HDV · p1044",
     "guide": "Delta virus, RNA, with anti-LKM-3 antibody; coinfection = acute HBV + acute HDV, anti-HBc IgM and anti-HDV IgM positive, 5-20% chance of fulminant hepatitis; superinfection (acute on chronic) = chronic HBV + acute hepatitis D, HBsAg and anti-HDV IgM positive, bad prognosis with chronic HDV-related cirrhosis and anti-LKM-3 antibody; closing note: HEV in pregnancy also has a high risk of fulminant hepatic failure.",
     "parts": ["p1044a"]},
])
