#!/usr/bin/env python3
"""Ch 66 Alcoholic Liver Disease — Book p1026-1029, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 66

# ---------------------------------------------------------------- p1026
p1026 = [
    ("numeric",
     "How is '1 peg' defined at the top of the chapter?",
     ["60 ml of alcohol (40%)", "30 ml of alcohol (40%)", "60 ml of alcohol (20%)", "100 ml of alcohol (10%)"],
     "'1 peg = 60 ml Alcohol (40%)'."),
    ("match",
     "Cirrhogenic dose — match — 1) Male 2) Female … A) 20–40 gm/day (1 peg) B) 40–80 g/day (2 pegs)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Male: 40–80 g/day (2 pegs); Female: 20–40 gm/day (1 peg)."),
    ("numeric",
     "The cirrhogenic dose must be consumed for how long to produce cirrhosis?",
     ["5 days a week for 15 years", "Daily for 5 years", "3 days a week for 10 years", "5 days a week for 3–5 years"],
     "'→ 5 days a week for 15 years → Cirrhosis.'"),
    ("numeric",
     "Alcoholic hepatitis: printed mortality and best serum marker?",
     ["Mortality 70%; carbohydrate-deficient transferrin", "Mortality 30%; gamma-glutamyl transferase (GGT)", "Mortality 70%; mean corpuscular volume (MCV)", "Mortality 10%; AST:ALT ratio > 2:1"],
     "'Mortality 70%' and 'Best Serum marker : Carbohydrate deficient transferrin'."),
    ("numeric",
     "In the progression diagram, alcohol consumption leads to alcoholic fatty liver after how long, and is that stage reversible?",
     ["3–5 years; reversible", "15 years; irreversible", "3–5 months; irreversible", "6 weeks; reversible"],
     "'Alcohol Consumption —3–5 years→ Alcoholic fatty liver (Reversible)'."),
    ("truefalse",
     "From the fatty-liver branch point, judge: I Cirrhosis begins micronodular and progresses to macronodular. II In macronodular cirrhosis the nucleus is pushed to the periphery. III Cirrhosis carries risk of HCC.",
     ["All three true", "I and III true, II false", "I true, II and III false", "II and III true, I false"],
     "Cirrhosis → micronodular → Progress → macronodular (Nucleus pushed to periphery); → Risk of HCC."),
    ("recall",
     "The other branch from alcoholic fatty liver is alcoholic hepatitis (high mortality). What cause is printed beneath it?",
     ["Binge drinking", "Poor-metaboliser polymorphism", "Malnutrition", "Hepatitis C co-infection"],
     "'Alcoholic hepatitis (High mortality) — Cause : Binge drinking'."),
    ("oddoneout",
     "Alcohol metabolism — which of the following is NOT one of the three enzymes branched in the diagram?",
     ["Alcohol oxidase", "Aldehyde dehydrogenase", "Cyt P2E1", "Catalase"],
     "Enzyme: Aldehyde dehydrogenase; Cyt P2E1; Catalase."),
    ("fillup",
     "Fill up the pathway: Alcohol → ______ (toxic to liver) —aldehyde dehydrogenase→ metabolic products.",
     ["Acetaldehyde", "Acetate", "Acetyl-CoA", "Methanol"],
     "'Alcohol → Acetaldehyde —Aldehyde dehydrogenase→ metabolic products'; 'Acetaldehyde → Toxic to liver'."),
    ("scenario",
     "Two men drink identically; one carries an aldehyde-dehydrogenase polymorphism making him a poor metaboliser. Per the diagram, what is his particular risk?",
     ["Prone to develop alcohol hepatitis", "Protected, because less acetaldehyde is formed", "Prone to macrovesicular steatosis only", "Higher carbohydrate-deficient transferrin but no liver risk"],
     "Polymorphism → Efficient metaboliser / Poor metaboliser: 'Prone to develop alcohol hepatitis'."),
]

# ---------------------------------------------------------------- p1027
p1027 = [
    ("fillup",
     "Fill up: The adverse-effects mnemonic printed for acetaldehyde/alcohol injury is ______.",
     ["HESST", "HEART", "HESSE", "SHEET"],
     "'mnemonic : HESST' — Hypoxia, Endoplasmic reticulum stress, Superoxide, ↓SAM/↑SAH, Toxic effect of acetaldehyde."),
    ("match",
     "HESST — match — 1) Hypoxia 2) Endoplasmic reticulum stress 3) Superoxide … A) Mallory hyaline bodies B) Reactive oxygen species produced by Cyt P2E1 C) Mitochondrial injury in zone 3 (centrilobular hepatocyte)",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "Hypoxia: mitochondrial injury in Zone 3 (centrilobular); ER stress: Mallory hyaline bodies; Superoxide: ROS produced by Cyt P2E1."),
    ("recall",
     "'↓SAM / ↑SAH' in the HESST list is linked to which factor labelled the most important pathogenic factor, and which drug is given as its Rx?",
     ["↑ TNF-α; pentoxifylline", "↑ IL-6; tocilizumab", "↑ TGF-β; pirfenidone", "↑ NADH; thiamine"],
     "'↓SAM/↑SAH : ↑ TNFα most important pathogenic factor' and 'Rx : Pentoxifylline'."),
    ("fillup",
     "Fill up the chain printed for the toxic effect of acetaldehyde: ↑ NADH → ↓ ______ → ______ gut.",
     ["glutathione; leaky", "ATP; ischaemic", "albumin; oedematous", "SAM; leaky"],
     "'Toxic effect of acetaldehyde : ↑ NADH → ↓ glutathione → leaky gut'."),
    ("match",
     "Match — 1) Left image 2) Right image … A) Centrilobular necrosis, balloon degeneration, hepatocyte Mallory bodies B) Eosinophilic body inside hepatocyte: Mallory's hyaline bodies (endoplasmic reticulum stress)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Left caption: 'Eosinophilic body inside hepatocyte : Mallory's hyaline bodies (Endoplasmic reticulum stress)'. Right: 'Centrilobular necrosis, Balloon degeneration hepatocyte Mallory bodies'."),
    ("numeric",
     "Under the right micrograph, fatty liver disease is defined by fat in what proportion of hepatocytes, and what does fat pushing the nucleus to the periphery denote?",
     ["> 5% hepatocytes; macronodular", "> 30% hepatocytes; microvesicular", "> 50% hepatocytes; macrovesicular", "> 10% hepatocytes; micronodular"],
     "'Fat in >5% Hepatocytes : Fatty liver disease. Fat pushes nucleus to periphery : macronodular.' (printed wording is macronodular)."),
    ("recall",
     "Laboratory features of alcoholic hepatitis — what is the first bullet and what enzyme range is given?",
     ["Neutrophilia (TC ↑); liver enzymes 300–500 U/L", "Lymphocytosis; liver enzymes >1000 U/L", "Thrombocytopenia; liver enzymes <150 U/L", "Eosinophilia; ALP 300–500 U/L"],
     "'Neutrophilia : TC ↑' and 'Liver enzymes : 300 – 500 U/L'."),
    ("match",
     "AST:ALT ratio — match — 1) > 2 : 1 2) > 3 : 1 … A) Highly suggestive of alcoholic hepatitis B) Likely alcoholic hepatitis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'>2:1 Likely Alcoholic hepatitis; >3:1 Highly suggestive of Alcoholic hepatitis'."),
    ("truefalse",
     "Judge the remaining lab bullets: I S. albumin is a significant marker (positive acute-phase reactant). II PT/INR is raised. III MCV is raised (macrocytosis).",
     ["I false; II and III true", "All three true", "I and II true, III false", "I true; II and III false"],
     "'S. Albumin : Not significant (Negative acute phase reactant)'; 'PT/INR : ↑'; 'MCV ↑ : macrocytosis'."),
    ("recall",
     "Thiamine depletion in alcoholics is drawn as inhibiting (−) two reactions. Which pair?",
     ["Pyruvate → Acyl-CoA (blocked) and the transketolase reaction", "Glucose → glycogen (blocked) and hepatic gluconeogenesis", "Acetaldehyde → acetate (blocked) and mitochondrial β-oxidation", "Ornithine → citrulline (blocked) and glutamine synthetase"],
     "'Thiamine depletion (−) (−) → Pyruvate ✗→ Acyl-CoA ; Transketolase Reaction' (printed Acyl-CoA; the physiological product is acetyl-CoA)."),
    ("oddoneout",
     "Clinical features listed on this page — which is NOT printed?",
     ["Splenomegaly", "Jaundice", "P/A soft, painful", "Hepatomegaly"],
     "Clinical features: Jaundice; P/A Soft, Painful; Hepatomegaly."),
]

# ---------------------------------------------------------------- p1028
p1028 = [
    ("recall",
     "Histopathological features of alcoholic hepatitis: where is the fatty infiltration located?",
     ["Centrilobular (zone III involvement)", "Periportal (zone I involvement)", "Mid-zonal (zone II involvement)", "Diffuse panlobular (all zones)"],
     "'Centrilobular fatty infiltration (Zone III involvement)'."),
    ("fillup",
     "Fill up the 'classical features' bullet: Ballooning degeneration / Alcoholic hyaline surrounding ______ infiltrate.",
     ["polymorphonuclear", "lymphoplasmacytic", "eosinophilic", "granulomatous"],
     "'Ballooning degeneration/Alcoholic hyaline surrounding polymorphonuclear infiltrate (Classical features)'."),
    ("recall",
     "The Note under histopathology says which viral hepatitis shows fatty liver-like changes / hepatic steatosis?",
     ["Hepatitis C", "Hepatitis B", "Hepatitis E", "Hepatitis A"],
     "'Note : Hepatitis C : fatty liver-like changes / hepatic steatosis.'"),
    ("recall",
     "What does the trichrome micrograph on p1028 illustrate, per its caption?",
     ["Alcoholic hepatitis: nodules with fibrous septation", "Primary sclerosing cholangitis: concentric periductal fibrosis", "NASH: chicken-wire pericellular fibrosis of zone 3", "NCPF: obliterative portal venopathy with sclerotic tracts"],
     "Caption: 'Alcoholic hepatitis : Nodules with fibrous septation'."),
    ("fillup",
     "Fill up the complications chain: Alcoholic hepatitis → Fulminant hepatitis / Decompensated → Encephalopathy + Coagulopathy (Portal HTN) → ↑ ______ → Death.",
     ["ICT (intracranial tension)", "INR (coagulopathy)", "Ammonia (encephalopathy)", "Bilirubin (jaundice)"],
     "'… → Encephalopathy + Coagulopathy → ↑ ICT → Death', with 'Portal HTN' bracketed beneath."),
    ("numeric",
     "Discriminant factor (DF) — state the formula and poor-prognosis cut-off exactly as printed.",
     ["4.6 × (PT patient − PT control) + S. bilirubin; poor prognosis ≥ 32", "4.6 × (PT control − PT patient) + albumin; ≥ 18", "PT × bilirubin / 4.6; ≥ 9", "4.6 × INR + bilirubin; ≥ 32"],
     "'Discriminant factor : 4.6 × (PT(PE) − PT(C)) + S. bilirubin — Poor prognosis : ≥ 32'."),
    ("match",
     "Prognostic scores — match — 1) MELD 2) Glasgow 3) Discriminant factor … A) ≥ 32 B) ≥ 9 C) ≥ 18",
     ["1-C, 2-B, 3-A", "1-A, 2-C, 3-B", "1-B, 2-C, 3-A", "1-C, 2-A, 3-B"],
     "MELD ≥ 18; Glasgow ≥ 9; DF ≥ 32."),
    ("management",
     "Treatment: what is the printed indication for steroid in alcoholic hepatitis, and the regimen?",
     ["DF score ≥ 32; 1 mg/kg × 7 days tapering over 3 weeks", "MELD ≥ 18; 1 mg/kg/day × 4 weeks tapering over 12 weeks", "Glasgow ≥ 9; 40 mg/day × 4 weeks", "Any jaundice; 0.5 mg/kg × 2 weeks"],
     "'Indication to steroid : DF Score ≥ 32 → Start → 1 mg/kg × 7 days tapering over 3 weeks.'"),
    ("oddoneout",
     "Which of the following is NOT printed as 'unfit for steroid'?",
     ["Hepatic encephalopathy", "Sepsis", "Renal failure", "Ongoing GI disease"],
     "Unfit for steroid: Sepsis; Renal failure; Ongoing GI disease."),
    ("scenario",
     "A binge drinker with DF 40 develops sepsis. Steroids are unsuitable. What alternative does the flowchart give, with its mechanism and dose?",
     ["Pentoxifylline — inhibits TNF-α — 400 mg TDS × 4 weeks", "Pentoxifylline — PDE-5 inhibitor — 400 mg OD × 1 week", "N-acetylcysteine — glutathione donor — 150 mg/kg", "Rifaximin — gut decontamination — 550 mg BD"],
     "Unfit for steroid → Pentoxifylline: 'Inhibits TNF-α; 400 mg TDS × 4 weeks'."),
]

# ---------------------------------------------------------------- p1029
p1029 = [
    ("recall",
     "Miscellaneous note: what is printed as the most common cause of cirrhosis?",
     ["NASH", "Alcohol", "Hepatitis B", "Hepatitis C"],
     "'m/c cause of cirrhosis : NASH'."),
    ("oddoneout",
     "Causes of micronodular cirrhosis — which is NOT in the printed list?",
     ["Wilson's disease", "Indian childhood cirrhosis (ICC)", "Cystic fibrosis", "Budd Chiari syndrome"],
     "Micronodular: Alcoholic hepatitis, Biliary cirrhosis, ICC, Cystic fibrosis, Budd Chiari syndrome, Hemochromatosis. Wilson's is the printed macronodular cause."),
    ("recall",
     "Which single cause is printed for macronodular cirrhosis?",
     ["Wilson's disease", "Hemochromatosis", "Alcoholic hepatitis", "Biliary cirrhosis"],
     "'Causes of macronodular cirrhosis : Wilson's disease'."),
    ("fillup",
     "Fill up the mnemonic for microvesicular steatosis: 'Pretty visits ______ with Alcohol and ______'.",
     ["Jamaica; Acid", "Jakarta; Aspirin", "Japan; Amiodarone", "Java; Acetaminophen"],
     "'mnemonic : Pretty visits Jamaica with Alcohol and Acid.'"),
    ("match",
     "Decode the mnemonic letters — match — 1) P 2) R 3) T 4) V … A) Tetracycline B) Reye's syndrome C) Valproate D) Pregnancy",
     ["1-D, 2-B, 3-A, 4-C", "1-D, 2-A, 3-B, 4-C", "1-B, 2-D, 3-C, 4-A", "1-D, 2-B, 3-C, 4-A"],
     "Microvesicular column: Pregnancy, Reye's syndrome, Tetracycline, Valproate, Jamaican vomiting sickness, Alcoholic liver disease, Acid lipase deficiency."),
    ("oddoneout",
     "Which condition is listed under MACROvesicular (not microvesicular) steatosis?",
     ["Wilson's disease", "Jamaican vomiting sickness", "Acid lipase deficiency", "Alcoholic liver disease"],
     "Macrovesicular: HCV, NASH, Wilson's disease."),
    ("truefalse",
     "Judge: I Alcoholic liver disease is placed in the microvesicular column. II HCV and NASH are in the macrovesicular column.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Alcoholic liver disease is in the microvesicular list (the 'Alcohol' of the mnemonic); HCV, NASH, Wilson's are macrovesicular."),
    ("recall",
     "How is Reye's syndrome characterised in the bullet after the table?",
     ["Swollen mitochondria with reduced number", "Tennis-racquet mitochondrial cristae", "Glycogenated nuclei", "Nutmeg congestion"],
     "'Reye's syndrome : Swollen mitochondria with reduced number.'"),
    ("fillup",
     "Fill up: 'Nutmeg liver : Chronic ______ condition.'",
     ["venous", "arterial", "biliary", "granulomatous"],
     "'Nutmeg liver : Chronic venous condition.'"),
    ("recall",
     "Mallory–Denk bodies are defined as what, and located where?",
     ["Endoplasmic reticulum stress — eosinophilic inclusion bodies in hepatocytes", "Mitochondrial stress — basophilic inclusions in Kupffer cells", "Copper-bound protein — brown granules in bile ducts", "Glycogen — clear nuclear vacuoles"],
     "'Mallory denk bodies : Endoplasmic reticulum stress (Eosinophilic inclusion bodies) In hepatocytes.'"),
    ("oddoneout",
     "Mallory–Denk bodies are 'seen in' a printed list. Which is NOT in that list?",
     ["Hepatitis B / Hepatitis C", "Wilson's", "ICC (Indian childhood cirrhosis)", "PBC"],
     "Seen in: Wilson's, ICC, NASH, Cholestasis, Alcohol/Alpha-1 antitrypsin deficiency, PBC, HCC. 'Not seen in HBV / HCV.'"),
    ("truefalse",
     "Judge: I Mallory–Denk bodies are seen in HCC. II They are seen in alpha-1 antitrypsin deficiency. III They are seen in HBV.",
     ["I and II true, III false", "All three true", "I true, II and III false", "III true, I and II false"],
     "HCC and Alcohol/Alpha-1 antitrypsin deficiency are in the seen-in list; 'Not seen in HBV / HCV'."),
]

write_part(CH, "p1026a", 1026, "Peg, cirrhogenic dose, alcoholic hepatitis mortality/marker, progression diagram, alcohol metabolism", p1026)
write_part(CH, "p1027a", 1027, "HESST adverse effects, acetaldehyde toxicity, micrographs, laboratory and clinical features", p1027)
write_part(CH, "p1028a", 1028, "Histopathology, complications chain, prognostic scores and treatment", p1028)
write_part(CH, "p1029a", 1029, "Miscellaneous: cirrhosis causes, micro vs macrovesicular steatosis, Reye's, nutmeg liver, Mallory-Denk bodies", p1029)

write_units(CH, [
    {"title": "Dose thresholds, progression and alcohol metabolism",
     "sec": "Dose & metabolism · p1026",
     "guide": "1 peg = 60 ml 40%; male 40–80 g (2 pegs), female 20–40 g (1 peg), 5 days/week × 15 years; alcoholic hepatitis mortality 70%, CDT best marker; 3–5 years to reversible fatty liver → cirrhosis (micro → macronodular, nucleus to periphery, HCC risk) or alcoholic hepatitis (binge); enzymes ALDH, CYP2E1, catalase; acetaldehyde toxic; ALDH polymorphism poor metaboliser prone to hepatitis.",
     "parts": ["p1026a"]},
    {"title": "HESST injury, histology images, laboratory and clinical features",
     "sec": "Pathogenesis & labs · p1027",
     "guide": "Hypoxia zone 3 mitochondria, ER stress Mallory hyaline, superoxide via CYP2E1, ↓SAM/↑SAH → TNF-α (pentoxifylline), acetaldehyde ↑NADH → ↓glutathione → leaky gut; fat >5% hepatocytes; neutrophilia, enzymes 300–500, AST:ALT >2:1 likely / >3:1 highly suggestive, albumin not significant, ↑PT/INR, ↑MCV, thiamine blocks pyruvate→acyl-CoA and transketolase; jaundice, soft painful abdomen, hepatomegaly.",
     "parts": ["p1027a"]},
    {"title": "Histopathology, complications, prognostic scores and treatment",
     "sec": "Scores & Rx · p1028",
     "guide": "Zone III fatty infiltration; ballooning/alcoholic hyaline with PMN infiltrate; HCV steatosis note; nodules with fibrous septation; fulminant → encephalopathy + coagulopathy → ↑ICT → death; DF = 4.6 × (PT pt − control) + bilirubin ≥ 32, MELD ≥ 18, Glasgow ≥ 9; steroid 1 mg/kg × 7 days taper 3 weeks; unfit: sepsis, renal failure, GI disease → pentoxifylline 400 mg TDS × 4 weeks.",
     "parts": ["p1028a"]},
    {"title": "Miscellaneous notes: cirrhosis morphology, steatosis mnemonic, Reye's, nutmeg, Mallory–Denk",
     "sec": "Miscellaneous · p1029",
     "guide": "NASH m/c cause of cirrhosis; micronodular list (alcohol, biliary, ICC, CF, Budd-Chiari, hemochromatosis) vs macronodular Wilson's; 'Pretty visits Jamaica with Alcohol and Acid' microvesicular vs HCV/NASH/Wilson's macrovesicular; Reye's swollen fewer mitochondria; nutmeg = chronic venous; Mallory-Denk ER-stress eosinophilic inclusions seen in Wilson's, ICC, NASH, cholestasis, alcohol/A1AT, PBC, HCC, not HBV/HCV.",
     "parts": ["p1029a"]},
])
