#!/usr/bin/env python3
"""Ch 73 Tropical Infections: Synopsis — Book p1053-1060, strict source order."""
from itemwriter_70_74 import write_part, write_units

CH = 73

# ---------------------------------------------------------------- p1053
p1053 = [
    ("match",
     "Pattern of fever — match the infection to the printed pattern — 1) Salmonella 2) Malaria 3) Leptospirosis / scrub typhus … A) Chills and rigors with fatigue B) Myalgia of the calf muscles and conjunctival suffusion in a farmer C) Step-ladder / rising pattern",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'· Salmonella : Step ladder / Rising pattern. · malaria : Chills and rigors a/w fatigue. · Leptospirosis, scrub typhus : A/w myalgia (Calf muscle), conjunctival suffusion in a farmer'."),
    ("recall",
     "Which occupation is printed in the leptospirosis / scrub typhus fever-pattern line?",
     ["A farmer", "A sewer worker", "A butcher", "A fisherman"],
     "'Leptospirosis, scrub typhus : A/w myalgia (Calf muscle), conjunctival suffusion in a farmer'."),
    ("match",
     "Dengue fever — match the symptom group — 1) Grade of fever 2) Pain 3) Gastrointestinal … A) High grade B) Vomiting, described as a few episodes C) Retro-orbital and occipital pain",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'· Dengue : - High grade fever a/w : a. Retro-orbital pain, b. Occipital pain, c. vomiting'."),
    ("oddoneout",
     "Which is NOT printed among the pains of dengue on this page?",
     ["Loin pain", "Retro-orbital pain", "Occipital pain", "Headache"],
     "Printed: retro-orbital pain and occipital pain with vomiting."),
    ("recall",
     "Which investigation is printed first in the fever work-up?",
     ["CBC profile", "Blood culture", "Widal test", "Chest radiograph"],
     "'Investigations : · CBC profile'."),
    ("fillup",
     "Fill up (Malaria testing): 'Quantitative buffy coat (QBC), repeated every ______ hours.'",
     ["12", "6", "24", "48"],
     "'· malaria : Quantitative buffy coat (QBC). Repeated every 12 hours'."),
    ("numeric",
     "How many consecutive negative QBC tests does the page require before malaria is ruled out?",
     ["3 consecutive tests", "1 test", "2 tests", "6 tests"],
     "'Ruled out : If 3 consecutive tests negative'."),
    ("recall",
     "What does the page advise starting on day 4 of fever?",
     ["Doxycycline (100 mg BD) plus co-trimoxazole double strength BD",
      "Intravenous ceftriaxone monotherapy",
      "Artesunate plus amodiaquine",
      "Oral amoxicillin"],
     "'Fever on day 4 : Start on : Doxycycline (100mg BD) + Cotrimoxazole DS (Double strength) BD'."),
    ("recall",
     "The day-4 empirical regimen is printed as covering which infections?",
     ["Leptospirosis and scrub typhus", "Dengue and chikungunya",
      "Malaria and typhoid", "Tuberculosis and brucellosis"],
     "Under the day-4 regimen the page prints 'Leptospirosis, Scrub typhus'."),
    ("truefalse",
     "Judge the fever algorithm: I Malaria is excluded only after three consecutive negative QBC tests. II By day 4 the page starts doxycycline plus double-strength co-trimoxazole for leptospirosis and scrub typhus.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Ruled out : If 3 consecutive tests negative' and 'Fever on day 4 : Start on : Doxycycline (100mg BD) + Cotrimoxazole DS BD'."),
    ("recall",
     "How is the fever evaluation organised on this page?",
     ["Day by day — fever on day 1-2, day 3, day 4 and day 5",
      "By organ system affected",
      "By causative organism alphabetically",
      "Only by the height of the fever"],
     "The synopsis is headed 'Fever in Infections' and then organised as 'Fever on day 1-2', 'Fever on day 3', 'Fever on day 4' and 'Fever on day 5'."),
]

# ---------------------------------------------------------------- p1054
p1054 = [
    ("match",
     "Salmonellosis by week — match — 1) Week 1 2) Week 3 … A) Ileocaecal hyperplasia with GI perforation and bleeding, encephalopathy B) Step-ladder fever with or without chills, relative bradycardia, vague abdominal pain and GI upset",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Week 1: '· Step ladder fever ± chills, · Relative bradycardia, Vague abdominal pain, GI disturbances'. Week 3: 'Ileocoecal hyperplasia > GI perforation, bleeding' and 'Encephalopathy'."),
    ("recall",
     "Which pulse-temperature relationship is printed for the first week of salmonellosis?",
     ["Relative bradycardia", "Relative tachycardia",
      "Pulsus paradoxus", "Pulsus alternans"],
     "'· Relative bradycardia' is listed under week 1."),
    ("truefalse",
     "Judge the week-3 column: I Ileocaecal hyperplasia can progress to GI perforation and bleeding. II Encephalopathy is listed as a week-3 complication.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Week 3 prints 'Ileocoecal hyperplasia > GI perforation, bleeding' and 'Encephalopathy'."),
    ("recall",
     "Which complication is printed for the chronic carrier state of Salmonella?",
     ["Gall stones", "Cholangiocarcinoma", "Cirrhosis", "Pancreatic abscess"],
     "'Complication : Gall stones in chronic carrier state'."),
    ("numeric",
     "Incubation period printed for salmonellosis?",
     ["5 – 20 days", "1 – 3 days", "20 – 40 days", "6 – 8 weeks"],
     "'Incubation period : 5-20 days'."),
    ("match",
     "Investigations — match the test to its printed yield — 1) Widal 2) Blood culture … A) 90% positivity in the first week B) Low positivity in the first and second weeks, 80-100% positivity by the third week",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Widal: '· Low positivity (1st and 2nd week), 80-100% positivity (3rd week)'. Blood culture: '· 90% positivity (1st week)'."),
    ("numeric",
     "What positivity does the page print for Widal in the third week?",
     ["80 – 100%", "90%", "50%", "Below 10%"],
     "'80-100% positivity (3rd week)'."),
    ("recall",
     "Which culture medium is printed as giving jet-black colonies for Salmonella?",
     ["Wilson-Blair bismuth sulphite agar", "MacConkey agar",
      "Blood agar", "Loeffler serum slope"],
     "'Wilson Blair bismuth sulphite agar : Jet black colonies'."),
    ("oddoneout",
     "Which medium is NOT printed in the salmonellosis investigations?",
     ["Chocolate agar", "MacConkey agar", "Wilson-Blair bismuth sulphite agar", "Blood culture"],
     "Printed: blood culture (90% first week), MacConkey agar and Wilson-Blair bismuth sulphite agar."),
    ("recall",
     "Rose spots are illustrated on this page next to which disease section?",
     ["Salmonellosis", "Dengue", "Leptospirosis", "Malaria"],
     "The 'Rose spots' label sits in the salmonellosis page image."),
    ("scenario",
     "A patient in the third week of enteric fever has abdominal guarding and a drop in blood pressure. Which week-3 complication does the page list?",
     ["GI perforation and bleeding from ileocaecal hyperplasia",
      "Acute cholecystitis with empyema",
      "Mycotic aneurysm of the aorta",
      "Splenic abscess rupture"],
     "Week 3: 'Ileocoecal hyperplasia > GI perforation, bleeding'."),
]

# ---------------------------------------------------------------- p1055
p1055 = [
    ("match",
     "Pathogenesis of typhoid — match — 1) Entry 2) Multiplication 3) Seeding 4) Re-entry … A) Liver, spleen and bone marrow B) Via the bloodstream C) Gallbladder, biliary system and lymphatic system of bowel D) Intestinal tract with ileocaecal hyperplasia",
     ["1-B, 2-A, 3-C, 4-D", "1-A, 2-C, 3-B, 4-D", "1-D, 2-A, 3-C, 4-B", "1-B, 2-C, 3-A, 4-D"],
     "'Via blood stream (m/c) → In liver, spleen & bone marrow multiply, re-enter → Invades & multiplies in Gallbladder, Biliary system, Lymphatic system of bowel → Pass into intestinal tract and causes ileocoecal hyperplasia'."),
    ("recall",
     "Which route does the page print as the most common for dissemination in typhoid?",
     ["Via the bloodstream", "Via lymphatics only", "Direct peritoneal spread", "Retrograde biliary spread"],
     "'Via blood stream (m/c)'."),
    ("truefalse",
     "Judge the pathogenesis: I The organism multiplies in liver, spleen and bone marrow. II The gallbladder and biliary system are seeded and the organism later re-enters the bowel.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both statements follow the printed chain through the gallbladder, biliary system and bowel lymphatics."),
    ("recall",
     "Which anatomical site is printed as the site of the lesion produced after intestinal re-entry?",
     ["Ileocaecal hyperplasia", "Rectal stricture", "Gastric ulcer", "Appendiceal abscess"],
     "'Pass into intestinal tract and causes ileocaecal hyperplasia'."),
    ("match",
     "Treatment — match — 1) Uncomplicated 2) Complicated … A) Ceftriaxone 2 g IV for 14 days B) Co-trimoxazole double strength BD for 14 days, or azithromycin 1 g once daily for 7 days",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Uncomplicated cases : Cotrimoxazole (DS) BD × 14 days OR Azithromycin 1g OD × 7 days'; 'Complicated cases : Ceftriaxone 2g I/V × 14 days'."),
    ("numeric",
     "Duration printed for azithromycin in uncomplicated enteric fever?",
     ["7 days", "14 days", "5 days", "3 days"],
     "'Azithromycin 1g OD × 7 days'."),
    ("numeric",
     "Duration printed for intravenous ceftriaxone in complicated enteric fever?",
     ["14 days", "7 days", "5 days", "21 days"],
     "'Ceftriaxone 2g I/V × 14 days'."),
    ("fillup",
     "Fill up (Dengue): 'Incubation period : ______ days.'",
     ["7 – 10", "2 – 3", "14 – 21", "1 – 2"],
     "'Incubation period : 7-10 days'."),
    ("match",
     "Dengue disease course — match — 1) Day 1 to 3 2) Day 4 onwards … A) NS1 antigen negative, fever subsides, rash appears B) NS1 antigen positive",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Day 1 to 3 : NS-1 antigen positive'; 'Day 4 onwards : NS-1 antigen negative; Fever subsides; Rash'."),
    ("match",
     "Dengue symptoms — match — 1) Fever 2) Pain 3) Gut … A) High grade B) Vomiting C) Headache and retro-orbital pain",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'Symptoms : High grade fever, Headache, · Retro-orbital pain, · vomiting'."),
    ("recall",
     "What does the page print about the platelet count in dengue without warning signs?",
     ["It falls but is given as not below 50,000",
      "It stays completely normal",
      "It always falls below 10,000",
      "It rises above 4,50,000"],
     "'Day 4 onwards : ↓ Platelet counts (Not < 50,000)' with '· Leucopenia' and 'Dengue without warning signs'."),
    ("recall",
     "Which white-cell change is printed on day 4 onwards in dengue?",
     ["Leucopenia", "Leucocytosis", "Eosinophilia", "Basophilia"],
     "'Day 4 onwards : … · Leucopenia'."),
    ("truefalse",
     "Judge the dengue block: I NS1 antigen is positive from day 1 to day 3 and negative from day 4. II The fever subsides and the rash appears from day 4 onwards.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Day 1 to 3 : NS-1 antigen positive'; 'Day 4 onwards : NS-1 antigen negative', 'Fever subsides', 'Rash'."),
]

# ---------------------------------------------------------------- p1056
p1056 = [
    ("recall",
     "Which days are printed as the most crucial period of dengue?",
     ["Day 4 to 7", "Day 1 to 3", "Day 8 to 10", "Day 10 to 14"],
     "'Day 4-7 : (most crucial period)'."),
    ("match",
     "Critical-phase problems — match — 1) Bleeding 2) Capillary leak … A) Pleural or pericardial effusion and ascites B) Falling platelet count",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'In some patients : ↓ Platelet count (Bleeding), Capillary leak syndrome (Pleural / pericardial effusion, ascites)'."),
    ("recall",
     "How is capillary leak syndrome manifested, according to the page?",
     ["Pleural or pericardial effusion and ascites", "Generalised lymphadenopathy",
      "Pulmonary fibrosis", "Peripheral oedema alone"],
     "'Capillary leak syndrome (Pleural / pericardial effusion, ascites)'."),
    ("match",
     "Monitoring in the critical phase — match — 1) Circulation 2) Volume status 3) Haemoconcentration … A) IVC diameter B) Haematocrit C) Blood pressure supported with IV fluids",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'monitor and maintenance : · BP by I/V fluids, · IVC diameter, · Hematocrit'."),
    ("numeric",
     "What platelet thresholds does the page print for transfusing platelets in dengue?",
     ["Below 10,000, or below 20,000 with bleeding",
      "Below 50,000, or below 1 lakh with bleeding",
      "Below 1 lakh in every case",
      "Only below 5,000"],
     "'Platelets (Administer if < 10,000 OR < 20,000 + bleeding)'."),
    ("recall",
     "What does the page print about steroids in dengue?",
     ["No use of steroids", "Steroids for all patients",
      "Steroids only in shock", "Steroids to raise platelets"],
     "'No use of steroids'."),
    ("truefalse",
     "Judge the management block: I Monitoring covers blood pressure, IVC diameter and haematocrit. II Steroids have no role.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both statements reproduce 'monitor and maintenance' and 'No use of steroids'."),
    ("match",
     "Course of illness phases — match — 1) Early 2) Critical 3) Late … A) Febrile B) Recovery C) Critical",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'Course of illness : Febrile, Critical, Recovery phases'."),
    ("match",
     "Day-wise chart — match the column to its content — 1) Temperature 2) Potential clinical issues 3) Lab changes 4) Serology and virology … A) Dehydration, shock and bleeding, then reabsorption and fluid overload, organ impairment, platelets B) IgM and IgG, viraemia C) Haematocrit D) Up to 40°C",
     ["1-D, 2-A, 3-C, 4-B", "1-A, 2-D, 3-B, 4-C", "1-D, 2-B, 3-A, 4-C", "1-C, 2-A, 3-D, 4-B"],
     "The chart rows are 'Days of illness 1-10', 'Temperature' (40°), 'Potential clinical issues' (dehydration, shock/bleeding, reabsorption/fluid overload, organ impairment, platelet), 'Lab changes' (haematocrit), 'Serology and virology' (IgM/IgG, viraemia) and 'Course of illness' (febrile, critical, recovery)."),
    ("fillup",
     "Fill up: 'Note : IgM becomes positive from day ______ onwards.'",
     ["5", "3", "7", "10"],
     "'Note : IgM become positive : Day 5 onwards'."),
    ("recall",
     "Which warning-sign group is contrasted with 'dengue without warning signs' on this spread?",
     ["Dengue with warning signs / organ failure", "Dengue haemorrhagic fever grade IV",
      "Expanded dengue syndrome", "Dengue shock syndrome only"],
     "'Dengue with warning signs/organ failure' is the label under the critical-period branch."),
    ("scenario",
     "On day 6 of dengue a patient develops ascites, a falling haematocrit and a platelet count of 15,000 with mucosal bleeding. Which printed intervention applies?",
     ["Transfuse platelets, since the count is below 20,000 with bleeding",
      "No transfusion, since the count is above 10,000",
      "Start steroids immediately",
      "Discharge with oral fluids"],
     "The threshold is 'Administer if < 10,000 OR < 20,000 + bleeding'."),
]

# ---------------------------------------------------------------- p1057
p1057 = [
    ("match",
     "Leptospirosis features — match — 1) Onset 2) Muscles 3) Eyes … A) Conjunctival congestion and suffusion B) Calf muscle tenderness C) Abrupt onset fever of low to intermediate grade",
     ["1-C, 2-B, 3-A", "1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-A, 3-B"],
     "'Features : · Abrupt onset fever (Low to intermediate grade), myalgia — Calf muscle tenderness, Conjunctival congestion' and 'Conjunctival suffusion'."),
    ("recall",
     "How is the fever of leptospirosis described on this page?",
     ["Abrupt onset, low to intermediate grade", "Insidious, high grade with rigors",
      "Biphasic with a saddle back", "Undulant with night sweats"],
     "'· Abrupt onset fever (Low to intermediate grade)'."),
    ("match",
     "Complications — match — 1) Hepatorenal syndrome 2) Renal lesion 3) Electrolytes … A) Non-oliguric AKI with hypokalaemia and hypomagnesaemia B) Hepatitis with jaundice plus acute tubular necrosis C) Thrombocytopenia",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'Hepatorenal syndrome : Hepatitis with jaundice + Acute tubular necrosis'; 'Non-oliguric AKI with : 1. Hypokalemia, 2. Hypomagnesemia'; 'Thrombocytopenia'."),
    ("recall",
     "Which electrolyte disturbances are printed under non-oliguric AKI in leptospirosis?",
     ["Hypokalaemia and hypomagnesaemia", "Hyperkalaemia and hypermagnesaemia",
      "Hypernatraemia and hypercalcaemia", "Hyponatraemia and hyperkalaemia"],
     "'Non-oliguric AKI with : 1. Hypokalemia, 2. Hypomagnesemia'."),
    ("match",
     "Immunological manifestations — match — 1) Cardiac 2) Neurological 3) Muscle … A) Myocarditis with secondary MR / AR, and aseptic meningitis B) Rhabdomyolysis C) Aseptic meningitis",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'Immunological manifestations : myocarditis, · Secondary MR/AR, + Aseptic meningitis'; 'Rhabdomyolysis'."),
    ("oddoneout",
     "Which is NOT printed among the leptospirosis complications?",
     ["Pancreatic pseudocyst", "Myocarditis", "ARDS", "Rhabdomyolysis"],
     "Printed complications: hepatorenal syndrome, non-oliguric AKI with hypokalaemia and hypomagnesaemia, thrombocytopenia, myocarditis with secondary MR/AR, aseptic meningitis, ARDS and rhabdomyolysis."),
    ("recall",
     "Which diagnostic criteria are printed for leptospirosis?",
     ["Modified Faine's criteria", "Duke criteria", "WHO dengue criteria", "Ramsay Hunt criteria"],
     "'Criteria : modified Faine's criteria'."),
    ("recall",
     "Which test is printed as the gold standard for leptospirosis?",
     ["Microscopic agglutination test (MAT)", "IgM ELISA", "Dark-field microscopy", "PCR of urine"],
     "'Gold standard test : microscopic agglutination test (MAT)'."),
    ("fillup",
     "Fill up (Treatment): 'Doxycycline + Inj Ceftriaxone ______ IV OD.'",
     ["2 g", "1 g", "500 mg", "3 g"],
     "'Treatment : Doxycycline + Inj Ceftriaxone 2g IV OD'."),
    ("recall",
     "Which period does the page print as the vital period in leptospirosis?",
     ["4 – 7 days", "1 – 3 days", "10 – 14 days", "2 – 3 weeks"],
     "'4-7 days (Vital period)'."),
    ("scenario",
     "A farmer presents with abrupt fever, tender calf muscles, conjunctival suffusion, jaundice and non-oliguric renal failure. Which diagnosis and confirmatory test does the page support?",
     ["Leptospirosis — confirmed by the microscopic agglutination test",
      "Scrub typhus — confirmed by Weil-Felix",
      "Malaria — confirmed by QBC",
      "Dengue — confirmed by NS1 antigen"],
     "The fever pattern page names leptospirosis in a farmer with calf myalgia and conjunctival suffusion; the gold standard here is MAT."),
]

# ---------------------------------------------------------------- p1058
p1058 = [
    ("recall",
     "What is the infectious agent of scrub typhus, as printed?",
     ["Orientia tsutsugamushi", "Rickettsia rickettsii",
      "Leptospira interrogans", "Coxiella burnetii"],
     "'Infectious agent : Orientia tsutsugamushi'."),
    ("match",
     "Disease progression in scrub typhus — match — 1) Renal lesion 2) Immunological phase … A) Micro-infarcts in kidney with ATN and a thrombotic microangiopathic pattern B) No immunological phase",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "'micro infarct in kidney (ATN + Thrombotic microangiopathic pattern)' and 'No immunological phase'."),
    ("recall",
     "What is printed as the characteristic feature of scrub typhus?",
     ["Eschar", "Rose spots", "Koplik spots", "Target lesion"],
     "'Characteristic feature : Eschar'."),
    ("truefalse",
     "Judge the scrub typhus block: I The presentation resembles leptospirosis. II Lymphadenopathy appears at the end of one week.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'· Similar presentation as leptospirosis' and 'Lymphadenopathy at the end of one week'."),
    ("match",
     "Untreated scrub typhus — match the feature to its timing/type — 1) CNS involvement 2) Hearing 3) Eye movements … A) Sensorineural deafness, reversible B) Opsoclonus and myoclonus C) Within one week",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'If untreated → CNS involvement (within one week) : Sensorineural deafness (Reversible), Opsoclonus, myoclonus'."),
    ("numeric",
     "What doxycycline regimen is printed for scrub typhus?",
     ["100 mg BD for 7 days", "100 mg BD for 14 days",
      "200 mg single dose", "500 mg OD for 5 days"],
     "'Doxycycline 100mg BD × 7 days'."),
    ("numeric",
     "What azithromycin regimen is printed as the alternative for scrub typhus?",
     ["500 mg once daily for 5 days", "1 g once daily for 7 days",
      "500 mg BD for 7 days", "250 mg OD for 10 days"],
     "'Azithromycin 500mg OD × 5 days'."),
    ("truefalse",
     "Judge the scrub typhus treatment: I Doxycycline 100 mg twice daily for 7 days. II Azithromycin 500 mg once daily for 5 days is the alternative.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both regimens are printed on the scrap typhus block."),
    ("match",
     "Malaria life cycle — match — 1) Infective form 2) Liver stage 3) Blood stage … A) Pre-erythrocytic schizogony B) Sporozoites C) Erythrocytic schizogony with merozoite release and RBC rupture",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'Sporozoites (Infective form) → Via blood → Liver → Pre-erythrocytic schizogony → Released → merozoites → Rupture RBC's → Erythrocytic schizogony → Fever'."),
    ("recall",
     "What is printed as the infective form in the malaria life cycle?",
     ["Sporozoites", "Merozoites", "Trophozoites", "Gametocytes"],
     "'Sporozoites (Infective form)'."),
    ("recall",
     "Which stage name is given to hepatic schizogony on this page?",
     ["Pre-erythrocytic schizogony", "Exo-erythrocytic schizogony",
      "Cryptozoite stage", "Hypnozoite stage"],
     "'Liver → Pre-erythrocytic schizogony'."),
    ("truefalse",
     "Judge the malaria cycle: I Sporozoites reach the liver through the blood. II Fever coincides with erythrocytic schizogony and RBC rupture.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both statements follow the printed cycle ending in 'Erythrocytic schizogony → Fever'."),
]

# ---------------------------------------------------------------- p1059
p1059 = [
    ("match",
     "Malaria — match the clinical group to its content — 1) Symptoms 2) Signs 3) Complication mechanism … A) Extreme fatigue B) Organ ischaemia C) Tachypnoea, tachycardia, splenomegaly",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'clinical features : · Extreme fatigue'; 'Tachypnea / tachycardia / splenomegaly'; 'complication : Organ ischemia'."),
    ("recall",
     "What mechanism is printed for the complications of falciparum malaria?",
     ["Cyto-adherence, rosetting and agglutination of RBCs", "Immune complex deposition",
      "Direct invasion of endothelium", "Complement-mediated lysis"],
     "'Cyto-adherence, rosetting, agglutination of RBCs'."),
    ("recall",
     "Which organ is printed as the major site of RBC trapping?",
     ["Spleen", "Liver", "Bone marrow", "Lung"],
     "'· major organ involved in trapping RBCs : Spleen'."),
    ("recall",
     "Which investigation is printed for malaria on this page?",
     ["Quantitative buffy coat (QBC)", "Bone marrow examination",
      "Serum lactate", "Stool microscopy"],
     "'Investigation : quantitative buffy coat (QBC)'."),
    ("match",
     "Species characteristics — match — 1) P. falciparum 2) P. vivax 3) P. ovale 4) P. malariae … A) Reticulocytes, up to 2 weeks old B) Reticulocytes C) Older cells D) Younger cells",
     ["1-D, 2-A, 3-B, 4-C", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-A, 4-B", "1-D, 2-C, 3-B, 4-A"],
     "'Red cell preference : Younger cells (falciparum); Reticulocytes and cells up to 2 weeks old (vivax); Reticulocytes (ovale); Older cells (malariae)'."),
    ("numeric",
     "Duration of the erythrocytic cycle printed for P. falciparum and P. vivax?",
     ["48 hours for both", "48 hours and 72 hours", "72 hours for both", "24 hours for both"],
     "'Duration of erythrocytic cycle (Hours) : 48 (falciparum), 48 (vivax), 48 (ovale), 72 (malariae)'."),
    ("numeric",
     "Which species is printed with a 72-hour erythrocytic cycle?",
     ["P. malariae", "P. falciparum", "P. vivax", "P. ovale"],
     "'Duration of erythrocytic cycle (Hours) : … P. malariae 72'."),
    ("match",
     "Pigment colour — match — 1) P. falciparum 2) P. vivax 3) P. ovale 4) P. malariae … A) Yellow-brown B) Dark-brown C) Brown-black D) Black",
     ["1-D, 2-A, 3-B, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     "'Pigment color : Black (falciparum), Yellow-brown (vivax), Dark-brown (ovale), Brown-black (malariae)'."),
    ("match",
     "Relapses — match the species to its ability — 1) P. vivax 2) P. ovale 3) P. falciparum 4) P. malariae … A) Yes B) Yes C) No D) No",
     ["1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-A, 4-B", "1-A, 2-C, 3-B, 4-D", "1-D, 2-A, 3-C, 4-B"],
     "'Ability to cause relapses : No (falciparum), Yes (vivax), Yes (ovale), No (malariae)'."),
    ("match",
     "Uncomplicated versus complicated — match — 1) Uncomplicated 2) Complicated … A) Due to P. falciparum, with anaemia, cerebral malaria, hypoglycaemia, shock, haemoglobinuria and jaundice B) Due to P. falciparum or P. vivax, with fever and chills, fatigue, diaphoresis and mild myalgia",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Uncomplicated malaria : (d/t P. falciparum / P. vivax) — Fever with chills / fatigue / diaphoresis, Tachypnea / tachycardia / splenomegaly, myalgia (Not severe)'; 'Complicated malaria : (d/t P. falciparum) — Anemia, Cerebral malaria, Hypoglycemia, Hypotension/shock, Hemoglobinuria (black water fever), Jaundice'."),
    ("recall",
     "Which colour name is given to the haemoglobinuria of complicated malaria?",
     ["Black water fever", "Red water fever", "Coca-cola urine", "Port-wine urine"],
     "'· Hemoglobinuria (black water fever)'."),
    ("oddoneout",
     "Which is NOT printed among the features of complicated malaria?",
     ["Generalised lymphadenopathy", "Cerebral malaria with convulsions",
      "Hypoglycaemia", "Hypotension and shock"],
     "Printed: anaemia, cerebral malaria (convulsions, seizures), hypoglycaemia, hypotension/shock, haemoglobinuria and jaundice."),
    ("scenario",
     "A patient with falciparum malaria has seizures and hypoglycaemia. Which group and species does the page assign this to?",
     ["Complicated malaria due to P. falciparum",
      "Uncomplicated malaria due to P. vivax",
      "Cerebral toxoplasmosis",
      "Bacterial meningitis"],
     "Cerebral malaria with convulsions, seizures and hypoglycaemia is listed under 'Complicated malaria : (d/t P. falciparum)'."),
]

# ---------------------------------------------------------------- p1060
p1060 = [
    ("match",
     "Microscopy — match — 1) Thick smear 2) Thin smear … A) Not sensitive B) Gold standard with Giemsa staining and light microscopy",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Thick smear : Gold standard, Giemsa staining and light microscopy'; 'Thin smear : Not sensitive'."),
    ("recall",
     "Which stain is printed for the QBC test?",
     ["Acridine orange", "Giemsa", "Leishman", "Ziehl-Neelsen"],
     "'QBC test : · Stain : Acridine orange'."),
    ("numeric",
     "How many QBC tests and at what spacing does the page require before declaring no malaria?",
     ["3 tests, 12 hours apart", "2 tests, 6 hours apart",
      "3 tests, 24 hours apart", "1 test only"],
     "'· 3 QBC tests 12 hours apart → Negative → No malaria'."),
    ("recall",
     "What is printed about the rapid diagnostic test based on HRP2?",
     ["It is not validated", "It is the gold standard",
      "It replaces microscopy", "It detects gametocytes only"],
     "'Rapid diagnostic test : HRP2 (Not validated)'."),
    ("match",
     "Uncomplicated malaria therapy — match — 1) First line 2) Alternatives … A) Artemether 80 mg plus lumefantrine 480 mg, four tablets twice daily for 3 days B) Atovaquone plus proguanil, clindamycin plus mefloquine, doxycycline plus quinine, artesunate plus amodiaquine, artesunate plus mefloquine",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "'Uncomplicated malaria : (oral therapy) · Artemether 80mg + Lumefantrine 480mg (First line) — 4 tablets BD × 3 days', then the listed alternatives."),
    ("numeric",
     "How is the artemether-lumefantrine course printed?",
     ["4 tablets twice daily for 3 days", "1 tablet daily for 14 days",
      "2 tablets three times daily for 7 days", "4 tablets once weekly"],
     "'- 4 tablets BD × 3 days'."),
    ("fillup",
     "Fill up (Complicated malaria): 'Day 1 : 3 doses IV artesunate (120 mg / ______ mg per kg) at 0, 12 and 24 hours.'",
     ["2.4", "1.2", "4.8", "3.6"],
     "'Day 1 : 3 doses I/V Artesunate (120mg / 2.4mg per kg) at 0, 12 and 24 hours'."),
    ("numeric",
     "What artesunate dose is printed for days 2 and 3?",
     ["2.4 mg/kg single dose each day", "1.2 mg/kg twice daily",
      "120 mg twice daily", "4.8 mg/kg single dose"],
     "'Day 2 : 2.4 mg/kg single dose. Day 3 : 2.4 mg/kg single dose'."),
    ("truefalse",
     "Judge the treatment block: I Uncomplicated malaria is treated with oral therapy, artemether-lumefantrine first line. II Complicated malaria is treated with intravenous artesunate for three days.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Uncomplicated malaria : (oral therapy)' with artemether-lumefantrine first line, and 'Complicated : (I/V therapy)' with day 1-3 artesunate."),
    ("scenario",
     "A patient reports fever on day 3 of illness and microscopy is planned. Which smear and stain does the page call the gold standard?",
     ["Thick smear with Giemsa staining and light microscopy",
      "Thin smear with acridine orange",
      "QBC with Giemsa",
      "Rapid diagnostic test for HRP2"],
     "'microscopy (Day 3) : Thick smear : Gold standard, Giemsa staining and light microscopy'; the thin smear is 'Not sensitive'."),
    ("recall",
     "Which combination is printed as atovaquone-based therapy?",
     ["Atovaquone plus proguanil", "Atovaquone plus mefloquine",
      "Atovaquone plus artesunate", "Atovaquone plus doxycycline"],
     "'Atovaquone + Proguanil'."),
    ("oddoneout",
     "Which is NOT printed among the oral options for uncomplicated malaria?",
     ["Artesunate plus sulfadoxine-pyrimethamine",
      "Artesunate plus amodiaquine",
      "Artesunate plus mefloquine",
      "Clindamycin plus mefloquine"],
     "Printed oral options: artemether-lumefantrine, atovaquone-proguanil, clindamycin-mefloquine, doxycycline-quinine, artesunate-amodiaquine and artesunate-mefloquine."),
]

write_part(CH, "p1053a", 1053,
           "Fever in infections: pattern by day, investigations, day-4 empirical therapy", p1053)
write_part(CH, "p1054a", 1054,
           "Salmonellosis: weekly clinical course, salient features, investigations and media", p1054)
write_part(CH, "p1055a", 1055,
           "Typhoid pathogenesis and treatment; dengue incubation, course and symptoms", p1055)
write_part(CH, "p1056a", 1056,
           "Dengue critical phase: capillary leak, monitoring, platelet thresholds, day-wise chart", p1056)
write_part(CH, "p1057a", 1057,
           "Leptospirosis: features, complications, diagnosis and treatment", p1057)
write_part(CH, "p1058a", 1058,
           "Scrub typhus: agent, progression, features and treatment; malaria life cycle", p1058)
write_part(CH, "p1059a", 1059,
           "Malaria: clinical features, complications, species characteristics", p1059)
write_part(CH, "p1060a", 1060,
           "Malaria: diagnosis and treatment of uncomplicated and complicated disease", p1060)

write_units(CH, [
    {"title": "Fever in infections and salmonellosis",
     "sec": "Approach & enteric fever · p1053-1054",
     "guide": "Day-wise approach: patterns of fever (salmonella step-ladder, malaria chills and rigors with fatigue, leptospirosis/scrub typhus with calf myalgia and conjunctival suffusion in a farmer, dengue with high-grade fever, retro-orbital and occipital pain and vomiting); investigations with CBC, QBC every 12 hours and malaria excluded only after three consecutive negatives; on day 4 start doxycycline 100 mg BD plus co-trimoxazole DS BD for leptospirosis and scrub typhus; salmonellosis week 1 step-ladder fever with relative bradycardia and vague abdominal pain, week 3 ileocaecal hyperplasia with perforation/bleeding and encephalopathy; salient features include the chronic-carrier gallstone complication and a 5-20 day incubation; Widal low positivity in weeks 1-2 and 80-100% by week 3, blood culture 90% positive in week 1, MacConkey agar and Wilson-Blair bismuth sulphite agar with jet-black colonies, rose spots.",
     "parts": ["p1053a", "p1054a"]},
    {"title": "Typhoid treatment and dengue",
     "sec": "Enteric therapy & dengue · p1055-1056",
     "guide": "Typhoid pathogenesis: bloodstream to liver, spleen and bone marrow, seeding of gallbladder, biliary system and bowel lymphatics, re-entry causing ileocaecal hyperplasia; uncomplicated therapy co-trimoxazole DS BD 14 days or azithromycin 1 g OD 7 days, complicated therapy ceftriaxone 2 g IV 14 days; dengue incubation 7-10 days, NS1 positive days 1-3 and negative from day 4 when fever subsides and rash appears, falling platelets (not below 50,000) and leucopenia in dengue without warning signs; days 4-7 are the most crucial with bleeding and capillary leak (pleural/pericardial effusion, ascites), monitored by blood pressure with IV fluids, IVC diameter and haematocrit, transfusing platelets below 10,000 or below 20,000 with bleeding, no steroids; febrile, critical and recovery phases with IgM positive from day 5.",
     "parts": ["p1055a", "p1056a"]},
    {"title": "Leptospirosis, scrub typhus and the malaria life cycle",
     "sec": "Spirochete, rickettsia & parasite basics · p1057-1058",
     "guide": "Leptospirosis: abrupt low-to-intermediate fever, calf muscle tenderness, conjunctival congestion and suffusion, 4-7 days as the vital period, hepatorenal syndrome (hepatitis with jaundice plus ATN), non-oliguric AKI with hypokalaemia and hypomagnesaemia, thrombocytopenia, myocarditis with secondary MR/AR, aseptic meningitis, ARDS and rhabdomyolysis; modified Faine's criteria with MAT as gold standard; doxycycline plus ceftriaxone 2 g IV OD. Scrub typhus: Orientia tsutsugamushi, micro-infarcts in kidney with a thrombotic microangiopathic pattern, no immunological phase, eschar, lymphadenopathy at the end of one week, untreated CNS involvement within one week with reversible sensorineural deafness, opsoclonus and myoclonus, treated with doxycycline 100 mg BD 7 days or azithromycin 500 mg OD 5 days. Malaria cycle: sporozoites via blood to liver, pre-erythrocytic schizogony, merozoite release, erythrocytic schizogony and fever.",
     "parts": ["p1057a", "p1058a"]},
    {"title": "Malaria: features, species and treatment",
     "sec": "Malaria · p1059-1060",
     "guide": "Extreme fatigue, tachypnoea/tachycardia/splenomegaly and mild myalgia in uncomplicated disease; complications from cyto-adherence, rosetting and agglutination of RBCs with organ ischaemia and the spleen as the major trapping organ; species table — falciparum (younger cells, 48 h, black pigment, no relapses), vivax (reticulocytes and cells up to 2 weeks old, 48 h, yellow-brown, relapses), ovale (reticulocytes, 48 h, dark-brown, relapses), malariae (older cells, 72 h, brown-black, no relapses); complicated falciparum disease with anaemia, cerebral malaria, hypoglycaemia, shock, black water fever and jaundice; diagnosis by thick smear with Giemsa and light microscopy as gold standard, thin smear not sensitive, QBC with acridine orange and three tests 12 hours apart to exclude malaria, HRP2 rapid test not validated; oral artemether 80 mg plus lumefantrine 480 mg four tablets BD for 3 days first line with atovaquone-proguanil, clindamycin-mefloquine, doxycycline-quinine, artesunate-amodiaquine and artesunate-mefloquine as alternatives; complicated disease IV artesunate 2.4 mg/kg at 0, 12 and 24 hours then daily on days 2 and 3.",
     "parts": ["p1059a", "p1060a"]},
])
