#!/usr/bin/env python3
"""Ch 72 Infective Endocarditis — Book p1047-1052, strict source order."""
from itemwriter_70_74 import write_part, write_units

CH = 72

# ---------------------------------------------------------------- p1047
p1047 = [
    ("fillup",
     "Fill up (Definition): 'Infection of ______ / endocardial surface.'",
     ["valvular", "myocardial", "pericardial", "subcutaneous"],
     "'Infective endocarditis — Infection of valvular / endocardial surface'."),
    ("fillup",
     "Fill up: it involves a native / prosthetic valve or intracardiac device and 'Leads to ______ (Hallmark).'",
     ["vegetations", "pancarditis", "ventricular aneurysm", "pericardial effusion"],
     "'Involving Native / Prosthetic valve, Intracardiac devices → Leads to Vegetations (Hallmark).'"),
    ("recall",
     "What is printed as the hallmark of infective endocarditis?",
     ["Vegetations", "Splinter haemorrhages", "Roth spots", "Osler nodes"],
     "The definition box ends with 'Leads to Vegetations (Hallmark)'."),
    ("match",
     "Risk-factor groups — match — 1) Congenital 2) Rheumatic 3) Degenerative … A) Calcific degenerative aortic stenosis B) Mitral regurgitation, aortic regurgitation C) Ventricular septal defect, atrial septal defect",
     ["1-C, 2-B, 3-A", "1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-A, 3-B"],
     "'Congenital conditions : Ventricular septal defect, Atrial septal defect'; 'Rheumatic conditions : mitral regurgitation, Aortic regurgitation'; 'Degenerative condition : Calcific degenerative aortic stenosis'."),
    ("truefalse",
     "Judge the rheumatic risk note: I Mitral regurgitation and aortic regurgitation carry risk. II Mitral stenosis carries no risk.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Rheumatic conditions : mitral regurgitation, Aortic regurgitation' and '· No risk with mitral stenosis'."),
    ("recall",
     "Which rheumatic lesion is specifically printed as carrying no risk of infective endocarditis?",
     ["Mitral stenosis", "Aortic regurgitation", "Mitral regurgitation", "Aortic stenosis"],
     "'· No risk with mitral stenosis'."),
    ("oddoneout",
     "Which is NOT printed as a risk-factor group on this page?",
     ["Hypertensive heart disease", "Congenital conditions", "Rheumatic conditions", "IV drug abusers"],
     "Printed groups: congenital conditions, rheumatic conditions, degenerative condition (calcific AS) and IV drug abusers."),
    ("match",
     "Sided distribution — match — 1) Left sided 2) Combined 3) Right sided … A) 15% B) 10%, 70% of them due to MRSA C) Most common, aortic valve, with MVP plus MR",
     ["1-C, 2-A, 3-B", "1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A"],
     "'Left sided : AV (m/c), MVP + MR'; 'Combined : 15%'; 'Right sided : 10% (70% due to MRSA), Tricuspid involvement'."),
    ("numeric",
     "What share of right-sided infective endocarditis is attributed to MRSA on this page?",
     ["70%", "10%", "15%", "30%"],
     "'Right sided : 10% (70% due to mRSA)'."),
    ("match",
     "Right-sided disease — match — 1) Valve involved 2) Seen in … A) IV drug abusers, IV central lines B) Tricuspid",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Right sided … Tricuspid involvement. Seen in : IV drugs abusers, IV central lines'."),
    ("recall",
     "Which valve is printed as the most common left-sided valve in infective endocarditis?",
     ["Aortic valve", "Tricuspid valve", "Pulmonary valve", "Mitral valve"],
     "The left-sided column prints 'AV (m/c)'."),
]

# ---------------------------------------------------------------- p1048
p1048 = [
    ("match",
     "Pathogenesis — match — 1) Mucosal injury 2) Valvular endothelial injury 3) Bacterial seeding … A) Platelet-fibrin clot (NBTE) B) Bacterial adherence to NBTE then proliferation C) Bacteraemia",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Mucosal injury → Bacterial seeding'; 'valvular endothelial injury → Platelet fibrin clot (NBTE) → Bacterial adherence to NBTE → Bacterial proliferation → vegetation → Endocarditic features'."),
    ("fillup",
     "Fill up: 'NBTE — Non-bacterial thrombotic endocarditis, ______ endocarditis.'",
     ["marantic", "Libman-Sacks", "rheumatic", "carcinoid"],
     "'Note : Non-bacterial thrombotic endocarditis, marantic endocarditis'."),
    ("truefalse",
     "Judge the NBTE note: I NBTE is the non-bacterial thrombotic (marantic) endocarditis. II It is the platelet-fibrin clot on which bacteria later adhere.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Both statements reproduce the printed NBTE note and its place in the pathogenetic chain."),
    ("recall",
     "Which condition is printed alongside NBTE in the note on non-bacterial thrombotic endocarditis?",
     ["SLE", "Rheumatoid arthritis", "Antiphospholipid-negative APS", "Sarcoidosis"],
     "'NBTE in SLE : Catheter / …' is printed next to the marantic-endocarditis note."),
    ("match",
     "Classification — match — 1) By valve 2) By exposure … A) Intravenous drug abuse, health-care associated B) Native valve, prosthetic valve",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Infective endocarditis : Native valve, Prosthetic valve, Intravenous drug abuse (IVDA), Health care associated'."),
    ("recall",
     "In native-valve endocarditis, which valve does the page print as involved?",
     ["Mitral (left sided)", "Tricuspid", "Pulmonary", "Aortic only"],
     "'· valve involved : mitral (Left sided)'."),
    ("match",
     "Native-valve associations — match — 1) Associated valvular heart disease 2) Congenital heart disease 3) CKD-associated IE … A) Ventricular septal defect B) Tricuspid C) MVP with mitral regurgitation",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Associated valvular heart disease : MVP + mitral regurgitation'; 'Congenital heart disease : Ventricular septal defect'; 'CKD associated IE : Tricuspid'."),
    ("match",
     "Predisposing conditions in native valves — match — 1) Rheumatic heart disease 2) Congenital heart disease 3) Mitral valve prolapse 4) Degenerative heart disease … A) 10-20% B) Rare C) 10-30% D) 25-30%",
     ["1-D, 2-A, 3-C, 4-B", "1-A, 2-D, 3-B, 4-C", "1-D, 2-C, 3-A, 4-B", "1-B, 2-A, 3-C, 4-D"],
     "Printed percentages: rheumatic heart disease 25-30, congenital heart disease 10-20, mitral valve prolapse 10-30, degenerative heart disease Rare."),
    ("numeric",
     "What percentage is printed against parenteral drug abuse in the predisposing-conditions table?",
     ["15 – 35%", "25 – 30%", "10 – 20%", "5 – 10%"],
     "'Parenteral drug abuse : 15-35'."),
    ("numeric",
     "What percentage is printed in the 'None' row of the predisposing-conditions table?",
     ["25 – 45%", "5 – 10%", "15 – 35%", "50 – 60%"],
     "'None : 25-45'."),
    ("match",
     "Organisms — match — 1) Native valve 2) Prosthetic valve under 12 months 3) Prosthetic valve over 12 months 4) IV drug use associated … A) CoNS > MRSA > Gram-negative bacilli B) MRSA C) S. aureus > Streptococcus viridans > enterococci D) Streptococcus viridans > S. aureus > enterococci",
     ["1-C, 2-A, 3-D, 4-B", "1-D, 2-C, 3-A, 4-B", "1-C, 2-D, 3-A, 4-B", "1-B, 2-A, 3-D, 4-C"],
     "'Native valve : S. aureus > Streptococcus viridans > enterococci'; 'Prosthetic valve : < 12 months : CoNS > mRSA > Gram -ve bacilli; > 12 months : Streptococcus viridans > S. aureus > enterococci'; 'IV drug users associated IE : mRSA'."),
    ("recall",
     "Which organism heads the list for prosthetic-valve endocarditis within 12 months of surgery?",
     ["Coagulase-negative staphylococci", "Streptococcus viridans",
      "Enterococci", "Pseudomonas aeruginosa"],
     "'· < 12 months : CoNS > mRSA > Gram -ve bacilli'."),
    ("numeric",
     "What mortality figure is printed for acute infective endocarditis?",
     ["About 60%", "About 6%", "About 16%", "About 90%"],
     "'ACUTE IE : · very high mortality (60%)'."),
    ("match",
     "Acute IE — match — 1) Associated conditions 2) Valve consequence 3) Management … A) Destroyed valves B) Management of sepsis C) Abscess, osteomyelitis → severe sepsis, septic shock (MRSA)",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Associated condition : Abscess, osteomyelitis → Severe sepsis, Septic shock (mRSA)'; 'Destroyed valves'; 'management : of Sepsis'."),
    ("scenario",
     "A patient with acute IE, multiple abscesses and MRSA bacteraemia deteriorates with shock. Which printed pair describes the complication and the management priority?",
     ["Abscess/osteomyelitis with severe sepsis or septic shock — manage the sepsis",
      "Immunological vasculitis with Osler nodes — give steroids",
      "Embolic stroke — thrombolyse immediately",
      "Drug fever — stop all antibiotics"],
     "The acute-IE block prints abscess and osteomyelitis leading to severe sepsis / septic shock with MRSA, and 'management : of Sepsis'."),
]

# ---------------------------------------------------------------- p1049
p1049 = [
    ("recall",
     "Which background is printed at the top of the subacute-IE case?",
     ["Congenital heart disease with rheumatic fever in childhood, treated for RHD",
      "Recent dental extraction in a normal valve",
      "Prosthetic aortic valve replaced last month",
      "Central venous catheter in a patient on chemotherapy"],
     "'H/o : · CHD, + Rheumatic fever in childhood, treatment for RHD.'"),
    ("match",
     "Symptoms versus signs — match — 1) Symptoms 2) Signs … A) New onset or worsening cardiac murmur, macro- and microembolic events, splenomegaly/clubbing B) Fever with chills for 2-3 months, anorexia, weight loss, fatigue, myalgia",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Symptoms : Fever with chills × 2-3 months, Anorexia, weight loss, Fatigue, myalgia'; 'Signs : New onset cardiac murmur / worsening of an existing murmur, macroembolic events, microembolic events, Splenomegaly / clubbing'."),
    ("numeric",
     "How long is the fever printed as lasting in the subacute case?",
     ["2 – 3 months", "2 – 3 weeks", "2 – 3 days", "2 – 3 years"],
     "'Fever with chills × 2-3 months'."),
    ("match",
     "Embolic phenomena — match — 1) Macroembolic 2) Microembolic … A) Petechiae and splinter haemorrhage B) Stroke, ACS, retinal occlusion",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'macroembolic events : stroke, ACS, retinal occlusion'; 'microembolic events : Petechiae and splinter hemorrhage'."),
    ("match",
     "Immunological manifestations — match — 1) Osler nodes 2) Roth spots 3) Positive rheumatoid factor … A) Retinal endothelial vasculitis with a pale centre and surrounding erythema B) Tender nodules of the finger and toe pulps C) Positive in about half of cases",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'manifestation a/w vasculitis : · Osler nodes, RF positivity, Roth spots : Retinal endothelial vasculitis — Pale centre with surrounding erythema'; 'Rheumatoid factor +ve (50% cases)'."),
    ("numeric",
     "In what proportion of cases is rheumatoid factor positive in subacute IE?",
     ["50% of cases", "10% of cases", "90% of cases", "5% of cases"],
     "'Rheumatoid factor +ve (50% cases)'."),
    ("numeric",
     "Proteinuria and microscopic haematuria are printed in what proportion of cases?",
     ["50% of cases", "25% of cases", "95% of cases", "5% of cases"],
     "'· Proteinuria and microscopic hematuria (50% cases)'."),
    ("match",
     "Laboratory features — match — 1) Anaemia 2) White cells 3) Acute phase … A) Raised ESR and CRP B) Normocytic C) Raised count",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     "'Laboratory features : · Anemia (Normocytic), · ↑ WBC, · ↑ ESR, · CRP'."),
    ("match",
     "Janeway lesions versus Osler nodes — match — 1) Site 2) Size and shape 3) Tenderness 4) Course 5) Type of endocarditis 6) Culture 7) Histology … A) Nodules 1 mm to > 1 cm; tender; hours to days; subacute; usually negative; vasculitis B) Macules of variable size and irregular shape; non-tender; days to weeks; acute; usually positive; septic microemboli",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Janeway: soles, palms, thenar and hypothenar eminences and plantar surfaces of the toes; macules of variable size and irregular shape; not tender; days to weeks; acute; culture positive; septic microemboli. Osler: finger and toe tips, pulp, thenar and hypothenar eminences; nodules 1 mm to > 1 cm; tender; hours to days; subacute; culture negative; vasculitis."),
    ("recall",
     "Where are Janeway lesions printed as occurring?",
     ["Soles, palms, thenar and hypothenar eminences, plantar surfaces of the toes",
      "Finger and toe tips and pulps only",
      "Buttocks and trunk",
      "Conjunctivae and hard palate"],
     "'Janeway lesion — Soles, palms, thenar and hypothenar eminences, plantar surfaces of the toe'."),
    ("recall",
     "What size range is printed for Osler nodes?",
     ["1 mm to more than 1 cm", "1 mm to 2 mm", "Pinpoint only", "More than 5 cm"],
     "'Osler node — Nodules of 1 mm to > 1 cm'."),
    ("truefalse",
     "Judge the comparison table: I Janeway lesions are non-tender macules of acute endocarditis with positive cultures. II Osler nodes are tender nodules of subacute endocarditis with negative cultures.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Janeway column: macules, non-tender, days to weeks, acute, culture positive, septic microemboli. Osler column: nodules, tender, hours to days, subacute, culture negative, vasculitis."),
    ("scenario",
     "A febrile patient with a murmur has tender nodules on the finger pulps and a negative blood culture. Which lesion and endocarditis type does the table indicate?",
     ["Osler node — subacute endocarditis", "Janeway lesion — acute endocarditis",
      "Roth spot — subacute endocarditis", "Splinter haemorrhage — acute endocarditis"],
     "Tender nodules of the pulps with negative cultures are the Osler-node column, linked to subacute endocarditis."),
]

# ---------------------------------------------------------------- p1050
p1050 = [
    ("match",
     "Causes listed for the immune/vasculitic picture — match — 1) Low C3 and C4 2) Others … A) Hepatitis C virus, cryoglobulinaemia, leprosy B) Infective endocarditis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Causes : · IE (↓C3, ↓C4), · Hep C Virus, · Cryoglobulinemia, · Leprosy'."),
    ("match",
     "Cardiac complications — match — 1) Stroke / ACS 2) Heart failure 3) Perivalvular abscess … A) Due to valvular insufficiency with new-onset adult AR / MR B) Common in aortic position, causes conduction block C) Fragment embolisation into coronaries",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Stroke / ACS : Fragment embolization into coronaries'; 'Heart failure : d/t Valvular insufficiency, New onset adult AR/MR'; 'Perivalvular abscess : (Common in aorta) → Conduction block'."),
    ("match",
     "Non-cardiac complications — match the group — 1) Embolic 2) Immunological 3) Septic … A) Metastatic infection, mycotic aneurysm B) Embolic occlusion C) Immunological phenomena",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     "'Non-cardiac complications : · Embolic occlusion, · Immunological, · metastatic infection, · mycotic aneurysm'."),
    ("match",
     "Right-sided IE complications — match — 1) Pulmonary 2) Cardiac 3) Vascular … A) Right heart failure B) Pulmonary abscess, empyema C) Mycotic aneurysm of pulmonary artery",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     "'Right-sided IE complications : · Pulmonary abscess, Empyema, · Right heart failure, · mycotic aneurysm of pulmonary artery'."),
    ("recall",
     "Which organism group is printed as a cause of perivalvular abscess with conduction block?",
     ["Perivalvular abscess is common in the aortic position", "It is common in the tricuspid position",
      "It is common in the pulmonary position", "It is common in the mitral position"],
     "'Perivalvular abscess : (Common in aorto) → Conduction block'."),
    ("match",
     "Modified Duke criteria — match the combinations — 1) Definite by majors 2) Major plus minors 3) Minors only … A) 1 major + 3 minor B) 5 minor C) 2 major",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Criterias : 2 major OR 1 major + 3 minor OR 5 minor'."),
    ("numeric",
     "How many minor criteria are required to satisfy the modified Duke criteria on their own?",
     ["5 minor", "3 minor", "2 minor", "4 minor"],
     "'OR 5 minor'."),
    ("fillup",
     "Fill up (Blood-culture technique): '______ sets (______ ml each) from 3 sites.'",
     ["3; 20", "2; 10", "3; 10", "5; 30"],
     "'Blood culture : · 3 sets (20 ml each) from 3 sites'."),
    ("match",
     "Blood-culture volumes and timing — match — 1) Per bottle 2) Interval between sets 3) Repeat interval … A) 30-60 minutes B) 18-24 hours C) 10 ml aerobic plus 10 ml anaerobic",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Blood (10 ml aerobic + 10 ml anaerobic) taken over 30-60 minutes'; 'Culture to be repeated every 18-24 hours'."),
    ("recall",
     "How does the page define a positive blood-culture major criterion for typical organisms?",
     ["Typical organism (MRSA, Streptococcus viridans) from two separate cultures",
      "Any single culture growing a skin commensal",
      "Three cultures drawn from one venipuncture",
      "A positive serology alone"],
     "'Positive culture : Typical organism (mRSA, Strep. viridans) from 2 separate cultures'."),
    ("recall",
     "Which organisms are named as needing only a single positive culture or antibody detection?",
     ["HACEK group and Coxiella burnetii", "Enterococci and Listeria",
      "S. aureus and CoNS", "Candida and Aspergillus"],
     "'HACeK group (Coxiella burnetii) single positive culture or antibodies detected'."),
    ("truefalse",
     "Judge the major criteria: I Three sets of 20 ml from three sites are required. II Persistently positive cultures also count as a major criterion.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'3 sets (20 ml each) from 3 sites' and 'Persistently positive culture' are both printed."),
]

# ---------------------------------------------------------------- p1051
p1051 = [
    ("match",
     "Minor criteria — match the number to the item — 1) 2 2) 3 3) 4 4) 5 … A) Immunological phenomenon B) Fever C) Vascular phenomenon (emboli) D) Microbiological evidence not meeting culture criteria",
     ["2-B, 3-C, 4-A, 5-D", "2-A, 3-B, 4-C, 5-D", "2-B, 3-A, 4-C, 5-D", "2-D, 3-C, 4-A, 5-B"],
     "'minor criteria : 1. Predisposition to IE, 2. Fever, 3. vascular phenomenon (Emboli), 4. Immunological phenomenon, 5. microbiological phenomenon not meeting culture criteria'."),
    ("recall",
     "Which minor criterion is listed first on this page?",
     ["Predisposition to IE", "Fever", "Vascular phenomenon", "Immunological phenomenon"],
     "'1. Predisposition to IE'."),
    ("match",
     "Echocardiography — match the modality to the printed accuracy — 1) TTE 2) TEE … A) Sensitivity 86-98%, specificity 98% B) Sensitivity 50-70%, specificity 86%",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'TTE (Transthoracic echocardiography) : Sensitivity 50-70, Specificity 86'; 'TEE (Transesophageal echocardiography) : sensitivity 86-98, specificity 98'."),
    ("numeric",
     "What sensitivity is printed for transthoracic echocardiography?",
     ["50 – 70%", "86 – 98%", "86%", "98%"],
     "TTE row: 'Sensitivity 50-70'."),
    ("recall",
     "Which route does the page print for suspected endocarditis with a prosthetic valve or intracardiac device?",
     ["TEE", "TTE", "No imaging is needed", "Chest radiograph"],
     "'Suspected endocarditis : Native valve → TTE; Prosthetic valve / Intracardiac devices → TEE'."),
    ("match",
     "Echo algorithm — match the result to the action — 1) Positive 2) Negative … A) Observe, repeat echo if required B) Rx for endocarditis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Positive → Rx for endocarditis'; 'Negative → Observe, repeat ECHO if required'."),
    ("recall",
     "When should TEE be added even if TTE has been done, according to this page?",
     ["When complications are suspected", "In every native-valve case",
      "Only if blood cultures are positive", "Only after surgery"],
     "'TEE if complications suspected'."),
    ("match",
     "TEE indications over TTE — match — 1) Vegetation size 2) Structural complications 3) Devices … A) Myocardial abscess, valve perforation, intracardiac fistula B) CIED (cardiovascular implantable electronic device), prosthetic valve C) Vegetations below 2 mm",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'TEE indications over TTE : · vegetations < 2 mm, · myocardial abscess, valve perforation, · Prosthetic valve, · CIED (Cardiovascular implantable electronic device), · Intracardiac fistula'."),
    ("oddoneout",
     "Which is NOT printed as a TEE indication over TTE?",
     ["Uncomplicated native-valve fever with a normal TTE", "Vegetations under 2 mm",
      "Myocardial abscess", "CIED lead infection"],
     "Printed indications: vegetations < 2 mm, myocardial abscess, valve perforation, prosthetic valve, CIED and intracardiac fistula."),
]

# ---------------------------------------------------------------- p1052
p1052 = [
    ("match",
     "Streptococcus viridans regimen — match — 1) DOC 2) Alternative 3) If penicillin resistant … A) Ceftriaxone 2 g IV once daily or vancomycin 15 mg/kg IV BD B) Vancomycin 15 mg/kg IV BD C) Penicillin G 2-3 million units IV every 4 hours for 4 weeks",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Streptococcus viridans : DOC : Penicillin G 2-3 million units IV Q4h × 4 wks. Ceftriaxone 2g IV OD × 4 wks OR Vancomycin 15 mg/kg IV BD (if Penicillin resistant : vancomycin 15 mg/kg IV BD × 4-6 wks)'."),
    ("match",
     "Enterococcal regimen — match — 1) Base drug 2) Synergy 3) Penicillin-resistant option … A) Gentamicin 1 mg/kg IV TDS B) Penicillin G 4-5 million units Q4h × 4-6 wks C) Vancomycin 15 mg/kg IV BD × 4-6 wks",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'Enterococci : Penicillin G 4-5 million units Q4h × 4-6 wks; Gentamicin (1 mg/kg IV TDS); (if Penicillin resistant : vancomycin 15 mg/kg IV BD × 4-6 wks)'."),
    ("recall",
     "Which organisms are printed as intrinsically resistant to cephalosporins?",
     ["Enterococci and Listeria", "Staphylococci and streptococci",
      "HACEK organisms", "Coxiella burnetii"],
     "'Note : Intrinsically resistant to cephalosporins · Enterococci, · Listeria'."),
    ("match",
     "MRSA endocarditis — match — 1) Native valve 2) Prosthetic valve … A) Vancomycin 15 mg/kg IV BD plus gentamicin 1 mg/kg IV BD plus rifampicin 300 mg orally TID for 6-8 weeks B) Vancomycin 15 mg/kg IV BD",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Native valve : vancomycin 15 mg/kg IV BD × 4-6 wks'; 'Prosthetic valve : Vancomycin 15 mg/kg IV BD + Gentamicin 1 mg/kg IV BD + Rifampicin 300 mg oral TID × 6-8 wks'."),
    ("numeric",
     "Dose and duration printed for rifampicin in prosthetic-valve MRSA endocarditis?",
     ["300 mg orally three times a day for 6 – 8 weeks", "600 mg once daily for 2 weeks",
      "300 mg twice daily for 4 weeks", "10 mg/kg IV daily for 6 weeks"],
     "'Rifampicin 300 mg oral TID × 6-8 wks'."),
    ("match",
     "Culture-negative endocarditis — match — 1) Culture report negative 2) True culture negative … A) Rare condition, no prior antibiotics, treated with vancomycin plus gentamicin for 4-6 weeks B) Common condition, prior antibiotics, sterile cultures, treated with ceftriaxone plus gentamicin",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Culture report negative : m/c condition, H/o treatment medication (antibiotics), Culture sterile, Ceftriaxone + Gentamicin'; 'Culture negative : Rare condition, No Rx, Vancomycin + Gentamicin × 4-6 wks'."),
    ("recall",
     "Which regimen is printed for true culture-negative endocarditis?",
     ["Vancomycin plus gentamicin for 4 – 6 weeks", "Ceftriaxone plus gentamicin",
      "Amoxicillin alone", "Doxycycline plus cotrimoxazole"],
     "'Culture negative … Vancomycin + Gentamicin × 4-6 wks'."),
    ("match",
     "Indications for surgery — match — 1) Native valve 2) Prosthetic valve … A) Dehiscence, increasing obstruction/regurgitation, heart failure B) Acute valvular regurgitation, fungal endocarditis, perivalvular aortic abscess",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Native valve : · Acute valvular regurgitation, · Fungal endocarditis, · Perivalvular aortic abscess'; 'Prosthetic valve : · Dehiscence, · Increasing obstruction/regurgitation, · Heart failure'."),
    ("recall",
     "Which infection is listed as a native-valve indication for surgery?",
     ["Fungal endocarditis", "Enterococcal endocarditis",
      "HACEK endocarditis", "Coxiella endocarditis"],
     "'Native valve : … · Fungal endocarditis'."),
    ("match",
     "Prophylaxis — who gets it? — match — 1) Valves 2) Congenital disease 3) Other … A) Unrepaired CHD, repaired CHD within 6 months B) Prosthetic valve, previous episode of IE C) Post cardiac transplant",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     "'Indications : · People with prosthetic valve, · Previous episode of IE, · Post cardiac transplant, · Unrepaired CHD, Repaired CHD (within 6 months)'."),
    ("recall",
     "For how long after repair is CHD still an indication for prophylaxis?",
     ["Within 6 months of repair", "Within 6 weeks of repair",
      "Within 6 years of repair", "Lifelong after repair"],
     "'Repaired CHD (within 6 months)'."),
    ("match",
     "Procedures needing prophylaxis — match — 1) Dental 2) Respiratory tract … A) Dental procedure B) Adenoidectomy, tonsillectomy, incision and drainage of respiratory mucosa",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "'Pre-procedural prophylaxis : Dental procedure; Invasive procedures of respiratory tract : Adenoidectomy, Tonsillectomy, Incision/drainage of respiratory mucosa'."),
    ("fillup",
     "Fill up (Regimen): 'Amoxicillin ______ orally, given ______ before the procedure.'",
     ["2 g; 30 – 60 minutes", "500 mg; 12 hours", "1 g; 2 hours", "2 g; 7 days"],
     "'· Amoxicillin 2g oral : 30-60 min before procedure'."),
    ("match",
     "Penicillin-allergy and parenteral options — match — 1) Oral allergy options 2) Unable to take orally 3) Allergy and unable to take orally … A) Ampicillin 2 g IV or ceftriaxone 1 g IV/IM B) Clindamycin 600 mg IV C) Azithromycin 500 mg, cephalexin 2 g or clindamycin 600 mg",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'In penicillin allergy : Azithromycin 500 mg, Cephalexin 2g, Clindamycin 600 mg'; 'unable to take orally : Ampicillin 2g IV / ceftriaxone 1g IV or IM'; 'In penicillin allergy : Clindamycin 600 mg IV'."),
    ("numeric",
     "Dose of clindamycin printed for prophylaxis in penicillin allergy?",
     ["600 mg", "60 mg", "300 mg", "900 mg"],
     "'Clindamycin 600 mg' (oral) and 'Clindamycin 600 mg IV'."),
    ("scenario",
     "A patient with a prosthetic valve and penicillin allergy cannot swallow tablets before a dental extraction. Which printed regimen applies?",
     ["Clindamycin 600 mg IV", "Amoxicillin 2 g orally",
      "Azithromycin 500 mg orally", "Ampicillin 2 g IV"],
     "Penicillin allergy plus inability to take orally: 'In penicillin allergy : Clindamycin 600 mg IV'."),
]

write_part(CH, "p1047a", 1047,
           "Definition, hallmark, risk factors, sided distribution of infective endocarditis", p1047)
write_part(CH, "p1048a", 1048,
           "Pathogenesis, NBTE, classification, predisposing conditions, organisms, acute IE", p1048)
write_part(CH, "p1049a", 1049,
           "Subacute IE: symptoms, signs, emboli, laboratory features, Janeway vs Osler", p1049)
write_part(CH, "p1050a", 1050,
           "Causes of the immune picture, complications, modified Duke major criteria", p1050)
write_part(CH, "p1051a", 1051,
           "Minor criteria, echocardiography, TTE vs TEE, TEE indications", p1051)
write_part(CH, "p1052a", 1052,
           "Treatment regimens, culture-negative disease, surgery, prophylaxis", p1052)

write_units(CH, [
    {"title": "Definition, risk factors and sided distribution",
     "sec": "Basics · p1047",
     "guide": "Infection of the valvular/endocardial surface involving native or prosthetic valves and intracardiac devices, leading to vegetations (the hallmark); risk factors: congenital (VSD, ASD), rheumatic (mitral and aortic regurgitation, no risk with mitral stenosis), degenerative calcific aortic stenosis and IV drug abuse; distribution: left sided most common (aortic valve, MVP with MR), combined 15%, right sided 10% of which 70% is MRSA, tricuspid, seen in IV drug abusers and IV central lines.",
     "parts": ["p1047a"]},
    {"title": "Pathogenesis, classification and organisms",
     "sec": "Mechanism · p1048",
     "guide": "Mucosal injury → bacterial seeding; valvular endothelial injury → platelet-fibrin clot = NBTE (non-bacterial thrombotic, marantic endocarditis, also seen in SLE with catheters) → bacterial adherence → proliferation → vegetation → endocarditic features; classified as native valve, prosthetic valve, IVDA and health-care associated; native valve most often mitral (left sided), with MVP + MR, VSD and CKD-associated tricuspid disease; predisposing conditions with percentages: rheumatic 25-30, congenital 10-20, MVP 10-30, degenerative rare, parenteral drug abuse 15-35, none 25-45; organisms: native valve S. aureus > Strep. viridans > enterococci; prosthetic < 12 months CoNS > MRSA > Gram-negative bacilli; > 12 months Strep. viridans > S. aureus > enterococci; IV drug use MRSA; acute IE has about 60% mortality with abscess, osteomyelitis, severe sepsis and destroyed valves, managed as sepsis.",
     "parts": ["p1048a"]},
    {"title": "Subacute infective endocarditis",
     "sec": "Clinical · p1049",
     "guide": "Background of congenital heart disease with childhood rheumatic fever treated as RHD; symptoms: fever with chills for 2-3 months, anorexia, weight loss, fatigue, myalgia; signs: new or worsening murmur, macroembolic events (stroke, ACS, retinal occlusion), microembolic events (petechiae, splinter haemorrhages), splenomegaly/clubbing, arterial embolisation; vasculitic manifestations: Osler nodes, rheumatoid factor, Roth spots (retinal endothelial vasculitis, pale centre with surrounding erythema); laboratory: normocytic anaemia, raised WBC, ESR and CRP, rheumatoid factor positive in 50% and proteinuria with microscopic haematuria in 50%; Janeway lesions (soles, palms, thenar/hypothenar, plantar toes; variable irregular macules; non-tender; days-weeks; acute; culture positive; septic microemboli) versus Osler nodes (finger/toe tips and pulps; 1 mm to >1 cm nodules; tender; hours-days; subacute; culture negative; vasculitis).",
     "parts": ["p1049a"]},
    {"title": "Complications and the modified Duke criteria",
     "sec": "Complications & diagnosis · p1050",
     "guide": "Causes of the immune complex picture: IE with low C3 and C4, hepatitis C, cryoglobulinaemia and leprosy; cardiac complications: stroke/ACS from fragment embolisation into coronaries, heart failure from valvular insufficiency with new adult AR/MR, perivalvular abscess (common in the aortic position) causing conduction block; non-cardiac: embolic occlusion, immunological, metastatic infection and mycotic aneurysm; right-sided IE: pulmonary abscess, empyema, right heart failure and mycotic aneurysm of the pulmonary artery; modified Duke criteria: 2 major, or 1 major plus 3 minor, or 5 minor; major blood-culture criteria: 3 sets of 20 ml from 3 sites, 10 ml aerobic plus 10 ml anaerobic per bottle taken over 30-60 minutes and repeated every 18-24 hours, with typical organisms (MRSA, Strep. viridans) from two separate cultures, persistently positive cultures, or a single positive culture/antibodies for HACEK group or Coxiella burnetii.",
     "parts": ["p1050a"]},
    {"title": "Minor criteria and echocardiography",
     "sec": "Imaging · p1051",
     "guide": "Minor criteria: predisposition, fever, vascular phenomenon (emboli), immunological phenomenon and microbiological evidence not meeting culture criteria; TTE sensitivity 50-70% with 86% specificity, TEE sensitivity 86-98% with 98% specificity; suspected endocarditis with a native valve goes to TTE while prosthetic valves and intracardiac devices go to TEE; positive echo means treat for endocarditis, negative means observe and repeat echo if required, TEE is added when complications are suspected; TEE is preferred over TTE for vegetations under 2 mm, myocardial abscess, valve perforation, prosthetic valve, CIED and intracardiac fistula.",
     "parts": ["p1051a"]},
    {"title": "Treatment, surgery and prophylaxis",
     "sec": "Management · p1052",
     "guide": "Strep. viridans: penicillin G 2-3 million units IV q4h for 4 weeks, else ceftriaxone 2 g IV daily or vancomycin 15 mg/kg IV BD, with vancomycin 15 mg/kg IV BD for 4-6 weeks if penicillin resistant; enterococci: penicillin G 4-5 million units q4h for 4-6 weeks with gentamicin 1 mg/kg IV TDS, vancomycin 15 mg/kg IV BD if penicillin resistant; enterococci and Listeria are intrinsically resistant to cephalosporins; MRSA: vancomycin 15 mg/kg IV BD for 4-6 weeks in native valves, plus gentamicin 1 mg/kg IV BD and rifampicin 300 mg oral TID for 6-8 weeks in prosthetic valves; culture-report-negative disease is common, follows antibiotics and is treated with ceftriaxone plus gentamicin, whereas true culture-negative disease is rare, follows no antibiotics and is treated with vancomycin plus gentamicin for 4-6 weeks; surgery for native valves with acute regurgitation, fungal endocarditis or perivalvular aortic abscess and for prosthetic valves with dehiscence, increasing obstruction/regurgitation or heart failure; prophylaxis for prosthetic valves, previous IE, post-cardiac transplant, unrepaired CHD and repaired CHD within 6 months, before dental procedures and invasive respiratory-tract procedures (adenoidectomy, tonsillectomy, incision and drainage of respiratory mucosa), with amoxicillin 2 g orally 30-60 minutes before, azithromycin 500 mg, cephalexin 2 g or clindamycin 600 mg in penicillin allergy, ampicillin 2 g IV or ceftriaxone 1 g IV/IM if unable to take orally, and clindamycin 600 mg IV for allergy plus parenteral need.",
     "parts": ["p1052a"]},
])
