#!/usr/bin/env python3
"""Ch 74 HIV — Book p1061-1068, strict source order."""
from itemwriter_70_74 import write_part, write_units

CH = 74

# ---------------------------------------------------------------- p1061
p1061 = [
    ("numeric",
     "In which year is the first reported case of HIV printed?",
     ["1981", "1971", "1991", "1986"],
     "'History : · First reported case : 1981'."),
    ("recall",
     "What is printed about the origin of the first reported case?",
     ["It was reported from an African patient", "It was reported from an American infant",
      "It was reported from a European blood donor", "It was reported from an Asian traveller"],
     "'from an African patient'."),
    ("recall",
     "Which old name for the virus is printed on this page?",
     ["Lymphadenopathy Associated Virus (LAV)", "Human T-lymphotropic virus",
      "Cytomegalic inclusion virus", "African lymphoma virus"],
     "'Lymphadenopathy Associated Virus (LAV)'."),
    ("match",
     "CDC staging — match the stage to the CD4 count — 1) Stage 1 2) Stage 2 3) Stage 3 … A) 200-499 cells/mm³ B) below 200 cells/mm³ C) 500 or more cells/mm³",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Stage 1 : ≥500 cells/mm³'; 'Stage 2 : 200-499 cells/mm³'; 'Stage 3 : <200 cells/mm³'."),
    ("numeric",
     "Which CD4 percentage is printed for stage 2 disease?",
     ["14 – 28%", "Below 14%", "Above 28%", "40 – 50%"],
     "Stage 2 prints a CD4 percentage of 14-28."),
    ("numeric",
     "Which CD4 percentage is printed for stage 3 disease?",
     ["Below 14%", "14 – 28%", "Above 26%", "Above 40%"],
     "Stage 3 prints a CD4 percentage below 14."),
    ("match",
     "CDC stages — match the stage to its clinical evidence — 1) Stage 0 2) Stage 1 and 2 3) Stage 3 … A) No AIDS-defining condition B) Documentation of AIDS-defining conditions C) Early HIV infection",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Stage 0 : Early HIV infection'; stages 1 and 2 print 'No AIDS-defining condition'; stage 3 prints 'Documentation of AIDS-defining conditions'."),
    ("match",
     "AIDS-defining malignancies — match — 1) Lymphomas 2) Others … A) Invasive cervical cancer and Kaposi's sarcoma B) Burkitt's lymphoma, immunoblastic lymphoma (EBV mediated), primary CNS lymphoma",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'1. malignancies : · Lymphomas : Burkitt's lymphoma, Immunoblastic lymphoma (EBV mediated), Primary CNS lymphoma; · Invasive cervical cancer; · Kaposi's sarcoma'."),
    ("recall",
     "How is the EBV relationship printed among the AIDS-defining lymphomas?",
     ["Immunoblastic lymphoma is EBV mediated", "Burkitt's lymphoma is EBV mediated",
      "Primary CNS lymphoma is EBV mediated", "No lymphoma is linked to EBV"],
     "'Immunoblastic lymphoma — EBV mediated'."),
    ("match",
     "AIDS-defining viral infections — match the virus to the lesion — 1) CMV 2) HSV 3) JC virus … A) Progressive multifocal leukoencephalopathy B) Disease other than liver, spleen and lymph node involvement C) Disease other than zoster",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     "'2. Viral infections : · Cytomegalovirus (other than liver, spleen and lymph node involvement); · Herpes simplex (except zoster); JC virus : Progressive multifocal leukoencephalopathy'."),
    ("recall",
     "Which JC-virus disease is listed as AIDS defining?",
     ["Progressive multifocal leukoencephalopathy", "Posterior reversible encephalopathy",
      "Subacute sclerosing panencephalitis", "Acute disseminated encephalomyelitis"],
     "'JC virus : Progressive multifocal leukoencephalopathy'."),
    ("match",
     "AIDS-defining fungal infections — match — 1) Candidiasis 2) Cryptococcosis 3) Pneumocystis … A) Extrapulmonary disease B) Pneumocystis jirovecii C) Bronchi, trachea, lungs or oesophagus",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'3. Fungal infections : · Candidiasis of bronchi/trachea/lungs/oesophagus; · Cryptococcosis (extrapulmonary); Pneumocystis jirovecii'."),
    ("oddoneout",
     "Which is NOT printed among the AIDS-defining infections on this page?",
     ["Oral hairy leukoplakia", "Cytomegalovirus disease outside liver, spleen and nodes",
      "Extrapulmonary cryptococcosis", "Oesophageal candidiasis"],
     "Oral hairy leukoplakia is a category B condition; the AIDS-defining list has CMV, HSV, JC virus, candidiasis of bronchi/trachea/lungs/oesophagus, cryptococcosis and Pneumocystis."),
    ("scenario",
     "A patient with HIV has a CD4 count of 150 cells/mm³ and oesophageal candidiasis. Which CDC stage and category does the page support?",
     ["Stage 3 (below 200 cells/mm³) with an AIDS-defining condition",
      "Stage 1, because candidiasis is not AIDS defining",
      "Stage 2, because the count is above 100",
      "Stage 0, early HIV infection"],
     "CD4 below 200 with documentation of an AIDS-defining condition is stage 3; oesophageal candidiasis is on the AIDS-defining fungal list."),
]

# ---------------------------------------------------------------- p1062
p1062 = [
    ("recall",
     "Which parasitic disease is printed as AIDS defining?",
     ["Toxoplasmosis of brain", "Cerebral malaria",
      "Visceral leishmaniasis", "Neurocysticercosis"],
     "'4. Parasites : Toxoplasmosis of brain'."),
    ("match",
     "AIDS-defining bacterial infections — match — 1) Mycobacteria 2) Salmonella … A) Salmonella septicemia B) Mycobacterium avium complex and Mycobacterium tuberculosis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'5. Bacterial infections : mycobacterium avium complex, mycobacterium tuberculosis, · Salmonella septicemia'."),
    ("recall",
     "How does the page label the category B conditions?",
     ["Not AIDS-defining illness", "AIDS-defining illness",
      "Opportunistic but not HIV related", "Irrelevant to staging"],
     "'CATEGORY B : Not AIDS defining illness'."),
    ("match",
     "Category B — match the site to the candidiasis — 1) Vulvovaginal 2) Oropharyngeal … A) Thrush B) Vulvovaginal candidiasis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'· vulvovaginal candidiasis' and 'Oropharyngeal candidiasis (Thrush)'."),
    ("numeric",
     "How does the page define the constitutional category B criterion?",
     ["Fever above 38.5 °C or diarrhoea lasting more than 1 month",
      "Fever above 38 °C for more than 1 week",
      "Diarrhoea for more than 1 week",
      "Weight loss of more than 5 kg"],
     "'· Fever (>38.5°C) or diarrhea lasting >1 month'."),
    ("match",
     "Category B — match the condition to its group — 1) Haematological 2) Neurological 3) Mucosal … A) Idiopathic thrombocytopenic purpura B) Peripheral neuropathy C) Hairy leukoplakia",
     ["1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-A, 3-B", "1-A, 2-C, 3-B"],
     "'· Idiopathic thrombocytopenic purpura', '· Peripheral neuropathy' and '· Hairy leukoplakia' are all category B items."),
    ("oddoneout",
     "Which is NOT printed as a category B condition?",
     ["Kaposi's sarcoma", "Herpes zoster (shingles)",
      "Pelvic inflammatory disease", "Cervical dysplasia / carcinoma in situ"],
     "Kaposi's sarcoma is an AIDS-defining malignancy; the others are category B."),
    ("numeric",
     "When was the first HIV case in India detected, and where?",
     ["1986, Chennai", "1981, Mumbai", "1991, Delhi", "1986, Kolkata"],
     "'HIV in India : First case detected (Chennai) : 1986'."),
    ("recall",
     "Which retroviral genus is printed for HTLV-1 on this page?",
     ["Delta virus", "Lentivirus", "Spumavirus", "Oncovirus"],
     "'Delta virus : HTLV-1' with adult T-cell lymphoma/leukemia and tropical spastic paraparesis."),
    ("match",
     "HTLV-1 associations — match — 1) Malignancy 2) Neurological … A) Adult T-cell lymphoma / leukemia B) Tropical spastic paraparesis",
     ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
     "'Delta virus : HTLV-1 · Adult T-cell lymphoma/leukemia, · Tropical spastic paraparesis'."),
    ("match",
     "Lentiviruses — match — 1) HIV-1 2) HIV-2 … A) Less virulent, West African virus of the simian viridae family B) The main agent with groups and subtypes",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Lentivirus : · HIV-1, · HIV-2 : Less virulent, · Simian viridae family, West African virus'."),
    ("match",
     "Viral structure — match the component to its label — 1) Envelope 2) Enzymes 3) Capsid … A) Reverse transcriptase, integrase and protease B) gp120 and gp41 C) p17 matrix protein and p24 core protein",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'Envelope : gp120, gp41'; 'Transcriptase (reverse), Integrase, Protease'; 'Capsid : Protein p17, p24'."),
    ("recall",
     "Which HIV-1 subtype is printed as the most common?",
     ["Subtype C", "Subtype B", "Subtype A", "Subtype D"],
     "'Subtypes … m/c : C'."),
    ("recall",
     "Which HIV-1 subtype is printed as spreading through blood and among homosexuals?",
     ["Subtype B", "Subtype C", "Subtype A", "Subtype E"],
     "'→ B : Spread through blood, homosexuals'."),
]

# ---------------------------------------------------------------- p1063
p1063 = [
    ("fillup",
     "Fill up: the HIV genome is printed as '______ copies of ssRNA'.",
     ["2", "1", "4", "10"],
     "'2 Copies of ssRNA'."),
    ("match",
     "Structural genes — match the gene to its product — 1) env 2) pol 3) gag … A) Reverse transcriptase, integrase and protease B) p17 matrix protein and p24 core protein C) gp120 spike protein and gp41 transmembrane pedicle protein",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'Env : codes gp120 (Spike protein), gp41 (Transmembrane pedicle protein); POL : codes Enzymes : Reverse transcriptase, Integrase, Protease; GAG : codes P17 (matrix protein), P24 (Core protein / nucleocapsid protein)'."),
    ("match",
     "Non-structural genes — match — 1) Nef 2) Vif 3) Rev 4) Tat … A) Viral infectivity factor B) Regulation of viral expression C) Transcription activator D) Negative effector, downregulates host CD4 cells",
     ["1-D, 2-A, 3-B, 4-C", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-A, 4-B", "1-D, 2-C, 3-A, 4-B"],
     "'· Nef/P : Negative effector → Downregulates host CD4 cells; · vif : Viral infectivity factor; Rev : Regulation of viral expression; Tat : Transcription activator'."),
    ("recall",
     "Which gene is printed as downregulating host CD4 cells?",
     ["Nef", "Vif", "Vpr", "Vpu"],
     "'· Nef/P : Negative effector → Downregulates host CD4 cells'."),
    ("recall",
     "Which two accessory proteins are printed at the end of the non-structural gene list?",
     ["Vpu and Vpx", "Vpr and Vpu only", "Rev and Tat", "Nef and Vif"],
     "The list ends with Vpr (viral protein R) and 'Vpu / Vpx'."),
    ("match",
     "Infection sources — match the concentration to the fluid — 1) Highest 2) As high as blood 3) Low … A) Semen and vaginal fluid B) Tears, saliva, urine and breast milk C) Blood, pus from sores and CSF",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'High concentration : · Blood, · Semen/vaginal fluid (As high as blood), · Pus from sores, CSF'; 'Low concentration : Tears, Saliva (SLIP), urine, Breast milk'."),
    ("recall",
     "What expansion is printed for SLIP in the low-concentration list?",
     ["Salivary lymphocyte inhibitory protein", "Salivary leukocyte inhibitory peptide",
      "Secretory lysosomal inhibitor protein", "Salivary lactoferrin inhibitory protein"],
     "'Saliva (SLIP : Salivary lymphocyte inhibitory protein)'."),
    ("recall",
     "Which body fluid is printed as carrying as high a viral concentration as blood?",
     ["Semen and vaginal fluid", "Saliva", "Breast milk", "Urine"],
     "'· Semen/vaginal fluid (As high as blood)'."),
    ("recall",
     "Which mode of transmission is printed first in the mode-of-transmission list?",
     ["Sexual", "Parent to child", "IV drug abuse", "Blood transfusion"],
     "'Sexual > Parent to child > IV drug abuse > Blood transfusion > Needle stick'."),
    ("numeric",
     "Which exposure is printed as carrying the maximum per-exposure risk, and at what figure?",
     ["Blood transfusion, at 9,250 per 10,000", "Needlestick, at 925 per 10,000",
      "Sexual contact, at 90 per 10,000", "IV drug use, at 9 per 10,000"],
     "'maximum : Blood transfusion (9250/10,000) > Parent to child > IV drug abuse > Needle stick'."),
    ("truefalse",
     "Judge the transmission page: I Sexual transmission outranks parent-to-child, IV drug use, transfusion and needlestick in frequency. II Per exposure, transfusion carries the highest risk.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Sexual > Parent to child > IV drug abuse > Blood transfusion > Needle stick' and 'maximum : Blood transfusion (9250/10,000)'."),
]

# ---------------------------------------------------------------- p1064
p1064 = [
    ("match",
     "Viral entry — match the step to its event — 1) First attachment 2) Co-receptor binding 3) Post-binding change 4) Final step … A) Conformational change in gp41 B) Conformational change in gp120 C) CXCR4 on lymphocytes, CCR5 on macrophages D) Fusion and uncoating of the virus",
     ["1-B, 2-C, 3-A, 4-D", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-C, 4-D"],
     "'Step-1 : Viral entry : Conformational change in gp120; b. Co-receptor binding (CXCR4 - lymphocyte, CCR5 - macrophages); Conformational change in gp41; C. Fusion uncoating of virus'."),
    ("match",
     "Co-receptors — match — 1) CXCR4 2) CCR5 … A) Macrophages B) Lymphocytes",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'(CXCR4 - lymphocyfe, CCR5 - macrophages)'."),
    ("match",
     "Drug classes matched to the replication step — match — 1) Entry 2) Fusion 3) Integration 4) Release … A) Fusion inhibitor given subcutaneously B) Protease inhibitors C) Integrase inhibitors given orally D) Co-receptor blocker given orally",
     ["1-D, 2-A, 3-C, 4-B", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-A, 4-B", "1-B, 2-A, 3-D, 4-C"],
     "'Co-receptor blocker (oral)' at entry, 'Fusion inhibitor (s/c)', 'Integrase inhibitors (Oral)' at integration and 'Cleaved by protease … Protease inhibitors' at release."),
    ("recall",
     "Which step converts viral RNA into DNA in the printed cycle?",
     ["Step 2, viral RNA to DNA", "Step 1, viral entry",
      "Step 3, integration", "Step 4, proliferation"],
     "'Viral RNA → DNA' is the step after viral entry and before integration."),
    ("recall",
     "What makes the released virion mature, according to the page?",
     ["Cleavage by protease", "Cleavage by integrase",
      "Phosphorylation by kinase", "Glycosylation in the Golgi"],
     "'Cleaved by protease → mature virus released'."),
    ("fillup",
     "Fill up: 'Primary infection → incubation period (______ weeks) → acute infectious syndrome / acute HIV infection.'",
     ["3 – 6", "1 – 2", "6 – 12", "12 – 16"],
     "'Incubation period (3-6 weeks)'."),
    ("recall",
     "What illness does the page print that acute HIV infection mimics?",
     ["Infectious mononucleosis", "Influenza with pneumonia",
      "Secondary syphilis", "Acute hepatitis B"],
     "'mimics Infectious mononucleosis'."),
    ("match",
     "Acute HIV syndrome — match the symptom group — 1) Constitutional 2) Throat 3) Nodes 4) Gut and skin … A) Sore throat B) Fever C) Lymphadenopathy D) Diarrhoea and rash",
     ["1-B, 2-A, 3-C, 4-D", "1-A, 2-C, 3-B, 4-D", "1-D, 2-B, 3-A, 4-C", "1-B, 2-D, 3-C, 4-A"],
     "'Clinical Symptoms : Fever, Sore throat, Lymphadenopathy, · Diarrhea, · Rash'."),
    ("numeric",
     "What proportion of acute HIV infections resolve symptomatically, and what proportion are fulminant?",
     ["Over 90% resolve; about 10% are fulminant",
      "Over 50% resolve; half are fulminant",
      "Over 99% resolve; under 1% are fulminant",
      "None resolve; all progress rapidly"],
     "'> 90% : Symptoms resolve'; '≥10% : Fulminant stage (meningoencephalitis)'. (Both figures are printed as given.)"),
    ("recall",
     "Which form does the fulminant stage take, as printed?",
     ["Meningoencephalitis", "Myocarditis",
      "Fulminant hepatic failure", "Acute respiratory distress"],
     "'≥10% : Fulminant stage (meningoencephalitis)'."),
    ("truefalse",
     "Judge the acute-HIV block: I Opportunistic infections are absent in acute HIV infection. II After the acute illness the virus is established in GALT with long subclinical replication (clinical latency).",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'No opportunistic infections', 'Establishment of infection in GALT' and 'Subclinical replication for long period (clinical latency)'."),
    ("recall",
     "Where is infection established during the long subclinical period?",
     ["GALT (gut-associated lymphoid tissue)", "Bone marrow",
      "Thymus", "Splenic white pulp"],
     "'Establishment of infection in GALT'."),
]

# ---------------------------------------------------------------- p1065
p1065 = [
    ("match",
     "Early pathogenesis — match — 1) Primary infection 2) Dissemination 3) Outcome … A) Massive viraemia with wide dissemination to lymphoid organs B) Establishment of infection in GALT C) Establishment of chronic, persistent infection",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     "'Primary infection → Establishment of infection in GALT → Massive viremia → Wide dissemination to lymphoid organs → Establishment of chronic, persistent infection'."),
    ("match",
     "Immune events — match — 1) Early response 2) Control 3) Failure … A) Partial immunologic control of virus replication B) HIV-specific immune response C) Destruction of the immune system with accelerated virus replication",
     ["1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'HIV-specific immune response', 'Partial immunologic control of virus replication' and then 'Destruction of Immune System' with 'Accelerated virus replication'."),
    ("recall",
     "What does the page print as driving immune activation in chronic HIV?",
     ["Cytokines and HIV envelope-mediated aberrant cell signalling",
      "Complement activation alone",
      "Superantigen release by bacteria",
      "Autoantibodies against gp120"],
     "'Immune activation mediated by cytokines and HIV envelope-mediated aberrant cell signaling'."),
    ("recall",
     "What happens to CD4 T-cell turnover, as printed?",
     ["Rapid CD4+ T-cell turnover", "Falls to zero",
      "Is unchanged throughout", "Slows markedly"],
     "'Rapid CD4+ T-cell turnover'."),
    ("match",
     "Course of untreated HIV — match the sequence — 1) After primary infection 2) During dissemination 3) After latency 4) Terminal … A) Wide dissemination of virus with seeding of lymphoid organs B) ± acute HIV syndrome C) Constitutional symptoms, opportunistic diseases and death D) Clinical latency",
     ["1-B, 2-A, 3-D, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-A, 3-B, 4-C", "1-B, 2-D, 3-A, 4-C"],
     "'Primary infection → ± Acute HIV syndrome → Wide dissemination of virus, Seeding of lymphoid organs → Clinical latency → Constitutional symptoms → Opportunistic diseases → Death'."),
    ("match",
     "Graph axes — match the curve to its label — 1) Left axis 2) Right axis 3) Bottom axis … A) Time in weeks 0-12 then years 1-8 B) CD4+ T-lymphocyte count in cells/µL C) HIV RNA copies per mL plasma",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     "'CD4+ T Lymphocyte count (cells/µL)', 'HIV RNA Copies per mL Plasma', 'Time (months after infection)' with weeks then years."),
    ("match",
     "Detection of HIV components — match — 1) Earliest marker 2) Next marker 3) Last … A) p24 antigen, about day 16 / 2-3 weeks B) Anti-HIV antibody C) HIV RNA, about day 10 / 1-2 weeks",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'HIV RNA : 10th day / 1-2 weeks (earliest)'; 'p24 levels : 16th day / 2-3 weeks'; anti-HIV antibody is the last of the three curves."),
    ("numeric",
     "How early does the page print HIV RNA becoming detectable?",
     ["Around day 10, or 1 – 2 weeks", "Around day 3",
      "After 6 weeks", "After 3 months"],
     "'HIV RNA : 10th day / 1-2 weeks (earliest)'."),
    ("numeric",
     "When does the page print p24 antigen becoming detectable?",
     ["Around day 16, or 2 – 3 weeks", "Around day 5",
      "After 6 weeks", "After 6 months"],
     "'p24 levels : 16th day / 2-3 weeks'."),
    ("recall",
     "Which chronic symptoms are printed along the untreated course?",
     ["Constitutional symptoms with skin and mucous-membrane defects and systemic deficiency",
      "Isolated splenomegaly only",
      "Progressive dementia from the outset",
      "Recurrent bacterial pneumonia only"],
     "Along the course the page prints 'Constitutional' symptoms, 'Skin and mucus membrane defects' and 'Systemic deficiency', with acute and chronic lymphadenopathy and subclinical immune dysfunction."),
    ("scenario",
     "A man with a high-risk exposure 12 days ago is anxious about testing. Which marker does the page say is detectable first?",
     ["HIV RNA, from about day 10",
      "p24 antigen, from about day 16",
      "Anti-HIV antibody, from about week 4",
      "None — everything is negative until 3 months"],
     "'HIV RNA : 10th day / 1-2 weeks (earliest)'."),
]

# ---------------------------------------------------------------- p1066
p1066 = [
    ("recall",
     "Which assay does the page print as currently in use for HIV testing?",
     ["4th generation combined antigen-antibody assay", "Western blot alone",
      "Third-generation antibody ELISA", "Viral culture"],
     "'Currently in use : 4th generation combined antigen antibody assay : HIV-1/HIV-2 antigen/antibody combination immunoassay'."),
    ("match",
     "Algorithm — match the result to the next step — 1) Negative 2) Positive … A) HIV-1/HIV-2 antibody differentiation immunoassay B) No HIV",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Interpretation : · If negative : No HIV. · If positive : HIV-1/HIV-2 antibody differentiation immunoassay'."),
    ("match",
     "Differentiation assay outcomes — match — 1) HIV-1 antibodies detected 2) HIV-2 antibodies detected 3) No antibodies detected … A) HIV-2 infection B) HIV-1 NAT needed C) HIV-1 infection",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'HIV-1 antibodies detected', 'HIV-2 antibodies detected' and 'No HIV antibodies detected → HIV-1 NAT'."),
    ("match",
     "HIV-1 NAT — match — 1) Positive 2) Negative … A) Negative for HIV-1 B) Acute HIV-1 infection",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'HIV-1 NAT : Positive → Acute HIV-1 infection; Negative → Negative for HIV-1'."),
    ("scenario",
     "A 4th-generation assay is positive but the HIV-1/HIV-2 differentiation immunoassay detects no antibodies. What is the printed next step and its interpretation?",
     ["HIV-1 NAT — positive means acute HIV-1 infection",
      "Repeat the 4th-generation test in 6 months",
      "Start antiretroviral therapy immediately without further tests",
      "Report the patient as HIV negative"],
     "'No HIV antibodies detected → HIV-1 NAT → Positive : Acute HIV-1 infection; Negative : Negative for HIV-1'."),
    ("match",
     "Opportunistic infections by CD4 — match — 1) Around 600 2) Around 300 3) Around 200 … A) Oral hairy leukoplakia or TB, mucocutaneous herpes, cryptosporidiosis, microsporidiosis B) Pneumocystis jirovecii, miliary TB, oesophageal candidiasis C) Lymphadenopathy and thrombocytopenia",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "The CD4-stratified table lists lymphadenopathy/thrombocytopenia near 600, mucocutaneous herpes and the diarrhoeal parasites around 300, and Pneumocystis, miliary TB and oesophageal candidiasis around 200."),
    ("recall",
     "At what CD4 level is Kaposi's sarcoma printed as occurring?",
     ["At any CD4 count", "Below 200 only", "Below 100 only", "Below 50 only"],
     "'Kaposi sarcoma (At any CD4 count)'."),
    ("match",
     "Low CD4 infections — match — 1) Cerebral toxoplasmosis 2) Cryptococcal meningitis 3) Primary CNS lymphoma … A) CD4 around 100 B) CD4 around 100 C) CD4 50 – 100",
     ["1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A", "1-A, 2-C, 3-B"],
     "The table places cerebral toxoplasmosis and cryptococcal meningitis around a CD4 count of 100, with primary CNS lymphoma at 50-100."),
    ("match",
     "Very low CD4 conditions — match — 1) HIV-associated dementia 2) PML 3) CMV retinitis 4) Mycobacterium avium intracellulare … A) Progressive multifocal leukoencephalopathy B) Cytomegalovirus retinitis C) Disseminated MAC disease D) HIV-associated dementia",
     ["1-D, 2-A, 3-B, 4-C", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-D, 4-A", "1-D, 2-C, 3-A, 4-B"],
     "All four are printed at the lowest CD4 stratum of the opportunistic-infection table."),
    ("oddoneout",
     "Which is NOT printed in the CD4-stratified opportunistic-infection table?",
     ["Pulmonary aspergillosis", "Cryptosporidiosis",
      "Oesophageal candidiasis", "Cerebral toxoplasmosis"],
     "The table lists lymphadenopathy/thrombocytopenia, Kaposi's sarcoma, oral hairy leukoplakia and TB, mucocutaneous herpes, cryptosporidiosis, microsporidiosis, Pneumocystis, miliary TB, oesophageal candidiasis, cerebral toxoplasmosis, cryptococcal meningitis, primary CNS lymphoma, HIV-associated dementia, PML, CMV retinitis and MAC disease."),
]

# ---------------------------------------------------------------- p1067
p1067 = [
    ("recall",
     "How is the fundus appearance of CMV retinitis described?",
     ["Pizza pie appearance", "Cotton-wool appearance",
      "Cherry-red spot", "Brush-field spots"],
     "'CMV : Pizza pie appearance'."),
    ("numeric",
     "What average CD4 count at diagnosis is printed for MAC disease?",
     ["Below 10 cells/µL", "Below 200 cells/µL",
      "Below 500 cells/µL", "Below 1000 cells/µL"],
     "'MAC : · Average CD4 at diagnosis : <10'."),
    ("match",
     "MAC presentation — match — 1) Constitutional 2) Nodes 3) Chest … A) Fever, night sweats and weight loss B) Pulmonary involvement is rare C) Lymphadenopathy",
     ["1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-B, 3-C"],
     "'Highly disseminated disease with : Fever, Night sweats, weight loss, Lymphadenopathy' and '· Pulmonary involvement is rare'."),
    ("recall",
     "Which drug combination is printed for treatment of MAC?",
     ["Clarithromycin plus ethambutol", "Azithromycin plus rifampicin",
      "Rifabutin plus ciprofloxacin", "Isoniazid plus rifampicin"],
     "'· Treatment : Clarithromycin + Ethambutol'."),
    ("numeric",
     "At what CD4 count is MAC prophylaxis printed, and with which drug?",
     ["CD4 below 50 — azithromycin", "CD4 below 200 — co-trimoxazole",
      "CD4 below 100 — clarithromycin", "CD4 below 20 — rifabutin"],
     "'· Prophylaxis (CD4 <50) : Azithromycin'."),
    ("recall",
     "What is the treatment principle printed at the top of the treatment section?",
     ["All HIV must be treated", "Treat only when CD4 falls below 350",
      "Treat only symptomatic patients", "Treat only if the viral load exceeds 1 lakh"],
     "'All HIV must be treated'."),
    ("match",
     "Entry and entry-adjacent inhibitors — match the class to the drug — 1) CD4 receptor inhibitor 2) Co-receptor inhibitor 3) Fusion inhibitor … A) Maraviroc (oral) B) Enfuvirtide (s/c) C) Ibalizumab (IV)",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'CD4 receptor inhibitors : Ibalizumab (IV); Coreceptor inhibitors : maraviroc (oral); Fusion inhibitors : Enfuvirtide (s/c)'."),
    ("match",
     "Enzyme inhibitors — match the class to the drugs — 1) Integrase inhibitors 2) Protease inhibitors … A) Ritonavir, nelfinavir, atazanavir B) Dolutegravir, raltegravir",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Integrase inhibitors : Dolutegravir, Raltegravir'; 'Protease inhibitors : Ritonavir, Nelfinavir, Atazanavir'."),
    ("match",
     "Reverse-transcriptase inhibitors — match the subclass to the drugs — 1) NRTI 2) NNRTI 3) Nucleotide RTI … A) Nevirapine, efavirenz, delavirdine B) Tenofovir disoproxil C) Abacavir, lamivudine, emtricitabine",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'1. Nucleoside reverse transcriptase inhibitors/NRTI : Abacavir, Lamivudine, Emtricitabine; 2. Non-nucleoside reverse transcriptase inhibitors/NNRTI : Nevirapine, Efavirenz, Delavirdine; 3. Nucleotide reverse transcriptase inhibitors : Tenofovir, Disoproxil'."),
    ("recall",
     "Which drug is printed as a co-receptor inhibitor?",
     ["Maraviroc", "Enfuvirtide", "Ibalizumab", "Raltegravir"],
     "'Coreceptor inhibitors : maraviroc (oral)'."),
    ("recall",
     "Which fusion inhibitor and route are printed?",
     ["Enfuvirtide, subcutaneous", "Maraviroc, oral",
      "Ibalizumab, intravenous", "Dolutegravir, oral"],
     "'Fusion inhibitors : Enfuvirtide (s/c)'."),
    ("oddoneout",
     "Which drug is NOT printed among the protease inhibitors?",
     ["Dolutegravir", "Ritonavir", "Nelfinavir", "Atazanavir"],
     "Dolutegravir is an integrase inhibitor; the protease inhibitors listed are ritonavir, nelfinavir and atazanavir."),
    ("scenario",
     "A patient with advanced HIV has fever, night sweats, weight loss, lymphadenopathy and a CD4 count under 10. Which diagnosis, treatment and prophylaxis does the page print?",
     ["Disseminated MAC — treat with clarithromycin plus ethambutol; prophylaxis with azithromycin once CD4 is below 50",
      "Disseminated tuberculosis — treat with HRZE",
      "CMV disease — treat with ganciclovir",
      "Cryptococcal meningitis — treat with amphotericin B"],
     "'MAC : · Average CD4 at diagnosis : <10 … · Treatment : Clarithromycin + Ethambutol · Prophylaxis (CD4 <50) : Azithromycin'."),
]

# ---------------------------------------------------------------- p1068
p1068 = [
    ("recall",
     "How many drugs are printed in the preferred antiretroviral combination?",
     ["3 drugs", "2 drugs", "4 drugs", "1 drug"],
     "'3 drug combination : Preferred combination'."),
    ("match",
     "TED regimen — match the drug to the dose — 1) Tenofovir 2) Emtricitabine 3) Dolutegravir … A) 200 mg once daily B) 50 mg once daily C) 300 mg once daily",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'TED regimen : (300 mg OD) + (200 mg OD) + (50 mg OD)' for tenofovir, emtricitabine and dolutegravir."),
    ("recall",
     "What does the 'E' in the TED regimen stand for?",
     ["Emtricitabine", "Efavirenz", "Ethambutol", "Enfuvirtide"],
     "TED = tenofovir, emtricitabine, dolutegravir."),
    ("match",
     "NACO / TLD regimen — match the drug to the dose — 1) Tenofovir 2) Lamivudine 3) Dolutegravir … A) 300 mg B) 50 mg once daily C) 300 mg once daily",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "'NACO regimen / TLD regimen : (300 mg OD) + (300 mg) + (50 mg OD)'."),
    ("recall",
     "Which backbone drug differs between the TED and the NACO/TLD regimen?",
     ["Emtricitabine in TED is replaced by lamivudine in TLD",
      "Tenofovir is replaced by abacavir",
      "Dolutegravir is replaced by raltegravir",
      "The backbones are identical"],
     "TED uses emtricitabine 200 mg while TLD uses lamivudine 300 mg."),
    ("fillup",
     "Fill up (Post-exposure prophylaxis): 'Optimally effective if started within ______ hours.'",
     ["72", "24", "48", "96"],
     "'Prophylaxis (After needle injury) : Optimally effective if started within 72 hours'."),
    ("numeric",
     "What regimen and duration are printed for post-exposure prophylaxis after a needlestick?",
     ["TED regimen for 4 weeks", "TED regimen for 4 days",
      "TLD regimen for 2 weeks", "Zidovudine alone for 4 weeks"],
     "'· TeD regimen for 4 weeks'."),
    ("recall",
     "Which adverse effect is printed against tenofovir in this section?",
     ["Bone toxicity", "Peripheral neuropathy",
      "Optic neuritis", "Haemolytic anaemia"],
     "'S/e : Bone toxicity with tenofovir'."),
    ("truefalse",
     "Judge the regimen page: I The preferred combination has three drugs, TED being tenofovir, emtricitabine and dolutegravir. II After a needlestick the same TED regimen is given for 4 weeks, ideally started within 72 hours.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'3 drug combination : Preferred combination : TED regimen' and 'Prophylaxis (After needle injury) : Optimally effective if started within 72 hours · TED regimen for 4 weeks'."),
    ("scenario",
     "A health-care worker has a needlestick exposure and presents at 60 hours. What does the page advise?",
     ["Start the TED regimen for 4 weeks — it is still within the 72-hour window",
      "No prophylaxis is useful after 48 hours",
      "Give zidovudine alone for 1 week",
      "Wait for the source patient's viral load result before starting"],
     "'Optimally effective if started within 72 hours · TED regimen for 4 weeks'."),
    ("recall",
     "Which two integrase-inhibitor-containing regimens are named on the last page of this chapter?",
     ["TED and the NACO / TLD regimen", "TEE and ABC/3TC",
      "ZDV/3TC/NVP and TDF/FTC/EFV", "Only the TLD regimen"],
     "Both the TED regimen and the NACO / TLD regimen end with dolutegravir 50 mg once daily."),
]

write_part(CH, "p1061a", 1061,
           "History, CDC staging and AIDS-defining malignancies, viral and fungal illnesses", p1061)
write_part(CH, "p1062a", 1062,
           "Remaining AIDS-defining illnesses, category B, HIV in India and viral structure", p1062)
write_part(CH, "p1063a", 1063,
           "Structural and non-structural genes, infection sources and modes of transmission", p1063)
write_part(CH, "p1064a", 1064,
           "Viral replication steps with drug classes, and acute HIV infection", p1064)
write_part(CH, "p1065a", 1065,
           "Pathogenesis, course of untreated infection and timing of detectable markers", p1065)
write_part(CH, "p1066a", 1066,
           "Testing algorithm and opportunistic infections by CD4 count", p1066)
write_part(CH, "p1067a", 1067,
           "CMV and MAC disease, and the antiretroviral drug classes", p1067)
write_part(CH, "p1068a", 1068,
           "Preferred regimens, NACO/TLD regimen and post-exposure prophylaxis", p1068)

write_units(CH, [
    {"title": "History, staging and AIDS-defining illness",
     "sec": "Definitions · p1061-1062",
     "guide": "First reported case in 1981 from an African patient, formerly lymphadenopathy-associated virus; CDC stages: 0 early HIV infection, 1 ≥500 cells/mm³, 2 200-499 cells/mm³ with CD4 14-28%, 3 <200 cells/mm³ or CD4 <14% with AIDS-defining conditions; AIDS-defining groups: malignancies (Burkitt's, EBV-mediated immunoblastic and primary CNS lymphoma, invasive cervical cancer, Kaposi's sarcoma), viral (CMV outside liver/spleen/nodes, HSV except zoster, JC virus PML), fungal (candidiasis of bronchi/trachea/lungs/oesophagus, extrapulmonary cryptococcosis, Pneumocystis jirovecii), parasitic (cerebral toxoplasmosis) and bacterial (MAC, MTB, Salmonella septicemia); category B non-defining conditions include vulvovaginal and oropharyngeal candidiasis, pelvic inflammatory disease, cervical dysplasia/carcinoma in situ, fever above 38.5 °C or diarrhoea beyond a month, ITP, herpes zoster, peripheral neuropathy and hairy leukoplakia; first Indian case in Chennai in 1986; Retroviridae with HTLV-1 (delta) causing adult T-cell lymphoma/leukemia and tropical spastic paraparesis, and lentiviruses HIV-1 and HIV-2 (less virulent, simian family, West African), envelope gp120/gp41, enzymes, capsid p17/p24, subtype C commonest and subtype B spread through blood and homosexuals.",
     "parts": ["p1061a", "p1062a"]},
    {"title": "Genes, transmission and replication",
     "sec": "Virology · p1063-1064",
     "guide": "Two copies of ssRNA; env codes gp120 spike and gp41 transmembrane pedicle protein, pol codes reverse transcriptase, integrase and protease, gag codes p17 matrix and p24 core (nucleocapsid) protein; non-structural genes Nef (negative effector downregulating host CD4), Vif, Rev, Tat, Vpr and Vpu/Vpx; sources with high concentration are blood, semen and vaginal fluid (as high as blood), pus from sores and CSF, while tears, saliva (with salivary lymphocyte inhibitory protein), urine and breast milk are low; transmission frequency sexual > parent to child > IV drug abuse > transfusion > needlestick, with the highest per-exposure risk being transfusion at 9,250 per 10,000; replication step 1 entry with gp120 change, CXCR4 (lymphocytes) or CCR5 (macrophages) co-receptor binding, gp41 change then fusion and uncoating (co-receptor blocker oral, fusion inhibitor subcutaneous), step 2 RNA to DNA, step 3 integration (oral integrase inhibitors), step 4 proliferation and release with protease cleavage (protease inhibitors); acute HIV infection after a 3-6 week incubation mimicking infectious mononucleosis with fever, sore throat, lymphadenopathy, diarrhoea and rash, no opportunistic infections, over 90% resolving and about 10% fulminant with meningoencephalitis, then establishment in GALT with long subclinical replication (clinical latency).",
     "parts": ["p1063a", "p1064a"]},
    {"title": "Course, diagnosis and opportunistic infections",
     "sec": "Course & diagnosis · p1065-1066",
     "guide": "Pathogenesis: HIV-specific immune response, massive viraemia with wide dissemination to lymphoid organs, GALT seeding, chronic persistent infection with trapping of virus, partial immunologic control, then destruction of the immune system with accelerated replication, immune activation driven by cytokines and HIV envelope-mediated aberrant cell signalling and rapid CD4 T-cell turnover; untreated course runs primary infection with or without acute HIV syndrome, dissemination and lymphoid seeding, clinical latency, constitutional symptoms with skin and mucous-membrane defects and systemic deficiency, opportunistic disease and death; graph shows CD4 count, HIV RNA copies and anti-HIV antibody over weeks then years; HIV RNA detectable around day 10 (1-2 weeks), p24 by day 16 (2-3 weeks) and antibody last; testing uses the 4th-generation HIV-1/HIV-2 antigen/antibody combination immunoassay, negative means no HIV, positive goes to the HIV-1/HIV-2 antibody differentiation immunoassay, and if no antibodies are detected HIV-1 NAT decides between acute HIV-1 infection and a negative result; opportunistic infections by CD4: lymphadenopathy/thrombocytopenia near 600, Kaposi's sarcoma at any count, oral hairy leukoplakia/TB, mucocutaneous herpes, cryptosporidiosis and microsporidiosis near 300, Pneumocystis, miliary TB and oesophageal candidiasis near 200, cerebral toxoplasmosis and cryptococcal meningitis near 100, primary CNS lymphoma at 50-100, and HIV-associated dementia, PML, CMV retinitis and MAC at the lowest counts.",
     "parts": ["p1065a", "p1066a"]},
    {"title": "Treatment: drugs, regimens and prophylaxis",
     "sec": "Therapy · p1067-1068",
     "guide": "CMV retinitis has the pizza-pie fundus; MAC presents with disseminated disease — fever, night sweats, weight loss and lymphadenopathy with rare pulmonary involvement — at an average CD4 below 10, treated with clarithromycin plus ethambutol and prevented with azithromycin when CD4 falls below 50; all HIV must be treated; drug classes are CD4 receptor inhibitors (ibalizumab IV), co-receptor inhibitors (maraviroc oral), fusion inhibitors (enfuvirtide subcutaneous), integrase inhibitors (dolutegravir, raltegravir), protease inhibitors (ritonavir, nelfinavir, atazanavir) and reverse-transcriptase inhibitors — NRTIs abacavir, lamivudine and emtricitabine, NNRTIs nevirapine, efavirenz and delavirdine, and the nucleotide RTI tenofovir disoproxil; preferred three-drug combination is TED (tenofovir 300 mg, emtricitabine 200 mg, dolutegravir 50 mg, all once daily) with the NACO/TLD regimen substituting lamivudine 300 mg for emtricitabine; post-needlestick prophylaxis uses the TED regimen for 4 weeks and is optimally effective within 72 hours; tenofovir carries bone toxicity.",
     "parts": ["p1067a", "p1068a"]},
])
