#!/usr/bin/env python3
"""Ch 65 Autoimmune Hepatitis — Book p1023-1025, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 65

# ---------------------------------------------------------------- p1023
p1023 = [
    ("numeric",
     "Autoimmune Hepatitis Type-1: which sex predominance and age band are printed?",
     ["F >> M; 2nd to 3rd decade female population", "M > F; 2nd to 3rd decade young male population", "F > M 9:1; 4th to 5th decade perimenopausal women", "Children of either sex; 1st decade"],
     "'F >> M (2nd to 3rd decade female population)'."),
    ("numeric",
     "ANA is printed positive in what proportion of AIH Type-1 cases?",
     ["100%", "95%", "50%", "60–65%"],
     "'ANA +ve (100% cases)' — repeated in the antibody table on p1024."),
    ("oddoneout",
     "ANA positivity is stated to be 'also in' two other conditions. Which of the following is NOT one of them?",
     ["Primary sclerosing cholangitis", "Drug induced erythematosus", "Mixed connective tissue disease", "Both listed conditions are correctly stated"],
     "'Also in : Drug induced erythematosus. Mixed connective tissue disease.' PSC is not listed."),
    ("match",
     "Associated HLA and diseases — match — 1) HLA-DR03 2) HLA-DR04 … A) Rheumatoid arthritis, Type-1 DM, autoimmune thyroid disorders B) SLE (AKA lupoid hepatitis)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'HLA-DR03 association +ve : SLE (AKA Lupoid hepatitis)'; 'HLA-DR04 : Rheumatoid arthritis, Type-1 DM, Autoimmune thyroid disorders'."),
    ("fillup",
     "Fill up: AIH occurring with SLE on an HLA-DR03 background is 'AKA ______ hepatitis'.",
     ["Lupoid", "Interphase", "Lymphoplasmacytic", "Piecemeal"],
     "'HLA-DR03 Association +ve : SLE (AKA Lupoid hepatitis)'."),
    ("recall",
     "The pathophysiology heading of AIH characterises the inflammation as which type?",
     ["Lymphoplasmacytic inflammation", "Neutrophilic suppurative inflammation", "Granulomatous non-caseating inflammation", "Eosinophilic inflammation"],
     "'PATHOPHYSIOLOGY — Lymphoplasmacytic inflammation'."),
    ("oddoneout",
     "Three 'unique features / histological findings' of AIH are branched in the diagram. Which is NOT one of them?",
     ["Ductopenia", "Interface hepatitis (piecemeal necrosis)", "Emporipolesis (engulfing cell without killing)", "Rosette formation"],
     "Branches: Interface Hepatitis (Piecemeal necrosis), Emporipolesis (Engulfing cell without killing), Rosette formation. Ductopenia is PBC (p1021)."),
    ("fillup",
     "Fill up the printed bracket: 'Emporipolesis (______ cell without ______)'.",
     ["Engulfing; killing", "Apoptosing; inflammation", "Fusing; necrosis", "Phagocytosing; digestion"],
     "'Emporipolesis (Engulfing cell without killing)'."),
    ("match",
     "Match — 1) filled purple circle 2) orange dots 3) blue open circle 4) red open circle … A) Hepatic artery B) Portal vein C) Central vein D) Hepatocytes",
     ["1-C, 2-D, 3-B, 4-A", "1-B, 2-D, 3-C, 4-A", "1-C, 2-A, 3-B, 4-D", "1-A, 2-D, 3-C, 4-B"],
     "Legend: Central vein (purple filled), Hepatocytes (orange dots), Portal track / Bile duct (open black), Portal vein (blue), Hepatic artery (red)."),
    ("scenario",
     "In the second acinus cone of the diagram, inflammation is drawn spilling from the portal tract across a dashed line into the hepatocyte cone. What is that dashed boundary labelled, and what histological term results?",
     ["Limiting plate; interface hepatitis (piecemeal necrosis)", "Canal of Hering; ductopenia", "Space of Disse; emporipolesis", "Central vein wall; centrilobular necrosis"],
     "Labels: 'Limiting plate' (dashed line) and 'Inflammation' (arrow) — inflammation breaching the limiting plate is interface / piecemeal hepatitis, the micrograph caption reading 'Interphase hepatitis'."),
]

# ---------------------------------------------------------------- p1024
p1024 = [
    ("oddoneout",
     "The presentation tree of AIH has three arms. Which is NOT one of them?",
     ["Cholestatic pruritus", "Acute hepatitis", "Chronic hepatitis", "Cirrhosis with complications"],
     "Arms: Acute Hepatitis; Chronic hepatitis; Cirrhosis with complications. Cholestasis is explicitly 'Not seen in AIH' (bottom note)."),
    ("truefalse",
     "Acute-hepatitis arm — judge: I Presents with waxing and waning of jaundice. II Presents as non-resolving acute hepatitis.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Waxing & waning of jaundice' and 'Non-resolving acute hepatitis' are the two printed bullets."),
    ("management",
     "In the acute-hepatitis arm, what does the book instruct as the '1st rule out'?",
     ["HAV, HBV, HEV", "Wilson's disease and drug injury", "ANA and anti-SMA", "Alcohol and paracetamol"],
     "'1st Rule out → HAV, HBV, HEV'."),
    ("management",
     "If HAV, HBV and HEV are all negative in that arm, which three entities does the flowchart then say to rule out / consider?",
     ["Wilson's disease, autoimmune disease (ANA +ve), fulminant hepatic failure (rare)", "NASH, alcoholic hepatitis, hereditary hemochromatosis (common)", "Primary biliary cirrhosis, primary sclerosing cholangitis, IgG4 disease", "CMV, EBV and HCV post-transfusion hepatitis (rare)"],
     "'If all are negative then rule out → Wilson's ds / Autoimmune disease (ANA +ve) / Fulminant hepatic failure (rare)'."),
    ("recall",
     "Chronic-hepatitis arm: which symptom–sign pair is highlighted first?",
     ["Fatigue and hepatomegaly", "Jaundice and splenomegaly", "Pruritus and xanthelasma", "Ascites and encephalopathy"],
     "'Fatigue & Hepatomegaly' + 'With autoimmune background: Rheumatoid arthritis, SLE'."),
    ("fillup",
     "Fill up: In the chronic arm the arrow toward cirrhosis is annotated 'Jaundice + Splenomegaly — ______/______ progression'.",
     ["Rare / slow", "Rapid / fulminant", "Silent / fast", "Common / stepwise"],
     "The connecting arrow reads 'Jaundice + Splenomegaly — Rare/slow progression' toward cirrhosis with complications."),
    ("numeric",
     "'Then do LFT' in the chronic arm yields what typical enzyme pattern?",
     ["↑ ALT and AST (<150 U/L), ALT > AST", "↑ ALT and AST (>1000 U/L), AST > ALT", "↑ ALP with normal transaminases", "AST:ALT > 2:1 with 300–500 U/L"],
     "'↑ ALT and AST (<150 U/ltr), ALT > AST' → then Fibroscan."),
    ("recall",
     "After LFT in the chronic-hepatitis arm, what is the next arrow in the flowchart?",
     ["Fibroscan", "Liver biopsy", "Immunoelectrophoresis", "MRCP"],
     "LFT → 'Fibroscan'."),
    ("oddoneout",
     "Cirrhosis-with-complications arm lists three complications. Which is NOT printed?",
     ["Hepatorenal syndrome", "Portal HTN", "Liver failure", "Hepatocellular carcinoma (significant risk)"],
     "'Portal HTN; Liver failure; Hepatocellular carcinoma: (Significant risk) – Also in Hemochromatosis.'"),
    ("fillup",
     "Fill up: Under HCC in the AIH cirrhosis arm the book notes the significant risk is 'Also in ______'.",
     ["Hemochromatosis", "Wilson's disease", "Alpha-1 antitrypsin deficiency", "Primary biliary cirrhosis"],
     "'Hepatocellular carcinoma : (Significant risk) – Also in Hemochromatosis.'"),
    ("recall",
     "Laboratory markers: A/G ratio reversal with ↑ globulin leads to which confirmatory test and finding?",
     ["Immunoelectrophoresis / protein electrophoresis: polyclonal hypergammaglobulinemia", "Serum free light chain assay / immunofixation: monoclonal M-band", "Complement C3 / C4 assay: consumption with low levels", "Bone marrow aspirate / trephine: reactive plasmacytosis"],
     "'A/G ratio reversal : ↑ Globulin → Immunoelectrophoresis / Protein electrophoresis : Polyclonal hypergammaglobulinemia'."),
    ("match",
     "Type-I AIH antibody table — match — 1) ANA 2) Anti actin antibody (AAA) 3) Anti SLA … A) Most specific, poor prognosis B) 100% +ve C) Poor prognosis",
     ["1-B, 2-C, 3-A", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-C, 3-B"],
     "ANA = 100% +ve; Anti SMA (no feature printed); AAA = Poor prognosis; Anti SLA (soluble liver antigen) = most specific, poor prognosis."),
    ("fillup",
     "Fill up: 'Anti SLA' in the Type-I table stands for anti ______ antigen.",
     ["soluble liver", "smooth-muscle liver", "sinusoidal lining", "specific lupoid"],
     "'Anti SLA (Soluble liver antigen) — most specific, poor prognosis'."),
    ("oddoneout",
     "Atypical p-ANCA in the Type-I table is 'seen in' three conditions. Which is NOT one of them?",
     ["Primary biliary cirrhosis", "AIH", "Primary sclerosing cholangitis", "Ulcerative colitis"],
     "'Seen in : AIH, Primary Sclerosing Cholangitis, Ulcerative colitis.' PBC is the AMA condition in the note below."),
    ("match",
     "Type-II AIH table — match — 1) Anti LKM-1 2) Anti liver cytosol type-1 … A) Poor prognosis B) Also seen in HCV infection",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "Anti LKM-1 : Also seen HCV infection; Anti liver cytosol type-1 : Poor prognosis."),
    ("match",
     "Note beside the Type-II table — match — 1) Anti LKM-2 2) Anti LKM-3 … A) HDV infection B) Drug induced hepatitis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Anti LKM-2 : Drug induced hepatitis; Anti LKM-3 : HDV infection'."),
    ("scenario",
     "A young woman with suspected AIH has pruritus, hyperpigmentation and weight loss, and her serum is AMA-positive. Per the bottom Note on this page, how should this be read?",
     ["Cholestasis with AMA points to primary biliary cirrhosis — this triad is not seen in AIH", "Classic Type-I AIH with cholestatic onset — start steroid 1 mg/kg/day", "Type-II AIH with hyperpigmentation — confirm with anti-LKM-1 and liver cytosol-1", "AIH–PSC overlap with cholestatic features — order MRCP for strictures"],
     "Note: 'Antimitochondrial Antibody : Primary biliary cirrhosis. Cholestasis : Pruritis + hyperpigmentation + weightloss (Not seen in AIH)'."),
]

# ---------------------------------------------------------------- p1025
p1025 = [
    ("truefalse",
     "Type-II AIH — judge: I Seen in children. II Carries a good prognosis. III Associated with HLA DR-7.",
     ["I and III true, II false", "All three true", "I true, II and III false", "II and III true, I false"],
     "'Seen in children; Poor prognosis; A/w HLA DR-7'."),
    ("oddoneout",
     "Disease associations of Type-II AIH — which is NOT printed?",
     ["Rheumatoid arthritis", "Diabetes mellitus Type-1", "Vitiligo", "Autoimmune polyendocrine syndrome Type-1"],
     "'Disease Association : Diabetes mellitus Type-1, Vitiligo, Autoimmune polyendocrine syndrome Type-1.' RA is the HLA-DR04 Type-1 association (p1023)."),
    ("management",
     "Treatment flowchart: once AIH is diagnosed, what is checked for by Fibroscan before treatment?",
     ["Cirrhosis", "Steatosis grade", "Portal vein thrombosis", "HCC"],
     "'Diagnosed AIH — Fibroscan, check for → Cirrhosis'."),
    ("numeric",
     "What is the printed steroid regimen for AIH and the taper duration?",
     ["1 mg/kg/day × 4 weeks, then taper over 12 weeks", "1 mg/kg × 7 days, tapering over 3 weeks", "0.5 mg/kg/day × 4 weeks, taper 4 weeks", "40 mg/day × 6 weeks, taper 8 weeks"],
     "'Steroid 1 mg/kg/day × 4 weeks → Taper → 12 weeks' +/− Azathioprine. (1 mg/kg × 7 days over 3 weeks is the alcoholic-hepatitis regimen, p1028.)"),
    ("fillup",
     "Fill up: Steroid in AIH is given '+/− ______', and response is assessed 'After ______ months'.",
     ["Azathioprine; 3–4", "Mycophenolate; 6", "UDCA; 12", "Pentoxifylline; 1"],
     "'+/− Azathioprine' and 'After 3–4 months' the outcome branches to remission or relapse."),
    ("oddoneout",
     "Which of the following is NOT one of the four printed criteria of remission?",
     ["Normalisation of IgG / globulin", "Symptomatic improvement", "Histological improvement", "↓ S. bilirubin and liver enzymes back to normal"],
     "Remission: Symptomatic improvement; Histological improvement; ↓ S. bilirubin; Liver enzyme back to normal."),
    ("management",
     "A patient relapses after 3–4 months of steroid ± azathioprine. What does the flowchart direct, and what caveat follows?",
     ["Transplant, with chances of recurrence", "Double the steroid dose indefinitely", "Switch to obeticholic acid", "Add pentoxifylline 400 mg TDS"],
     "'Relapse → Transplant → Chances of recurrence'."),
]

write_part(CH, "p1023a", 1023, "AIH Type-1: demographics, ANA, HLA associations, lymphoplasmacytic pathology, histological triad and acinus diagram", p1023)
write_part(CH, "p1024a", 1024, "AIH presentation tree, LFT/fibroscan, laboratory markers and antibody tables", p1024)
write_part(CH, "p1025a", 1025, "Type-II AIH features and treatment algorithm", p1025)

write_units(CH, [
    {"title": "AIH Type-1 — demographics, ANA, HLA and histological hallmarks",
     "sec": "Type-1 basics · p1023",
     "guide": "F>>M 2nd–3rd decade; ANA 100% (also drug-induced erythematosus, MCTD); HLA-DR03 → SLE/lupoid hepatitis, HLA-DR04 → RA, T1DM, autoimmune thyroid; lymphoplasmacytic inflammation; interface hepatitis (piecemeal necrosis), emporipolesis (engulfing without killing), rosette formation; acinus legend and limiting plate.",
     "parts": ["p1023a"]},
    {"title": "Presentation arms, laboratory markers and antibody tables",
     "sec": "Presentation & labs · p1024",
     "guide": "Acute (waxing/waning jaundice, non-resolving; rule out HAV/HBV/HEV → Wilson's, autoimmune ANA+, FHF rare); chronic (fatigue + hepatomegaly with RA/SLE; LFT <150 ALT>AST → fibroscan; rare/slow progression); cirrhosis (portal HTN, liver failure, HCC also in hemochromatosis); A/G reversal → polyclonal hypergammaglobulinemia; Type-I ANA 100%, SMA, AAA poor prognosis, SLA most specific/poor, atypical p-ANCA (AIH/PSC/UC); Type-II LKM-1 (HCV), liver cytosol-1 poor; LKM-2 drug, LKM-3 HDV; AMA = PBC, cholestasis triad not in AIH.",
     "parts": ["p1024a"]},
    {"title": "Type-II AIH and treatment algorithm",
     "sec": "Type-II & Rx · p1025",
     "guide": "Children, poor prognosis, HLA DR-7, T1DM/vitiligo/APS-1; fibroscan for cirrhosis; steroid 1 mg/kg/day × 4 weeks, taper 12 weeks, ± azathioprine; after 3–4 months remission (symptomatic, histological, ↓ bilirubin, enzymes normal) vs relapse → transplant → recurrence risk.",
     "parts": ["p1025a"]},
])
