#!/usr/bin/env python3
"""Ch 68 Vascular Diseases of Liver — Book p1033-1035, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 68

# ---------------------------------------------------------------- p1033
p1033 = [
    ("match",
     "Opening classification — match — 1) Extrahepatic 2) Intrahepatic pre-sinusoidal 3) Post hepatic … A) 3rd order vein B) 1st order portal vein involvement C) Hepatic venous obstruction",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "Extrahepatic: 1st order portal vein involvement; Pre-sinusoidal: 3rd order vein; Post hepatic: hepatic venous obstruction."),
    ("fillup",
     "Fill up: The extrahepatic entity is Extrahepatic portal vein occlusion (______), described as ______.",
     ["EHPVO; non-cirrhotic", "EHPVO; cirrhotic", "NCPF; cirrhotic", "BCS; non-cirrhotic"],
     "'Extrahepatic portal vein occlusion (EHPVO). • Non cirrhotic'."),
    ("match",
     "Intrahepatic sub-types — match — 1) Pre-sinusoidal 2) Sinusoidal 3) Post-sinusoidal … A) Cirrhosis PH B) Sinusoidal obstruction syndrome (veno-occlusive) C) Non-cirrhotic portal fibrosis (NCPF)",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     "Pre-sinusoidal: 3rd order vein, NCPF; Sinusoidal: Cirrhosis PH; Post sinusoidal: Sinusoidal obstruction syndrome (veno occlusive)."),
    ("recall",
     "Post-hepatic hepatic venous obstruction is exemplified by which condition, and what does the arrow beneath it lead to?",
     ["Budd Chiari syndrome → cirrhosis", "Veno-occlusive disease → NCPF", "EHPVO → hypersplenism", "Constrictive pericarditis → ascites"],
     "'Post hepatic: Hepatic venous obstruction: • Budd Chiari syndrome → Cirrhosis.'"),
    ("fillup",
     "Fill up (BCS pathogenesis): Vasculature — ______ ductule of acinus → right atrium; hepatic venous occlusion / thrombosis anywhere → ______ entry into right atrium.",
     ["efferent; IVC", "afferent; SVC", "efferent; portal vein", "afferent; hepatic artery"],
     "'Vasculature : efferent ductule of acinus — Hepatic venous occlusion / Thrombosis anywhere → IVC entry into Right atrium.'"),
    ("match",
     "Site of BCS — match — 1) Hepatic vein 2) Terminal IVC … A) 2nd most common B) Most common",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Hepatic vein : m/c. Terminal IVC : 2nd m/c.'"),
    ("recall",
     "Among the inherited deficiencies causing BCS, which hierarchy is printed?",
     ["Anti-thrombin 3 > Protein C / Protein S", "Protein C > Protein S > Anti-thrombin 3", "Protein S > Anti-thrombin 3 > Protein C", "Factor V Leiden > Prothrombin gene > Protein C"],
     "'Deficiency : Anti thrombin 3 > Protein C/Protein S.'"),
    ("oddoneout",
     "Which of the following is NOT one of the six printed causes of BCS?",
     ["Oral contraceptive pills", "Factor V Leiden mutation", "Paroxysmal nocturnal haemoglobinuria", "Pregnancy / post partum"],
     "Causes: Factor V Leiden mutation; deficiency AT3 > protein C/S; MPN; polycythemia rubra vera (PCRV); PNH; pregnancy/post partum."),
    ("truefalse",
     "Classification of BCS — judge: I Secondary is far commoner than primary (2° >> 1°). II Secondary is subdivided into inherited and acquired.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Primary / Secondary (2° >> 1°) → Inherited / Acquired.'"),
]

# ---------------------------------------------------------------- p1034
p1034 = [
    ("recall",
     "Most common presentation demographic of BCS printed?",
     ["30–40 years post-partum female", "3–8 year child", "20–40 year adult Asian male", "Neonate with umbilical sepsis"],
     "'m/c : 30–40 years post partum female.'"),
    ("fillup",
     "Fill up: Ascites in BCS arises from zone ______ involvement → sinusoidal ______ + pooling.",
     ["3; distension", "1; collapse", "2; fibrosis", "3; sclerosis"],
     "'Ascites : zone 3 involvement → sinusoidal distension + pooling.'"),
    ("truefalse",
     "Subacute BCS — judge: I It is the most common presentation. II It causes refractory ascites with collaterals. III The ascites is high-SAAG, high-protein.",
     ["All three true", "I and II true, III false", "II and III true, I false", "I true, II and III false"],
     "'1. Subacute : m/c presentation; Refractory ascites + collaterals; High SAAG, high protein ascites.'"),
    ("scenario",
     "A patient's ascitic fluid shows high SAAG and LOW protein. Per the Note on this page, what does this pattern indicate?",
     ["Sinusoidal cause", "Post-sinusoidal (hepatic venous) cause such as BCS", "Peritoneal carcinomatosis", "Pancreatic ascites"],
     "'Note : High SAAG, low protein ascites : Sinusoidal cause.' (BCS gives high SAAG, high protein.)"),
    ("numeric",
     "Acute hepatitis presentation of BCS: what jaundice frequency is printed and how common is fulminant hepatic failure?",
     ["Jaundice <10%; fulminant hepatic failure rare", "Jaundice 50%; fulminant hepatic failure common", "Jaundice 10–30%; fulminant hepatic failure 20%", "Jaundice universal; fulminant hepatic failure rare"],
     "'2. Acute Hepatitis : Abdominal pain + hepatomegaly + ascites; Jaundice : <10% patients; Fulminant hepatic failure : Rare.' Then '3. Cirrhosis'."),
    ("numeric",
     "Prognosis of BCS as printed?",
     ["Very poor: 3-year survival rate < 10%", "Good: negligible cirrhosis risk", "5-year survival 50%", "Very poor: 1-year survival < 50%"],
     "'PROGNOSIS • very poor : 3yr survival rate < 10%.'"),
    ("recall",
     "Mechanism flowchart, LEFT column — put in order: A) Extravasation of fluid from hepatic vein > sinusoids B) Increased sinusoidal & portal pressure C) High SAAG, high protein ascites D) Sinusoidal distension",
     ["B → D → A → C", "D → B → A → C", "B → A → D → C", "A → B → D → C"],
     "Hepatic venous outflow obstruction → Increased sinusoidal & portal pressure → Sinusoidal distension → Extravasation of fluid from hepatic vein > sinusoids → High SAAG, high protein ascites."),
    ("recall",
     "Mechanism flowchart, RIGHT column — put in order: A) Fibrosis, nodular regenerative hyperplasia B) Venous stasis and congestion C) Hepatocyte necrosis (centrilobular) leading to lobar collapse D) Hypoxic damage to hepatocytes, zone 3 involvement",
     ["B → D → C → A → Cirrhosis", "D → B → C → A → Cirrhosis", "B → C → D → A → Cirrhosis", "B → D → A → C → Cirrhosis"],
     "Venous stasis and congestion → Hypoxic damage to hepatocytes, zone 3 → Hepatocyte necrosis (centrilobular) leading to lobar collapse → Fibrosis, nodular regenerative hyperplasia → Cirrhosis. Caption: 'mechanism of Ascites & Cirrhosis in BCS'."),
    ("match",
     "Investigations — match — 1) Hepatic venous Doppler 2) CECT 3) MRI … A) IOC B) Nodules / hemorrhagic liver C) Screening test; obstruction + portosystemic collaterals",
     ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "Doppler: screening test, obstruction + portosystemic collaterals; CECT: IOC; MRI: nodules/hemorrhagic liver."),
    ("recall",
     "What does the red arrow on the 'CECT image in BCS' point to?",
     ["Caudate lobe hypertrophy", "Cavernoma", "Portal vein thrombus", "Splenic varices"],
     "Label: 'Caudate lobe hypertrophy' — CECT image in BCS."),
    ("management",
     "Management of BCS: which statement matches the printed text?",
     ["Anticoagulation is mandatory for all; non-decompensated patients get angioplasty ± stenting, and on failure TIPSS", "Anticoagulation only if PNH; all others go straight to TIPSS", "Angioplasty is reserved for decompensated patients; anticoagulation is optional", "Liver transplant is first-line in all non-decompensated patients"],
     "'mandatory anticoagulation to all. Non decompensated patients : Angioplasty +/− stenting —Failure→ TIPSS (Transjugular Intrahepatic Porto-systemic Shunt).'"),
]

# ---------------------------------------------------------------- p1035
p1035 = [
    ("fillup",
     "Fill up the alternative names in the table header: NCPF / IPH / Hepatoportal ______ / Obliterative portal ______.",
     ["Sclerosis; venopathy", "Fibrosis; arteriopathy", "Cirrhosis; venopathy", "Sclerosis; biliopathy"],
     "Header: 'NCPF/IPH/Hepatoportal Sclerosis Obliterative portal venopathy)'."),
    ("match",
     "Row 'Outcome' (demographic) — match — 1) EHPVO 2) NCPF … A) 20–40 yr adult Asian male B) 3–8 yr child (m/c cause of UGI bleed in children)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "EHPVO: 3–8 yr child (m/c cause of UGI bleed in children); NCPF: 20–40 yr adult Asian male."),
    ("match",
     "Rows 'Involvement' and 'Cause' — match — 1) EHPVO 2) NCPF … A) 3rd order portal vein; E. coli / arsenic associations, hypervitaminosis A B) 1st order portal vein; umbilical sepsis > prothrombotic state",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "EHPVO: 1st order portal vein, umbilical sepsis > prothrombotic state. NCPF: 3rd order portal vein, E. coli/arsenic, hypervitaminosis A."),
    ("scenario",
     "A 6-year-old presents with massive haematemesis and a massive spleen; blood counts show anaemia and thrombocytopenia. Per the table, what explains the cytopenias and which condition is this?",
     ["Hypersplenism; EHPVO", "Marrow suppression by arsenic; NCPF", "Portal biliopathy; EHPVO", "Consumptive coagulopathy; BCS"],
     "EHPVO presentation: 'massive UGI bleed + massive spleen (hypersplenism) → Anemia, thrombocytopenia'. NCPF presents similarly but in 20–40 yr adults."),
    ("truefalse",
     "Row 'Prognosis' — judge: I EHPVO prognosis is good with no risk for cirrhosis. II NCPF prognosis is good with negligible risk for cirrhosis.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "EHPVO: 'Good, with no risk for cirrhosis'; NCPF: 'Good, negligible risk for cirrhosis'."),
    ("match",
     "Row 'Investigations' — match — 1) EHPVO 2) NCPF … A) IOC Doppler; biopsy (gold standard) shows obliterative portal venopathy B) IOC CT; cavernoma appearance of collaterals",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "EHPVO: IOC CT, cavernoma appearance of collaterals. NCPF: IOC Doppler, biopsy gold std — obliterative portal venopathy."),
    ("fillup",
     "Fill up (EHPVO complications): Stunted growth and portal ______ — compression of the biliary system by portal ______.",
     ["biliopathy; collaterals", "cholangiopathy; thrombus", "biliopathy; lymph nodes", "venopathy; cavernoma"],
     "'Portal biliopathy : compression of biliary system by portal collaterals.' NCPF complications: '—'."),
    ("recall",
     "What treatment is printed for EHPVO, and what is printed for NCPF?",
     ["EHPVO: endoscopic variceal ligation / endoscopic sclerotherapy; NCPF: '—' (none printed)", "EHPVO: TIPSS after failed angioplasty; NCPF: liver transplant (only treatment)", "EHPVO: mandatory anticoagulation; NCPF: splenectomy with devascularisation", "Both: angioplasty ± stenting, then endoscopic sclerotherapy on failure"],
     "Treatment row: EHPVO = Endoscopic variceal ligation / Endoscopic sclerotherapy; NCPF = '—'."),
    ("match",
     "Note on the most common cause of portal hypertension — 1) Asia 2) World … A) Biliary atresia B) EHPVO",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'m/c cause of PHTN : Asia: EHPVO; world: Biliary atresia.'"),
    ("match",
     "Match — 1) CECT panels 2) Colour Doppler 3) Trichrome/H&E micrograph … A) Obliterative portal venopathy — sclerotic & non-patent portal tracts B) EHPVO showing collaterals C) EHPVO with cavernoma labelled",
     ["1-B, 2-C, 3-A", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C", "1-A, 2-C, 3-B"],
     "'CECT: EHPVO showing collaterals'; 'Color doppler : EHPVO' with 'Cavernoma' arrow; 'Obliterative portal venopathy' with 'Sclerotic & non patent portal tracts'."),
]

write_part(CH, "p1033a", 1033, "Classification of hepatic vascular disease; BCS pathogenesis, site, causes, classification", p1033)
write_part(CH, "p1034a", 1034, "BCS presentation, prognosis, mechanism flowchart, investigations and management", p1034)
write_part(CH, "p1035a", 1035, "Non-cirrhotic diseases: EHPVO vs NCPF table, PHTN note and images", p1035)

write_units(CH, [
    {"title": "Classification and Budd–Chiari pathogenesis, sites, causes",
     "sec": "Classification & BCS causes · p1033",
     "guide": "Extrahepatic 1st-order portal vein (EHPVO, non-cirrhotic); intrahepatic pre-sinusoidal 3rd-order vein/NCPF, sinusoidal cirrhosis PH, post-sinusoidal SOS (veno-occlusive); post-hepatic BCS → cirrhosis; efferent ductule → IVC → RA; hepatic vein m/c, terminal IVC 2nd; Factor V Leiden, AT3 > protein C/S, MPN, PCRV, PNH, pregnancy/post-partum; primary vs secondary (2°>>1°) inherited/acquired.",
     "parts": ["p1033a"]},
    {"title": "BCS presentation, mechanism, investigations and management",
     "sec": "BCS clinical · p1034",
     "guide": "30–40 yr post-partum female; zone-3 sinusoidal distension + pooling; subacute m/c with refractory ascites, high SAAG high protein (low protein = sinusoidal); acute hepatitis jaundice <10%, FHF rare; cirrhosis; 3-yr survival <10%; two-column mechanism flowchart; Doppler screening, CECT IOC (caudate hypertrophy), MRI nodules/hemorrhagic; anticoagulate all, angioplasty ± stent → TIPSS.",
     "parts": ["p1034a"]},
    {"title": "EHPVO vs NCPF/IPH and the portal-hypertension note",
     "sec": "Non-cirrhotic PHTN · p1035",
     "guide": "3–8 yr child (m/c UGI bleed in children) vs 20–40 yr Asian male; 1st vs 3rd order vein; umbilical sepsis > prothrombotic vs E. coli/arsenic/hypervitaminosis A; massive bleed + spleen, hypersplenism cytopenias; good prognosis both; CT cavernoma vs Doppler + biopsy obliterative venopathy; stunted growth, portal biliopathy; EVL/sclerotherapy; Asia EHPVO, world biliary atresia; image captions.",
     "parts": ["p1035a"]},
])
