#!/usr/bin/env python3
"""Ch 71 Hepatitis C Virus — Book p1045-1046, strict source order."""
from itemwriter_70_74 import write_part, write_units

CH = 71

p1045 = [
    ("fillup",
     "Fill up (Structure): '______ sense RNA virus : ______ (Family), ______ (Sub family).'",
     ["+ve; Flaviviridae; Hepaciviridae", "-ve; Flaviviridae; Hepaciviridae",
      "+ve; Hepaciviridae; Flaviviridae", "-ve; Retroviridae; Lentivirinae"],
     "'+ve sense RNA virus : Flaviviridae (Family), Hepaciviridae (Sub family)'."),
    ("recall",
     "How does the page describe the HCV virion?",
     ["A lipoviral particle bound to VLDL / LDL", "A 42 nm Dane particle",
      "A naked icosahedral capsid", "An enveloped DNA nucleocapsid"],
     "'Virion (lipo viral particle) : Bound to VLDL / LDL — causes Steatosis'."),
    ("scenario",
     "Which mechanism does this page give for steatosis in chronic hepatitis C?",
     ["The lipoviral particle is bound to VLDL / LDL", "Autoimmune destruction of bile ducts",
      "Iron overload from repeated phlebotomy", "Alcohol-like acetaldehyde toxicity"],
     "'Virion (lipo viral particle) : Bound to VLDL/LDL → causes Steatosis'."),
    ("truefalse",
     "Judge the steatosis note: I Hepatitis A, B and D are listed as not causing steatosis. II HCV causes steatosis through its lipoviral particle.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Hepatitis A, B, D & E do not cause steatosis' follows the lipoviral-particle note."),
    ("numeric",
     "Genome length and coding capacity printed for HCV?",
     ["9.7 kb, coding for about 3,000 amino acids as a polyprotein",
      "3.2 kb, coding for about 300 amino acids",
      "9.7 kb, coding for four separate structural proteins only",
      "1.7 kb, coding for about 900 amino acids"],
     "'Length : 9.7 kb — codes for ~3000 amino acid polyprotein'."),
    ("recall",
     "Which host enzyme is printed as cleaving the structural from the non-structural genes?",
     ["Host signal peptidase", "Viral NS3 protease",
      "Host furin", "Viral NS5B polymerase"],
     "'Structural genes / Non-structural genes' are separated by 'host signal peptidase'."),
    ("match",
     "DAA drug-name suffixes — match — 1) NS3 2) NS5A 3) NS5B … A) -asvir B) -buvir C) -previr",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "'NS3 (-) : Previr; NS5A (-) : Asvir; NS5B (-) : buvir' under 'New Directly Acting Antivirals (DAAs)'."),
    ("numeric",
     "How many HCV genotypes does the page print, and which one is commonest in India?",
     ["7 genotypes; genotype 3 commonest in India", "6 genotypes; genotype 1 commonest in India",
      "7 genotypes; genotype 4 commonest in India", "3 genotypes; genotype 2 commonest in India"],
     "'7 genotypes : Genotype 1 : m/c (world); Genotype 3 : m/c (India)'."),
    ("truefalse",
     "Judge the genotype note: I Genotype 1 is the commonest worldwide. II Genotype 3, commonest in India, carries the worst prognosis and is linked to cirrhosis and HCC.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Genotype 1 : m/c (world)'; 'Genotype 3 : m/c (India) — worst prognosis'; 'Note : Associated with Cirrhosis / Hepatocellular carcinoma'."),
    ("recall",
     "The note 'Hepatitis A, B, D & E do not cause steatosis' is printed next to the description of which virus?",
     ["Hepatitis C virus", "Hepatitis A virus", "Hepatitis D virus", "Hepatitis E virus"],
     "The note follows the HCV lipoviral-particle line that explains steatosis."),
    ("match",
     "Transmission — match the route to the printed risk — 1) Transfusion 2) IV drug users 3) Sexual modes … A) 40 – 90% B) Negligible C) 1 in 10,00,000",
     ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A"],
     "'Transfusion : 1/10,00,000'; 'IV drug users (40-90%)'; 'Sexual modes : Negligible'."),
    ("recall",
     "Which group is printed as the commonest setting (m/c in) for HCV infection?",
     ["CKD patients", "Pregnant women", "Health-care workers after needlestick", "Children of infected mothers"],
     "'m/c in : CKD patients'."),
    ("recall",
     "What does the page print for post-exposure prophylaxis against HCV?",
     ["Unavailable", "HBIG within 24 hours", "Vaccine plus HBIG", "Lamivudine for 4 weeks"],
     "'Post exposure prophylaxis : unavailable'."),
    ("oddoneout",
     "Which is NOT one of the printed transmission headings for HCV?",
     ["Feco-oral", "Percutaneous", "Transfusion", "Perinatal / breast feeding"],
     "Printed headings: Percutaneous, Transfusion, Perinatal / Breast feeding, Sexual modes, IV drug users."),
    ("recall",
     "Perinatal / breast-feeding transmission of HCV is printed in which risk band?",
     ["A low single-digit percentage — far below the 40 – 90% seen in IV drug users",
      "40 – 90%, the same as IV drug users",
      "1 in 10,00,000, the same as transfusion",
      "Negligible, the same as sexual transmission"],
     "Perinatal / breast feeding is printed in the single-digit percent range, against 40-90% for IV drug users, negligible for sexual exposure and 1 in 10,00,000 for transfusion."),
]

p1046 = [
    ("match",
     "Progression chain — match — 1) After infection 2) Acute phase 3) Chronic phase 4) End stage … A) Chance for chronic hepatitis B) Cirrhosis / liver failure / portal hypertension C) HCC D) Incubation period of about 50 days",
     ["1-D, 2-A, 3-B, 4-C", "1-A, 2-D, 3-C, 4-B", "1-D, 2-B, 3-A, 4-C", "1-C, 2-A, 3-B, 4-D"],
     "'Incubation period : 50 days → Acute → Chance for chronic → Cirrhosis / Liver failure (PHTN) → HCC'."),
    ("numeric",
     "Incubation period printed for HCV?",
     ["About 50 days", "About 15 days", "About 60 days", "About 6 months"],
     "'Incubation period : 50 days'."),
    ("truefalse",
     "Judge the acute phase: I Acute HCV is usually anicteric and therefore usually undiagnosed. II Enzymes are variable and fulminant failure occurs in 0.1 – 1%.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "'Acute : Anicteric hepatitis, usually undiagnosed; Enzymes : variable; Fulminant failure : 0.1-1%'."),
    ("numeric",
     "Risk of fulminant hepatic failure printed for acute HCV?",
     ["0.1 – 1%", "5 – 20%", "10 – 30%", "0.01%"],
     "'Fulminant failure : 0.1-1%'."),
    ("match",
     "Serology — match the marker to the window — 1) Earliest marker after infection 2) Appears after the serological window … A) Anti-HCV B) HCV RNA",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "The window phase shows HCV RNA first, with anti-HCV appearing later ('Serologic window', 'HCV RNA', 'Anti-HCV' sequence)."),
    ("scenario",
     "An immunosuppressed patient (CKD / haemodialysis / HIV) has a negative anti-HCV EIA. What does this page advise?",
     ["Test HCV RNA, because such patients may not produce anti-HCV",
      "Repeat anti-HCV after 6 months only",
      "No further testing is needed — the patient is not infected",
      "Do a liver biopsy to rule out cirrhosis"],
     "'CKD / Hemodialysis / HIV (Immunosuppressed patients may not produce anti-HCV) → HCV RNA'."),
    ("match",
     "Interpretation of anti-HCV EIA — match — 1) Positive 2) Negative … A) No HCV contact B) Acute / chronic infection or recovered",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'+ve → acute / chronic infection / recovered'; '-ve → No HCV contact'."),
    ("recall",
     "Which investigation is printed to rule out cirrhosis in chronic HCV?",
     ["Fibroscan", "MRCP", "Liver biopsy", "Ct abdomen"],
     "'Fibroscan (to rule out cirrhosis)'."),
    ("match",
     "Presentation — match — 1) Acute HCV 2) Chronic HCV … A) Asymptomatic / extrahepatic manifestations B) Fever, flu-like illness, fatigue",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'Acute : Fever / flu like illness, fatigue'; 'Chronic : Asymptomatic / extra hepatic manifestations'."),
    ("match",
     "Sustained viral response — match the condition to the printed SVR — 1) Chronic HCV 2) Cirrhosis 3) Decompensated liver disease … A) 60% B) 75% C) 99.5 – 99.7%",
     ["1-C, 2-B, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     "'Condition : Chronic HCV / Cirrhosis / Decompensated liver disease; Response (SVR) : 99.5-99.7% / 75 / 60%'."),
    ("recall",
     "What age threshold does the page print for treating HCV?",
     ["Treat anyone above 12 years of age", "Treat anyone above 18 years of age",
      "Treat only adults above 40 years", "Treat only after fibrosis stage F2"],
     "'Treat anyone > 12 years of age'."),
    ("match",
     "Regimen — match the DAA class to the drug printed — 1) NS3 2) NS5A 3) NS5B … A) Sofosbuvir B) Velpatasvir C) Glecaprevir / simeprevir",
     ["1-C, 2-B, 3-A", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-A, 3-B"],
     "'NS3 (-) : Glecaprevir / simeprevir; NS5A (-) : velpatasvir; NS5B (-) : Sofosbuvir + Ribavirin'."),
    ("numeric",
     "Duration printed for the DAA combination in chronic HCV with cirrhosis?",
     ["12 weeks", "24 weeks", "8 weeks", "48 weeks"],
     "'Combination for 12 weeks for chronic HCV with cirrhosis'."),
    ("recall",
     "Which DAA component is flagged as not available in India on this page?",
     ["Velpatasvir (NS5A)", "Sofosbuvir (NS5B)",
      "Glecaprevir (NS3)", "Ribavirin"],
     "'Not available in India' is printed against the NS5A agent velpatasvir."),
    ("oddoneout",
     "Which is NOT one of the printed extrahepatic manifestations of HCV?",
     ["Kayser-Fleischer rings", "Sjogren's syndrome",
      "Porphyria cutanea tarda", "Lichen planus"],
     "Printed list: Sjogren's syndrome, extranodal B-cell marginal zone lymphoma, essential mixed cryoglobulinaemia, porphyria cutanea tarda, lichen planus, MPGN, autoimmune thyroid illness."),
    ("match",
     "Extrahepatic manifestations — match — 1) Essential mixed cryoglobulinaemia 2) Extranodal marginal zone lymphoma 3) Renal lesion … A) Salivary gland B) Classical MPGN C) Type 2 and type 3",
     ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A"],
     "'Essential mixed cryoglobulinemia type 2, 3'; 'extranodal B cell marginal zone lymphoma (MZL) : salivary gland'; 'Classical MPGN (membranoproliferative glomerulonephritis)'."),
    ("recall",
     "Which thyroid disease is printed among the extrahepatic associations of HCV?",
     ["Autoimmune thyroid illness (Hashimoto)", "Graves disease",
      "Riedel thyroiditis", "Subacute de Quervain thyroiditis"],
     "'Autoimmune thyroid illness (Hashimoto)'."),
    ("recall",
     "What is the printed treatment headline for chronic HCV drugs?",
     ["New DAAs, pangenotypic drugs with markedly improved SVR",
      "Interferon plus ribavirin for 48 weeks",
      "Lamivudine monotherapy",
      "Tenofovir alafenamide"],
     "'Drugs : New DAAs, pangenomic drugs with ↑↑ SVR'."),
]

write_part(CH, "p1045a", 1045,
           "HCV structure, lipoviral particle, genome, genes and DAA suffixes, genotypes, transmission", p1045)
write_part(CH, "p1046a", 1046,
           "HCV progression, acute disease, serology and interpretation, SVR, drugs and extrahepatic disease", p1046)

write_units(CH, [
    {"title": "Hepatitis C virus: virology and transmission",
     "sec": "Virology · p1045",
     "guide": "+ve sense RNA Flaviviridae, Hepaciviridae subfamily; lipoviral particle bound to VLDL/LDL causing steatosis (HAV, HBV, HDV, HEV do not); 9.7 kb coding ~3000 amino acid polyprotein; structural and non-structural genes separated by host signal peptidase; DAA suffixes NS3 -previr, NS5A -asvir, NS5B -buvir; 7 genotypes with genotype 1 commonest worldwide and genotype 3 commonest in India with the worst prognosis and cirrhosis/HCC link; transmission percutaneous, transfusion 1 in 10,00,000, perinatal/breast feeding low single digits, IV drug users 40-90%, sexual negligible, commonest in CKD patients; no post-exposure prophylaxis.",
     "parts": ["p1045a"]},
    {"title": "Hepatitis C: natural history, diagnosis and treatment",
     "sec": "Clinical & therapy · p1046",
     "guide": "Incubation ~50 days then acute anicteric hepatitis (usually undiagnosed, variable enzymes, fulminant failure 0.1-1%) → chance for chronic hepatitis → cirrhosis / liver failure / portal hypertension → HCC; serological window with HCV RNA before anti-HCV, waning anti-HCV and seroreversion in clearance; anti-HCV EIA positive means acute/chronic/recovered, negative means no contact except in CKD, haemodialysis or HIV where HCV RNA is needed; fibroscan to rule out cirrhosis; SVR 99.5-99.7% in chronic HCV, 75% in cirrhosis, 60% in decompensated disease; new pangenotypic DAAs with high SVR, treat anyone above 12 years; NS3 glecaprevir/simeprevir, NS5A velpatasvir (not available in India), NS5B sofosbuvir with ribavirin, 12 weeks for chronic HCV with cirrhosis; extrahepatic: Sjogren's, salivary gland marginal zone lymphoma, mixed cryoglobulinaemia type 2/3, porphyria cutanea tarda, lichen planus, MPGN, Hashimoto thyroiditis.",
     "parts": ["p1046a"]},
])
