#!/usr/bin/env python3
"""Ch 67 Nonalcoholic Steatohepatitis — Book p1030-1032, strict source order."""
from itemwriter_64_69 import write_part, write_units

CH = 67

# ---------------------------------------------------------------- p1030
p1030 = [
    ("numeric",
     "How is NAFLD defined under 'Features' of Fatty Liver Disease?",
     ["Macrovesicular fat / steatosis in ≥ 5% of hepatocytes", "Microvesicular fat in ≥ 30% of hepatocytes", "Macrovesicular fat in ≥ 50% of hepatocytes", "Any fat with ALT > 150 U/L"],
     "'NAFLD : macrovesicular fat / steatosis ≥5% hepatocytes (Non alcoholic FLD)'. The micrograph caption reads 'macrovesicular fat in NAFLD'."),
    ("match",
     "NAFLD splits into two groups — match — 1) 80% 2) 20% … A) Fatty liver + inflammation = NASH B) Isolated fatty liver (IFL)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "80% Isolated fatty liver (IFL); 20% Fatty liver + Inflammation: NASH (non-alcoholic steatohepatitis)."),
    ("oddoneout",
     "Four histological components branch from NASH. Which is NOT one of them?",
     ["Mallory–Denk bodies", "Ballooning change", "Degree of steatosis", "Lobular inflammation"],
     "Branches: Ballooning change; Degree of steatosis; Lobular inflammation; Chicken-wire fibrosis (Zone 3)."),
    ("fillup",
     "Fill up: The fibrosis pattern of NASH is '______ fibrosis (Zone ______)'.",
     ["Chicken-wire; 3", "Onion-skin; 1", "Bridging; 2", "Periportal; 1"],
     "'Chicken-wire fibrosis (Zone 3)'."),
    ("oddoneout",
     "Risk-factor table, column 'Common conditions with established association' — which is NOT in that column?",
     ["Hypothyroidism", "Polycystic ovary syndrome", "Starvation / rapid weight loss", "Leptin resistance"],
     "Column 1: Obesity, T2DM/insulin resistance, dyslipidemia, metabolic syndrome, PCOS, starvation/rapid weight loss, ↓ adiponectin, leptin resistance. Hypothyroidism is in column 2."),
    ("truefalse",
     "Judge from column 1: I Adiponectin levels are printed as decreased. II Leptin is printed as deficient.",
     ["I true, II false", "I false, II true", "Both true", "Both false"],
     "'↓ Adiponectin levels' and 'Leptin Resistance' (not deficiency)."),
    ("oddoneout",
     "Column 'Other conditions associated with NAFLD' — which is NOT listed?",
     ["Cushing's syndrome", "Obstructive sleep apnea", "Pancreatoduodenal resection", "Psoriasis"],
     "Column 2: Hypothyroidism, OSA, Hypopituitarism, Hypogonadism, Pancreatoduodenal resection, Psoriasis."),
    ("match",
     "Match — 1) T2DM / insulin resistance 2) Hypopituitarism 3) Hypogonadism … A) Other conditions associated B) Common established association",
     ["1-B, 2-A, 3-A", "1-A, 2-B, 3-B", "1-B, 2-B, 3-A", "1-A, 2-A, 3-B"],
     "T2DM/insulin resistance is column 1; hypopituitarism and hypogonadism are column 2."),
    ("oddoneout",
     "Drugs column — which drug is NOT printed among the six NAFLD-associated drugs?",
     ["Methotrexate", "L-asparaginase", "Griseofulvin", "Amiodarone"],
     "Drugs: L-asparaginase, Bleomycin, Tetracycline, Griseofulvin, Valproate, Amiodarone."),
    ("fillup",
     "Fill up: NASH progression follows a ______-hit hypothesis; the 1st hit is ______.",
     ["2; risk factors", "3; insulin resistance", "2; unknown", "1; obesity"],
     "'2 hit hypothesis — Normal liver —1st hit: Risk factors→ NASH —2nd hit: unknown R/F→ Cirrhosis'."),
    ("numeric",
     "What proportion of NASH patients progress to cirrhosis, and over what period?",
     ["10–15% of patients over 15 years", "20% of patients over 5 years", "1–5% of patients over 10 years", "80% of patients over 15 years"],
     "'2nd hit : unknown R/F — 10–15% pts over 15 yrs → Cirrhosis'."),
    ("scenario",
     "In the progression diagram an arrow runs directly from NASH to HCC, bypassing cirrhosis, labelled 'Only in NASH & ______'. Complete it.",
     ["Hep B virus infection", "Hep C virus infection", "Hemochromatosis", "Alcoholic liver disease"],
     "'Only in NASH & Hep B virus infection' — HCC without intervening cirrhosis. Cirrhosis itself branches to portal hypertension, liver failure and HCC."),
]

# ---------------------------------------------------------------- p1031
p1031 = [
    ("oddoneout",
     "Clinical features table, 'Symptoms' column — which is NOT printed?",
     ["Pruritus", "Vague RUQ pain", "Fatigue", "Malaise"],
     "Symptoms: Vague RUQ pain, Fatigue, malaise."),
    ("match",
     "'Sign' column — hepatomegaly, then four rare signs each bracketed with its meaning. Match — 1) Splenomegaly 2) Spider angiomata 3) Ascites … A) Decompensation B) PHTN C) Liver failure",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "Rare: Splenomegaly (PHTN), Spider angiomata (Liver failure), Palmar erythema, Ascites (Decompensation)."),
    ("truefalse",
     "Judge: I Hepatomegaly is the routine sign of NAFLD. II Palmar erythema is listed among the rare signs.",
     ["Both true", "I true, II false", "I false, II true", "Both false"],
     "Sign: Hepatomegaly; Rare: splenomegaly, spider angiomata, palmar erythema, ascites."),
    ("match",
     "Investigations 1–4 — match — 1) Biopsy 2) S. Ferritin 3) Imaging 4) Enzymes … A) Elevated B) ALT, AST C) Inflammatory changes D) USG → MR elastography > transient elastography",
     ["1-C, 2-A, 3-D, 4-B", "1-C, 2-D, 3-A, 4-B", "1-A, 2-C, 3-D, 4-B", "1-C, 2-A, 3-B, 4-D"],
     "1. Biopsy: inflammatory changes; 2. S. Ferritin: elevated; 3. Imaging: USG → MR elastography > transient elastography; 4. Enzymes: ALT, AST."),
    ("recall",
     "Which imaging modality is ranked higher on this page: MR elastography or transient elastography?",
     ["MR elastography > transient elastography", "Transient elastography > MR elastography", "They are ranked equal", "USG is ranked above both"],
     "'USG → MR Elastography > Transient Elastography'."),
    ("match",
     "Liver fibroscan figure — match — 1) Vs = 1.1 m/s 2) Vs = 1.7 m/s 3) Vs = 3.6 m/s … A) ~ 9 kPa B) ~ 40 kPa C) ~ 3 kPa",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     "Panels: Vs 1.1 m/s ~3 kPa; Vs 1.7 m/s ~9 kPa; Vs 3.6 m/s ~40 kPa, above the F0–F4 scale."),
    ("numeric",
     "The fibroscan figure shows a staging strip from ______ to ______ and the probe illustration cites an explored volume of ______ × ______ cm.",
     ["F0 to F4; 2.5 × 4", "F1 to F5; 1 × 2", "S0 to S3; 2.5 × 4", "F0 to F4; 5 × 10"],
     "Strip F0 F1 F2 F3 F4; the probe inset labels 'Volumen explorado' 2.5 cm and 4 cm."),
    ("management",
     "ALT/AST algorithm: enzymes are normal. What is the printed conclusion?",
     ["IFL (isolated fatty liver)", "NASH without cirrhosis", "Cirrhosis", "Repeat in 6 months"],
     "'ALT, AST → Normal → IFL'."),
    ("match",
     "Enzymes ↑↑ (<150 U/L) — match — 1) AST < ALT 2) AST > ALT … A) Cirrhosis B) NASH (risk & cirrhosis)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     "'↑↑ (<150 U/L) → AST<ALT → NASH (Risk & cirrhosis); AST>ALT → Cirrhosis'."),
    ("scenario",
     "A 45-year-old obese diabetic has ALT 110, AST 70 U/L. Following the algorithm, fibroscan is done and stiffness is markedly raised (↑↑). What is the final printed label?",
     ["NASH with cirrhosis", "NASH without cirrhosis", "IFL", "Alcoholic hepatitis"],
     "AST<ALT → NASH → Fibroscan → (N) NASH without cirrhosis / ↑↑ NASH with cirrhosis."),
]

# ---------------------------------------------------------------- p1032
p1032 = [
    ("numeric",
     "Supportive treatment of NASH — what weight-loss target and exercise prescription are printed?",
     ["Weight loss 10% over 6 months; exercise 30–45 min/day × 5 days/week", "Weight loss 5% over 3 months; exercise 60 min/day × 7 days/week", "Weight loss 15% over 12 months; exercise 20 min/day × 3 days/week", "Weight loss 10% over 1 month; exercise 30 min × 2 days/week"],
     "'Weight loss : 10% over 6 months. Exercise : 30 – 45 minutes / day × 5 day / wk.'"),
    ("fillup",
     "Fill up the third supportive bullet: '______ fatty acids, ______'.",
     ["Omega 3; caffeine", "Omega 6; green tea", "Saturated; alcohol", "Trans; sucrose"],
     "'Omega 3 fatty acids, caffeine.'"),
    ("numeric",
     "Vitamin E is the printed DOC for NASH. What dose is given?",
     ["800–1000 unit/day", "400 unit/day", "100–200 unit/day", "2000 unit/day"],
     "'DOC : Vitamin E — 800–1000 unit/day.'"),
    ("truefalse",
     "Judge the Vitamin E sub-bullets: I Improves NASH. II Its efficacy in cirrhosis is unknown. III Takes about 2 years to show effect.",
     ["All three true", "I and II true, III false", "I true, II and III false", "I and III true, II false"],
     "'improves NASH, unknown efficacy in cirrhosis' and 'takes ~2 years to show effect'."),
    ("recall",
     "Saroglitazar (4 mg) works by which mechanism, per the book?",
     ["Dual PPAR-α + PPAR-γ agonist", "PPAR-γ agonist only", "GLP-1 receptor agonist", "Farnesoid X receptor agonist"],
     "'Saroglitazar (4mg) : Dual PPAR-α + PPAR-γ agonist.'"),
    ("match",
     "Match — 1) Pioglitazone 2) Oral semaglutide 3) Saroglitazar … A) GLP-1 RA B) PPAR-γ agonist (may be tried) C) Dual PPAR-α + γ agonist",
     ["1-B, 2-A, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A", "1-A, 2-B, 3-C"],
     "Pioglitazone PPAR-γ agonist (may be tried); Oral semaglutide GLP-1 RA (receptor agonist); Saroglitazar dual PPAR-α+γ."),
]

write_part(CH, "p1030a", 1030, "FLD features, NASH histology, risk-factor table and 2-hit progression", p1030)
write_part(CH, "p1031a", 1031, "Clinical features, investigations, fibroscan figure and enzyme algorithm", p1031)
write_part(CH, "p1032a", 1032, "Supportive treatment and drugs", p1032)

write_units(CH, [
    {"title": "NAFLD definition, NASH histology, risk factors and progression",
     "sec": "Features & risk · p1030",
     "guide": "Macrovesicular fat ≥5% hepatocytes; 80% IFL vs 20% NASH; ballooning, steatosis degree, lobular inflammation, chicken-wire zone-3 fibrosis; established (obesity, T2DM/IR, dyslipidemia, MetS, PCOS, starvation, ↓adiponectin, leptin resistance), other (hypothyroid, OSA, hypopituitarism, hypogonadism, pancreatoduodenal resection, psoriasis), drugs (L-asparaginase, bleomycin, tetracycline, griseofulvin, valproate, amiodarone); 2-hit, 10–15% over 15 yrs, direct HCC only in NASH & HBV.",
     "parts": ["p1030a"]},
    {"title": "Clinical features, investigations, fibroscan and the ALT/AST algorithm",
     "sec": "Clinical & work-up · p1031",
     "guide": "Vague RUQ pain, fatigue, malaise; hepatomegaly; rare splenomegaly (PHTN), spider angiomata (liver failure), palmar erythema, ascites (decompensation); biopsy, ferritin, USG → MR elastography > transient elastography, ALT/AST; Vs 1.1/1.7/3.6 m/s ≈ 3/9/40 kPa, F0–F4; normal → IFL; <150 AST<ALT → NASH → fibroscan N/↑↑; AST>ALT → cirrhosis.",
     "parts": ["p1031a"]},
    {"title": "Treatment: lifestyle and drugs",
     "sec": "Treatment · p1032",
     "guide": "10% weight loss over 6 months; 30–45 min × 5 days/week; omega-3, caffeine; vitamin E DOC 800–1000 U/day, improves NASH, unknown in cirrhosis, ~2 years; saroglitazar 4 mg dual PPAR-α/γ; pioglitazone PPAR-γ may be tried; oral semaglutide GLP-1 RA.",
     "parts": ["p1032a"]},
])
